### PR TITLE
fix naive global ReactOnRails references

### PR DESCRIPTION
**Pull request by Judahmeek**
Here's the PR I promised. One possible change I was considering was including https://github.com/rstacruz/jsdom-global instead of partially rolling our own. That's up to you though.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/569)

### CODE REVIEW

**Comment by Judahmeek** [comment]
I don't understand why I don't get the same `no-useless-escape` linting errors that Travis does when I run npm run lint.

**Comment by justin808** [comment]
@judahmeek Looks **EXCELLENT**!

@robwise can you take a quick peek at this. I think this is ready for merge. 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.jscsrc, line 8 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/569#-KUele6r9bLmJSW5Gv7t:-KUele6r9bLmJSW5Gv7u:b-iwpzc9) ([raw file](https://github.com/shakacode/react_on_rails/blob/80e28209b4a9ed5d7ba792a5536831e8369df8ec/.jscsrc#L8)):*
> ```
>   ],
>   "excludeFiles": [
>     "**/.c9/**",
> ```

what is a c9 file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/569#-:-KUemMAKgGI_KY9gtpPR:b8quzri)*

**Comment by justin808** [comment]
@Judahmeek update with latest from master

**Comment by Judahmeek** [comment]
Done

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.jscsrc, line 8 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/569#-KUele6r9bLmJSW5Gv7t:-KUiBWH-f0h-vzmHfJYI:blu6mzt) ([raw file](https://github.com/shakacode/react_on_rails/blob/e4a4992db98b3aed2ff3aad044fd38a7580d84f8/.jscsrc#L8)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> what is a c9 file?
</details>
It's a hidden directory on Cloud 9 VMs that keeps some kind of meta-data in a JSON format and causes jscs to fail. I can remove it if you'd like, but it would be convenient to me if we could leave it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/569#-:-KUiBSpkm_8E1PybsWIx:bb6un1j)*

**Comment by justin808** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.jscsrc, line 8 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/569#-KUele6r9bLmJSW5Gv7t:-KUiIWaCsaxjhkUBv-3S:b-54imli) ([raw file](https://github.com/shakacode/react_on_rails/blob/e4a4992db98b3aed2ff3aad044fd38a7580d84f8/.jscsrc#L8)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary>
> It's a hidden directory on Cloud 9 VMs that keeps some kind of meta-data in a JSON format and causes jscs to fail. I can remove it if you'd like, but it would be convenient to me if we could leave it.
</details>
we can leave

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/569#-:-KUiIYtqaImBMI_NDkmD:bnfp4nl)*

**Pull request merged**
