### PR TITLE
Update hmr-and-hot-reloading-with-the-webpack-dev-server.md

### PR DESCRIPTION
**Pull request by AlexKund**
replacing overlay false with sockPort: [port] plugin option dealing with sockjs-node error

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1311)

### CODE REVIEW

**Comment by justin808** [comment]
@AlexKund did you try:

```
We can probably check this:

process.env.WEBPACK_DEV_SERVER
```

**Comment by AlexKund** [comment]
Yes, Do you want to substitute process.env.NODE_ENV with process.env.WEBPACK_DEV_SERVER?

**Comment by justin808** [comment]
> Yes, Do you want to substitute process.env.NODE_ENV with process.env.WEBPACK_DEV_SERVER?
Definitely! 👍

**Comment by AlexKund** [comment]
@justin808 

> Yes, Do you want to substitute process.env.NODE_ENV with process.env.WEBPACK_DEV_SERVER?

Done

**Comment by justin808** [comment]
@AlexKund Please see 
https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh/commit/cb7037be084e49656b2d6a2412a75bc3db461075

The install needs to be updated per what I used (non-beta version, overlay.sockport, etc.

Please let me know if you want to make this update. Otherwise, I can take over.

**Comment by AlexKund** [comment]
👍. Let me check with not beta version.

**Comment by AlexKund** [comment]
All requirements has been done. Sorry about sockPort - during updating the file and copy paste from my code i miss to place it as part of the overlay option, but now it is ok.

> Otherwise, I can take over.
Of course you can do whatever you think is good in this file.

**Comment by AlexKund** [comment]
@justin808  thank you too 👍

**Pull request merged**
