### PR TITLE
Fix scripts for js linting and linting warnings

### PR DESCRIPTION
**Pull request by AlexKVal**
I've opened `node_package/src` files in my Atom and it started to show me `eslint` warnings.
That's why I've checked `npm run lint` scripts and this PR is the result of it.

atom

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/520)

### CODE REVIEW

**Comment by justin808** [comment]
Good progress. Let's lock the version of the linter to use the latest, and use this config:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json#L99

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.eslintignore, line 8 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXGq2lZFlMvgcfhrBn:-KPXGq2lZFlMvgcfhrBo:b7tyohh) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/.eslintignore#L8)):*
> ```
> node_package/tests/node_modules
> node_package/webpack.config.js
> gen-examples
> ```

we want these to pass linting

---

*[package.json, line 51 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXFzF5pB7htYrHhSer:-KPXFzF5pB7htYrHhSes:b-11z9e) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/package.json#L51)):*
> ```JSON
>     "build": "node_package/scripts/build",
>     "build-watch": "babel --watch --out-dir node_package/lib node_package/src",
>     "eslint": "eslint .",
> ```

this is not right, as this will use the eslint that is globally installed

---

*[node_package/src/clientStartup.js, line 1 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXGDqGybidc-mvD7HH:-KPXGDqGybidc-mvD7HI:bqkv34p) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/node_package/src/clientStartup.js#L1)):*
> ```JavaScript
> /* global ReactOnRails Turbolinks */
> ```

import ReactOnRails

---

*[node_package/src/ReactOnRails.js, line 1 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXGX6bc9reqw1Yme52:-KPXGX6bc9reqw1Yme53:bsm4lih) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/node_package/src/ReactOnRails.js#L1)):*
> ```JavaScript
> /* global ReactOnRails */
> ```

Not sure about this comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-:-KPXGzlFYbPhHYX6o2iR:b-4muayh)*

**Comment by AlexKVal** [comment]
In process. Thanks for the hint!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.eslintignore, line 8 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXGq2lZFlMvgcfhrBn:-KPZVF74GNTHuL1VA03I:binv496) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/.eslintignore#L8)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> we want these to pass linting
</details>
`.gitignore`  ignores this folder thus I've thought it should be ignored as well.
I'll add it back and will make sure about linting.

---

*[package.json, line 51 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXFzF5pB7htYrHhSer:-KPZVcdzY0f7OvIM7uFH:bolgorp) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/package.json#L51)):*
I encountered this question a year ago in `React-Bootstrap`.

Let's check it.
change in `package.json`
```json
  "eslint": "eslint -v",
```
run
```sh
> npm i eslint@2
> npm i -g esling@3
> eslint -v
v3.3.1 (global)
> npm run eslint
v2.13.1 (local)
```
As it turned out:
https://www.sitepoint.com/solve-global-npm-module-dependency-problem/
> Npm scripts will look for a local copy of an executable command in the ./node_modules/.bin/ directory before checking your PATH for it

https://docs.npmjs.com/cli/run-script
> In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix.

To point out that I want to run a locally installed package I should write it with the `node_modules/.bin/` prefix. And we already know that `npm` automatically adds this to any npm-script.
Hence `eslint .` - is the most popular way to run it throughout OSS libraries.

---

*[node_package/src/clientStartup.js, line 1 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXGDqGybidc-mvD7HH:-KPZXUNa_Vfwp1AIZmry:b8j9t0y) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/node_package/src/clientStartup.js#L1)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> import ReactOnRails
</details>
I wasn't sure. Thank you for the help with it.

---

*[node_package/src/ReactOnRails.js, line 1 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXGX6bc9reqw1Yme52:-KPZXT5gWCqMhqgJuoQt:bo461z7) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/node_package/src/ReactOnRails.js#L1)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Not sure about this comment
</details>
Nice catch. It seems I was much more weak and unfocused than I though.
I'll fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-:-KPZV7lcb8_ZAl3OBePL:b-ovewqg)*

**Comment by AlexKVal** [comment]
I have a question that arose after updating linter's versions because of additional rules.

--
The linter now "swears" about the `dangled _` in `_storeGenerators` but I cannot just rename it to `storeGenerators`
because it it already defined as argument.
```js
register(storeGenerators) {
    Object.keys(storeGenerators).forEach(name => {
      if (_storeGenerators.has(name)) { 
```
[here src/StoreRegistry.js#L12:L14](https://github.com/shakacode/react_on_rails/blob/master/node_package/src/StoreRegistry.js#L12:L14)

There are a handful of such occasions throughout the project.

I propose to rename all **_localScopeName** variables with the `dangled _` to something like **privLocalScopeName**
What do you think ? I need help with the more appropriate naming scheme here.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-:-KPZXjHO4_ZGWSlYAro_:b6twigx)*

**Comment by justin808** [comment]
@alexkval  you have a good point.  In most cases, we could do `this.storeGenerators` or, in Ruby, @store_generators.

We either have to change the name of the param or the closure variable.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-:-KPahBF3vGrfXbKJ0R0t:bamtm5s)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.eslintignore, line 8 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXGq2lZFlMvgcfhrBn:-KPahYst8GP2bSOWnE-a:bsvbpmt) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/.eslintignore#L8)):*
<details><summary><i>Previously, AlexKVal (Alexander Shemetovsky) wrote…</i></summary>
> `.gitignore`  ignores this folder thus I've thought it should be ignored as well.
> I'll add it back and will make sure about linting.
</details>
Please do so! Needs to be linted!

---

*[package.json, line 51 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXFzF5pB7htYrHhSer:-KPahm13ErnzmPmWag4n:b-1oks5f) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/package.json#L51)):*
<details><summary><i>Previously, AlexKVal (Alexander Shemetovsky) wrote…</i></summary>
> I encountered this question a year ago in `React-Bootstrap`.
> 
> Let's check it.
> change in `package.json`
> ```json
>   "eslint": "eslint -v",
> ```
> run
> ```sh
> > npm i eslint@2
> > npm i -g esling@3
> > eslint -v
> v3.3.1 (global)
> > npm run eslint
> v2.13.1 (local)
> ```
> As it turned out:
> https://www.sitepoint.com/solve-global-npm-module-dependency-problem/
> > Npm scripts will look for a local copy of an executable command in the ./node_modules/.bin/ directory before checking your PATH for it
> 
> https://docs.npmjs.com/cli/run-script
> > In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix.
> 
> To point out that I want to run a locally installed package I should write it with the `node_modules/.bin/` prefix. And we already know that `npm` automatically adds this to any npm-script.
> Hence `eslint .` - is the most popular way to run it throughout OSS libraries.
</details>
Very nice! Thanks @alexkval! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520)*

**Comment by robwise** [comment]
I hesitate to enforce any sort of naming scheme like that, as it can't be enforced by linting and is often not necessary. I vote we just rename `_storeGenerators` to `registeredStoreCreators`.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[package.json, line 51 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXFzF5pB7htYrHhSer:-KPalw-1XC2bClTgA9Ks:b-1et9h) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/package.json#L51)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Very nice! Thanks @alexkval! 
</details>
I think the confusion may be coming from when you have your npm scripts run `.sh` files, then in those files I'm pretty sure you need to use `$(npm bin)/` to get the local version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-:-KPal60w-WZhCSv5estB:b-80m09e)*

**Comment by justin808** [comment]
Review status: 4 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[node_package/src/clientStartup.js, line 52 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPdSN5NU2cMLw9gLqya:-KPdSN5NU2cMLw9gLqyb:b-ncvtvn) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/node_package/src/clientStartup.js#L52)):*
> ```JavaScript
>   return (typeof Turbolinks.controller !== 'undefined');
> }
> ```

why the re-ordering?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520)*

**Comment by justin808** [comment]
:lgm:

---

Reviewed 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[node_package/src/StoreRegistry.js, line 4 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPdT3-CXPEfiT-l_pWD:-KPdT3-CXPEfiT-l_pWE:b53mmgs) ([raw file](https://github.com/shakacode/react_on_rails/blob/372d3a0090e6b0ea940a6d89f0cb81ea77f667e7/node_package/src/StoreRegistry.js#L4)):*
> ```JavaScript
> // value = redux store creator, which is a function that takes props and returns a store
> const registeredStoreGenerators = new Map();
> const hydratedStores = new Map();
> ```

nice changes!

---

*[node_package/tests/ComponentRegistry.test.js, line 8 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPdTF0Z3XRmm3zTj3l-:-KPdTF0Z3XRmm3zTj3l0:bq9wxoh) ([raw file](https://github.com/shakacode/react_on_rails/blob/372d3a0090e6b0ea940a6d89f0cb81ea77f667e7/node_package/tests/ComponentRegistry.test.js#L8)):*
> ```JavaScript
> import test from 'tape';
> import React from 'react';
> import ComponentRegistry from '../src/ComponentRegistry';
> ```

FWIW (for what it's worth), I like to leave a blank line between library and local imports.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-:-KPdUIetobgS4A-ZcZjo:b-8eqfer)*

**Comment by AlexKVal** [comment]
- I've rebased it to the latest master.
- All previously pointed out issues has been resolved.
- I put it as another one commit to facilitate review process.

--
Thanks @robwise for the help with naming things 🍒 

--
A new issue needs to be created. I'm just silencing it here because this PR is about linting.
> ReactDOM.render() currently returns a reference to the root ReactComponent instance. However, using this return value is legacy and should be avoided because future versions of React may render components asynchronously in some cases. If you need a reference to the root ReactComponent instance, the preferred solution is to attach a callback ref to the root element.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-render-return-value.md
```js
// eslint-disable-next-line react/no-render-return-value
return ReactDOM.render(reactElement, document.getElementById(domNodeId));
```
[src/ReactOnRails.js](https://github.com/shakacode/react_on_rails/pull/520/commits/78e76c493d7a3250c68aa9b3df69b1107cf1d061#diff-ae274fcd65172ec96919e88590fcef08R148)
The code needs to be refactored to be future-proof for next React versions.

--
Another issue needs to be created as well. It's about circular dependencies.
I cannot do this
```diff
- /* global ReactOnRails Turbolinks */
+ import ReactOnRails from './ReactOnRails';
```
in [src/clientStartup.js](https://github.com/shakacode/react_on_rails/pull/520/commits/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2#diff-2b02b66a19627ff0da5b8fed749a5742R1)
It starts to throw an error because of circular dependencies:
`ReactOnRails` imports `clientStartup` which in turn imports `ReactOnRails`
circular

--
Pff.. it takes a lot of time to re-run again and again all those tests and linting even locally and even only parts of them. It seems I just have to get used to it.

**Comment by AlexKVal** [comment]
Review status: 6 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[node_package/src/clientStartup.js, line 52 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPdSN5NU2cMLw9gLqya:-KPdYKUjev4bVhyOBwhF:bbjonfs) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/node_package/src/clientStartup.js#L52)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> why the re-ordering?
</details>
http://eslint.org/docs/rules/no-use-before-define

---

*[node_package/src/StoreRegistry.js, line 4 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPdT3-CXPEfiT-l_pWD:-KPdaiA9FBVKyM4BY7iW:b-vuj8ut) ([raw file](https://github.com/shakacode/react_on_rails/blob/372d3a0090e6b0ea940a6d89f0cb81ea77f667e7/node_package/src/StoreRegistry.js#L4)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> nice changes!
</details>
Thank you :)

---

*[node_package/tests/ComponentRegistry.test.js, line 8 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPdTF0Z3XRmm3zTj3l-:-KPdakVVKkXVPcygStXj:b-bd37k7) ([raw file](https://github.com/shakacode/react_on_rails/blob/372d3a0090e6b0ea940a6d89f0cb81ea77f667e7/node_package/tests/ComponentRegistry.test.js#L8)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> FWIW (for what it's worth), I like to leave a blank line between library and local imports.
</details>
I reformatted node_package/* files accordingly.

---

*[.eslintignore, line 8 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/520#-KPXGq2lZFlMvgcfhrBn:-KPddeZyAxeAhbCC36Zy:bb6un1j) ([raw file](https://github.com/shakacode/react_on_rails/blob/65361055ae6d7cde539cb8bc6aeeb5b18b670bb2/.eslintignore#L8)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Please do so! Needs to be linted!
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520)*

**Comment by justin808** [comment]
Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/520)*

**Pull request merged**
