### PR TITLE
Rework files for asset checking

### PR DESCRIPTION
**Pull request by justin808**
[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/258)

### CODE REVIEW

**Comment by justin808** [comment]
@samnang @robwise Thoughts?

**Comment by samnang** [comment]
*[lib/react_on_rails.rb, line 16 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/258#-K9whtfIgUfOJKNf-EyI:-K9whtfIgUfOJKNf-EyJ:1357075359) ([raw file](https://github.com/shakacode/react_on_rails/blob/689ed803aa69c3a50e9afa3c78f789439876c79e/lib/react_on_rails.rb#L16)):*
As I remember, `invoke` is most common method for callable objects in Java or C#, but it's not so common in Ruby community.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/258)*

**Comment by justin808** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/react_on_rails.rb, line 16 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/258#-K9whtfIgUfOJKNf-EyI:-K9wuTxDo94DkfUZMsM_:-557825303) ([raw file](https://github.com/shakacode/react_on_rails/blob/689ed803aa69c3a50e9afa3c78f789439876c79e/lib/react_on_rails.rb#L16)):*
`ReactOnRails.ensure_assets_compiled` looks better.

Agree?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/258)*

**Comment by justin808** [comment]
This ONE is READY....

**Comment by robwise** [comment]
Reviewed 20 of 21 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[node_package/src/StoreRegistry.js, line 76 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/258#-K9xq84cAhtt3YxHvUbU:-K9xq84d000ODpNIgwJt:799340268) ([raw file](https://github.com/shakacode/react_on_rails/blob/881461e77bca82a581053624ef62ba2c8cf2d255/node_package/src/StoreRegistry.js#L76)):*
What's this file?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/258)*

**Comment by justin808** [comment]
See #253

**Pull request merged**
