### PR TITLE
Only call hide! if defined 

### PR DESCRIPTION
**Pull request by flynfish**
Fixes issue on rails 3.2

### CODE REVIEW

**Comment by justin808** [comment]
@robwise @flynfish what is the effect of not running hide?

**Comment by flynfish** [comment]
@justin808 it's just a convenience method so I don't think there are too many side effects:

http://www.rubydoc.info/docs/rails/4.1.7/Rails%2FGenerators%2FBase.hide!

**Comment by robwise** [comment]
@justin808 @flynfish it makes it so that when you run the command to get a list of generators, the sub-generators that we didn't intend for users to call directly will not appear

**Comment by justin808** [comment]
@flynfish Can you please see if you can call the implementation from Rails 3.x:

```
# File railties/lib/rails/generators/base.rb, line 52
      def self.hide!
        Rails::Generators.hide_namespace self.namespace
      end
```

http://apidock.com/rails/v4.0.2/Rails/Generators/Base/hide!/class

**Comment by justin808** [comment]
@flynfish Any update?

**Comment by flynfish** [comment]
I've been on vacation but I'll try to get to this soon!

**Comment by justin808** [comment]
@flynfish I will try to do a release later today, so if you have a good workaround for this issue, please let me know.

**Comment by flynfish** [comment]
@justin808 unfortunately I haven't had time to try your suggestion and I
won't be able to get to it until next week

**Comment by justin808** [comment]
@flynfish Any update?

**Comment by flynfish** [comment]
@justin808 Closing in preference to #182

**Pull request closed without merging**
