### PR TITLE
Clear hydrated stores

### PR DESCRIPTION
**Pull request by udovenko**
* Create clearHydratedStores() methods for StoreRegistry.js and ReactOnRails.js
* Add clearHydratedStores() invocation to #initialize_redux_stores helper
* Add JS tests

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/785)

### CODE REVIEW

**Comment by justin808** [comment]
Test needs work. Looking promising!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[node_package/src/ReactOnRails.js, line 45 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/785#-KgXZia1z01a2ENwWi9G:-KgXZia1z01a2ENwWi9H:b-ywv8q4) ([raw file](https://github.com/shakacode/react_on_rails/blob/c0b43b28ac59f59fbdfbda8049436928120689cd/node_package/src/ReactOnRails.js#L45)):*
> ```JavaScript
> 
>   /**
>    * Clears hydratedStores to avoid accidental usage of wrong store hydrated in previous/parallel
> ```


1. There's no parallel requests, with the connection pool.
2. This should be down below in the place with the comment HERE, b/c this is internal

---

*[node_package/src/ReactOnRails.js, line 144 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/785#-KgXZwtfzWrAHZyu0RLP:-KgXZwtfzWrAHZyu0RLQ:b-27veei) ([raw file](https://github.com/shakacode/react_on_rails/blob/c0b43b28ac59f59fbdfbda8049436928120689cd/node_package/src/ReactOnRails.js#L144)):*
>  // /////////////////////////////////////////////////////////////////////////////
>   // INTERNALLY USED APIs
>   // /////////////////////////////////////////////////////////////////////////////
>  
HERE for  clearHydratedStores() {

---

*[node_package/tests/ReactOnRails.test.js, line 138 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/785#-KgX_MDn57pwqKrPRU0i:-KgX_MDojiATPC2NPS8N:bjnmq1k) ([raw file](https://github.com/shakacode/react_on_rails/blob/c0b43b28ac59f59fbdfbda8049436928120689cd/node_package/tests/ReactOnRails.test.js#L138)):*
> ```JavaScript
>   }
> 
>   ReactOnRails.registerStore({ storeGenerator });
> ```

`registration` is what user code does to tell React on Rails the store's code.

We need to be testing `setStore` with some value passed in.

```js
 /**
   * Internally used function to set the hydrated store after a Rails page is loaded.
   * @param name
   * @param store (not the storeGenerator, but the hydrated store)
   */
  setStore(name, store) {
    hydratedStores.set(name, store);
  },
```

---

*[node_package/tests/StoreRegistry.test.js, line 102 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/785#-KgX_kna_Fx6ssmYaaSC:-KgX_kna_Fx6ssmYaaSD:b2lyirv) ([raw file](https://github.com/shakacode/react_on_rails/blob/c0b43b28ac59f59fbdfbda8049436928120689cd/node_package/tests/StoreRegistry.test.js#L102)):*
> ```JavaScript
>   StoreRegistry.clearHydratedStores();
>   const expected = new Map();
>   assert.deepEqual(StoreRegistry.stores(), expected);
> ```

see comments for ReactOnRails.test.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/785#-:-KgX_oV3ocbDAPFHqRHA:b3dw7lh)*

**Comment by udovenko** [comment]
As I already showed in #774, there are parallel requests with ConnectionPool...Will fix other notices.

**Comment by justin808** [comment]
One tiny comment and we need the CHANGELOG entry.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[node_package/src/ReactOnRails.js, line 139 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/785#-KgY4yLIMMQAUd4D8F-n:-KgY4yLIMMQAUd4D8F-o:b-wu3mfx) ([raw file](https://github.com/shakacode/react_on_rails/blob/66aca37242183ca74bc962cdb5cb7127b7b8d291/node_package/src/ReactOnRails.js#L139)):*
> ```JavaScript
> 
>   /**
>    * Clears hydratedStores to avoid accidental usage of wrong store hydrated in previous/parallel
> ```

no parallel requests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/785#-:-KgY5Q448vyCf51ivB4L:ba928t6)*

**Comment by udovenko** [comment]
@justin808 It is not a problem to remove word "parallel" form the comment, but could you please tell me why there are "no parallel requests"? I thought in #774 I've showed you that connection can be returned to the pool and any parallel request can check out this connection before current request is finished.

**Comment by justin808** [comment]
@udovenko Each connection (really a JS context) can be served from the pool to a thread for running a snippet of JS code. The number of these "connections" can be configured. They do not, as far as I know, share the same context. Thus, only *ONE* thread at a time has access to the given connection (js context). 

Does that sound about right?

**Comment by udovenko** [comment]
@justin808 Yes you're right. Two threads do not share same ```js_context``` at the same moment but same ```js_context``` can be used by 2 parallel requests in turn. E.g. request A created stores 1 and 2 and returned connection to the pool. Request B started and have acces to both stores in case if it checked out the same ```js_context``` form the pool. By *parallel requsts* I mean requests to the web-server. Please look at the code snippet I've posted in #774.

**Comment by justin808** [comment]
@udovenko, great explanation. We just had different ideas of the potential concurrency issue. I'll merge as-is.

**Comment by udovenko** [comment]
@justin808 I'm not insiting on leaving this comment. Just wanted to clarify...

**Comment by justin808** [comment]
@udovenko Since I merged this, the codeship builds are failing:




These are the failing tests:

https://app.codeship.com/projects/187011/builds/23942593

```
Failed examples:

rspec ./spec/features/integration_spec.rb[15:1:1] # 2 react components, 1 store, server side /server_side_hello_world_shared_store Type in one component changes the other component
rspec ./spec/features/integration_spec.rb[17:1:1] # 2 react components, 1 store, server side, controller setup /server_side_hello_world_shared_store_controller Type in one component changes the other component
rspec ./spec/features/integration_spec.rb[19:1:1] # 2 react components, 1 store, server side, defer /server_side_hello_world_shared_store_defer Type in one component changes the other component
rspec ./spec/features/rails_context_spec.rb[1:2:1:1:1] # rails_context server rendering shared store server_side_hello_world_shared_store check rails context
rspec ./spec/requests/server_render_check_spec.rb:14 # Server Rendering generates server rendered HTML if server renderering enabled for shared redux
rspec ./spec/requests/server_render_check_spec.rb:108 # Server Rendering server rendering railsContext shared redux store matches expected values
```
What's odd is that Travis is passing.

**Comment by udovenko** [comment]
@justin808 Is this issue resolved now? I can't open the link you've provided to see what exactly went wrong. And I have no expirience with CodeShip... But before opening PR I launched both JS and RSpect tests two times and they all were green.

**Comment by justin808** [comment]
Hi @udovenko. I fixed the problem. It was due to the way that codeship was caching npm modules. Thanks for checking back with me.

**Pull request merged**
