### PR TITLE
Make generator recognize application.scss

### LINKED ISSUE #86: Generator Should Recognize application.scss File in Addition to application.css.scss
Currently the generator is looking to append Sass imports into the `app/assets/stylesheets/application.css` file (which it renames to `application.css.scss`) or an `application/assets/stylesheets/application.css.scss`, but it doesn't look for simply `application.scss` and therefore throws an error.

This is extracted from: https://github.com/shakacode/react_on_rails/issues/78#issuecomment-154257465

### PR DESCRIPTION
**Pull request by robwise**
Makes the generator recognize `application.scss` files instead of only looking for `application.css.scss` by just forcing all variations to be `application.scss`.

Fixes #86

We're just forcing any version of application.css or
application.css.scss to be application.scss

This avoids a lot of headache when trying to reference the file
in multiple places, and ensures that users could have either variation without the generator failing.

### CODE REVIEW

**Comment by justin808** [comment]
@robwise what if there's no file at all named application.xxxxx

**Comment by justin808** [comment]
LGTM

**Comment by robwise** [comment]
@justin808 In that case, the generator outputs a message to the user indicating that it was unable to find the file and continues with the build. Do you think we should handle this differently, such as just creating our own application.scss file?

**Comment by justin808** [comment]
@robwise I'd say just create a new file. User can them move code to another file.

**Comment by justin808** [comment]
@robwise I just did a merge commit via the UI on github.

**Comment by robwise** [comment]
@justin808 shouldn't we rebase master, not merge it? It's just noise, right?

**Comment by justin808** [comment]
@robwise go ahead and merge, or if you have time, rebase this to one commit on top of master.

**Pull request merged**
