### PR TITLE
Update generator to add ReactOnRails spec helper

### PR DESCRIPTION
**Pull request by justin808**
* Generator adds line to spec/rails_helper.rb so that running specs will
  ensure assets are compiled.
* Added more diagnostics for server rendering.
* Calls to setTimeout and setInterval are not logged for server
  rendering unless env TRACE_REACT_ON_RAILS is set to YES.
* Other small changes to the generator including adding necessary npm
  scripts to allow React on Rails to build assets.
* npm modules updated for generator.
* Updated all npm dependencies to latest.
* Update to node 5.10.0 for CI
* Change babel-runtime to be a peer dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/362)

### CODE REVIEW

**Comment by jbhatab** [comment]
*[lib/generators/react_on_rails/base_generator.rb, line 194 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/362#-KEOsdkrc5QU0_JUqQQP:-KEOsdkrc5QU0_JUqQQQ:-401352382) ([raw file](https://github.com/shakacode/react_on_rails/blob/b7b2ca425d47b5e8e83bec61504188eecd499246/lib/generators/react_on_rails/base_generator.rb#L194)):*
What about writing these out separately so they stack? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/362)*

**Comment by jbhatab** [comment]
*[lib/generators/react_on_rails/templates/redux/base/client/app/bundles/HelloWorld/containers/HelloWorld.jsx, line 14 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/362#-KEOsuBnqwZqbO7OXk2S:-KEOsuBnqwZqbO7OXk2T:-566152663) ([raw file](https://github.com/shakacode/react_on_rails/blob/b7b2ca425d47b5e8e83bec61504188eecd499246/lib/generators/react_on_rails/templates/redux/base/client/app/bundles/HelloWorld/containers/HelloWorld.jsx#L14)):*
I thought it was best practice to still use class syntax? I don't care much either way though, they both look good. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/362)*

**Comment by justin808** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/generators/react_on_rails/base_generator.rb, line 194 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/362#-KEOsdkrc5QU0_JUqQQP:-KEOzwt73dLcgNKPsXy_:802222206) ([raw file](https://github.com/shakacode/react_on_rails/blob/b7b2ca425d47b5e8e83bec61504188eecd499246/lib/generators/react_on_rails/base_generator.rb#L194)):*
Not sure what you mean by this.

---

*[lib/generators/react_on_rails/templates/redux/base/client/app/bundles/HelloWorld/containers/HelloWorld.jsx, line 14 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/362#-KEOsuBnqwZqbO7OXk2S:-KEP-0LLbL2eOeogG1a5:1073747563) ([raw file](https://github.com/shakacode/react_on_rails/blob/b7b2ca425d47b5e8e83bec61504188eecd499246/lib/generators/react_on_rails/templates/redux/base/client/app/bundles/HelloWorld/containers/HelloWorld.jsx#L14)):*
Linter requires this now. If no use of class stuff, then you have to change to SFC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/362)*

**Comment by jbhatab** [comment]
*[lib/generators/react_on_rails/base_generator.rb, line 194 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/362#-KEOsdkrc5QU0_JUqQQP:-KEU3HbJ9NuMk0RmsglH:-856379430) ([raw file](https://github.com/shakacode/react_on_rails/blob/fa16c9a3afe2dfd5de9d9edc61308b02ce7755c1/lib/generators/react_on_rails/base_generator.rb#L194)):*
I just meant make these checks into two separate checks. So have the rails helper check separate from the spec helper check. It's fine as is thoughl

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/362)*

**Comment by jbhatab** [comment]
Reviewed 16 of 19 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/362)*

**Pull request merged**
