### PR TITLE
Clean up a bit travis.yml

### PR DESCRIPTION
**Pull request by AlexKVal**
Remove installation of [npm poltergeist package](https://www.npmjs.com/package/poltergeist). It seems a typo.

--
`TravisCI`'s recommended way to run `Xvfb` https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
> Note: Don’t run `xvfb` directly, as it does not handle multiple concurrent instances that way.

--
The [npm config set spin false](https://github.com/emberjs/ember.js/blob/86f65045fddd5fdd09685f39884230474dd2e111/.travis.yml#L14) speeds things a bit up.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/516)

### CODE REVIEW

**Comment by justin808** [comment]
@alexkval Thanks!

@dylangrafmyre You'd be better to review this me. If this looks good to you, let's merge this.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-:-KOwrEflHVruM8tGW3ey:b-vwn2qz)*

**Comment by justin808** [comment]
@dylangrafmyre Travis passed, FWIW.

**Comment by dylangrafmyre** [comment]
@justin808 @alexkval I have not run the ci rake task locally for this repo for a while. 
I do not know what is required for it to run successfully. 

However, if it can pass by using PhantomJs and Poltergeist than maybe some of this `.travis.yml before_install` items can be deleted?

Sometime all of these things get patched together to make it work because of web driver prior failures with react,etc. Maybe now it might be worth stripping down the the basics in the `.travis.yml` and testing if the suite works with only phantomjs and poltergeist?

But if this is what it takes now to get CI passing that is fine too. Just sometimes you need to revisit the CI config because of changes to the node_modules and gems that have adapted and provide better support for our tool chain.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-:-KOxQU8fx6NClAE6Hbwm:b-c9ezq3)*

**Comment by dylangrafmyre** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/516)*

**Comment by AlexKVal** [comment]
> Maybe now it might be worth stripping down the the basics in the .travis.yml and testing if the suite works with only phantomjs and poltergeist?

I've tried to run tests with `PhantomJS` instead of `Chome` on `TravisCI`.
https://travis-ci.org/AlexKVal/react_on_rails/builds/151347102
`PhantomJS` crashes.
phantomjs

I did not do any additional research about it.

Though locally `phantomjs@2.1.1` all runs OK.

**Comment by AlexKVal** [comment]
I've made "install" section a bit simpler and added caching.

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 34 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-KPJetg9DDDwuhj5uxLK:-KPJetg9DDDwuhj5uxLL:b-pztfx2) ([raw file](https://github.com/shakacode/react_on_rails/blob/4ff4656b47fe1a3332726ad476f77d47670a2378/.travis.yml#L34)):*
> ```YAML
> 
> install:
>   - nvm install 5
> ```

@alexkval @dylangrafmyre Why not version 6? or just latest node or LTS:

https://github.com/creationix/nvm#usage

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/516)*

**Comment by dylangrafmyre** [comment]
@alexkval Here is an example for getting phantomjs 2.1 + installed within .travis.yml
https://github.com/testdouble/present/blob/57deb323731c23607d4e3cafd709ec062d9b6666/.travis.yml

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 34 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-KPJetg9DDDwuhj5uxLK:-KPJgyws7MdRWDuLcgnL:b-vuiclc) ([raw file](https://github.com/shakacode/react_on_rails/blob/4ff4656b47fe1a3332726ad476f77d47670a2378/.travis.yml#L34)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> @alexkval @dylangrafmyre Why not version 6? or just latest node or LTS:
> 
> https://github.com/creationix/nvm#usage
</details>
It should be updated to version 6.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-:-KPJgkcpxiYRorY19ZIr:bmb25ll)*

**Comment by AlexKVal** [comment]
Thank you for the help. I'll check it out and report on it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 34 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-KPJetg9DDDwuhj5uxLK:-KPK_w29BEPelpAuTAIN:b4xsuhz) ([raw file](https://github.com/shakacode/react_on_rails/blob/4ff4656b47fe1a3332726ad476f77d47670a2378/.travis.yml#L34)):*
<details><summary><i>Previously, dylangrafmyre (Dylan Grafmyre) wrote…</i></summary>
> It should be updated to version 6.
</details>
I wasn't sure if it is right to propose the node's version update.
Then should I rewrite it as `nvm install 6`
or `nvm install node` to always get the latest stable ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-:-KPKafOVTN7aXx7CGySw:b-6jzdul)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 34 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-KPJetg9DDDwuhj5uxLK:-KPKlk9-R7iamaAvlRji:be571eh) ([raw file](https://github.com/shakacode/react_on_rails/blob/4ff4656b47fe1a3332726ad476f77d47670a2378/.travis.yml#L34)):*
<details><summary><i>Previously, AlexKVal (Alexander Shemetovsky) wrote…</i></summary>
> I wasn't sure if it is right to propose the node's version update.
> Then should I rewrite it as `nvm install 6`
> or `nvm install node` to always get the latest stable ?
> 
</details>
I think the latter. I want to know if one day we become incompatible with the latest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/516)*

**Comment by AlexKVal** [comment]
I've just changed `npm install node` and added `node -v`.

--
`TravisCI` now has Phantom@2.0.0 by default.
It crashes.
I've tried the provided link with Phantom@2.1.1. It also crashes.
https://travis-ci.org/AlexKVal/react_on_rails/builds/152966747

crach

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/516#-:-KPX9PFUuw96ImV4VwI1:bnfp4nl)*

**Comment by justin808** [comment]
Thanks @AlexKVal!

**Pull request merged**
