### PR TITLE
Fixes to avoid yak shave with redux_store

### PR DESCRIPTION
**Pull request by justin808**
We had a major yak shave when figuring out why setting up the store from
a content_for block caused majore issues.

The following doc changes and enhanced error messages will save others
from this pain.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/470)

### CODE REVIEW

**Comment by justin808** [comment]
@robwise @jbhatab Please review.

**Comment by justin808** [comment]
@jbhatab, @thewoolleyman @martyphee Any opinions?

**Comment by thewoolleyman** [comment]
@jbhatab, @thewoolleyman @martyphee

Glanced at it, more docs and better messages seem good, but...

...FYI, I'm out of the loop and not doing much with React on Rails directly (although we are definitely still using it on Tracker, and plan on using it more to move towards a more mono-repo architecture for our now-separate-repo node apps, the patterns and conventions it establishes are great for that).  

On my personal projects, I've backed up and am focusing on learning Elm as an alternative to Redux+React (actually learning the fundamentals of Haskell first, so I'm strong in the FP fundamentals before diving into Elm).  

Not to disparage React-on-Rails, as I said, the "conventions" of structure, webpack configs, etc, are great and very much in the spirit of rails.  I'm more backing up and seeing the flaws of JS/ES6 as a language, because I've seen the value of strong typing in Elm, which makes many errors like this impossible (e.g. an undefined parameter, which I believe is exactly the bug at the root of this issue).  Tracker as a team I believe is also coming to this general position on Elm.

I'd love to see "react-on-rails" perhaps evolve into something that gives all the mentioned benefits of convention and "just works" webpack configs, but while allowing the use of Elm as an alternative to React+Redux.  Once I learn more (which is slow going for me) I'll perhaps try to help with this.

Anyway, just a heads up on why I've gone mostly dark, sorry to put it on this random issue, but you mentioned me so wanted to be transparent.  Glad to post this in a more general place if you think it's of wider interest.

Thanks,
-- Chad

**Comment by jbhatab** [comment]
*[node_package/src/StoreRegistry.js, line 10 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/470#-KMQM9WEe6mLoE3tdK83:-KMQM9WEe6mLoE3tdK84:-1427668697) ([raw file](https://github.com/shakacode/react_on_rails/blob/a7f600a414f762c5dc49b1dbdd43e2af34293b07/node_package/src/StoreRegistry.js#L10)):*
> ```JavaScript
>   /**
>    * Register a store generator, a function that takes props and returns a store.
>    * @param storeGenerators { name1: storeGenerator1, name2: storeGenerator2 }
> ```

what's this store generator thing about?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/470)*

**Comment by jbhatab** [comment]
*[node_package/src/StoreRegistry.js, line 10 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/470#-KMQM9WEe6mLoE3tdK83:-KMQN-vau5OE-fy3l5xc:-110173586) ([raw file](https://github.com/shakacode/react_on_rails/blob/a7f600a414f762c5dc49b1dbdd43e2af34293b07/node_package/src/StoreRegistry.js#L10)):*
<details><summary><i>Previously, jbhatab (Blaine Hatab) wrote…</i></summary>
> what's this store generator thing about?
</details>
Just not sure why you broke it out to 2 exactly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/470)*

**Comment by jbhatab** [comment]
Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/470)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/src/StoreRegistry.js, line 10 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/470#-KMQM9WEe6mLoE3tdK83:-KMQflEm4BI8fGUnIzWQ:-2061259693) ([raw file](https://github.com/shakacode/react_on_rails/blob/a7f600a414f762c5dc49b1dbdd43e2af34293b07/node_package/src/StoreRegistry.js#L10)):*
<details><summary><i>Previously, jbhatab (Blaine Hatab) wrote…</i></summary>
> Just not sure why you broke it out to 2 exactly?
</details>
just clarifying the docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/470)*

**Comment by martyphee** [comment]
LGTM.  We're not using redux anywhere and probably won't so I haven't seen anything like this.

**Pull request merged**
