### PR TITLE
Switch to yarn and Webpack v2 for default generators

### PR DESCRIPTION
**Pull request by justin808**
Now that webpack v2 is out, let's update to yarn and Webpack v2.

Any volunteers to help us finish up this one?

@marcusmolchany? @squadette?  

This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/622)

### CODE REVIEW

**Comment by justin808** [comment]
@robwise Please review.

**Comment by justin808** [comment]
This is blocked by this issue: https://github.com/yarnpkg/yarn/pull/1498

Once this is done, we can continue with yarn.

😢

**Comment by marcusmolchany** [comment]
looks like bestander replied and said `0.18.0` fixed this issue. need any help with this PR?

**Comment by justin808** [comment]
@marcusmolchany I'd be thrilled if you'd take this one on. You can create a fork and create a branch off my branch here!

**Comment by justin808** [comment]
@marcusmolchany let me know if you can get this done this week.

**Comment by marcusmolchany** [comment]
hey @justin808 i copied down your branch and rebased to `origin/master` but had a few failing tests. i'm on vacation after today so i don't think i can take another stab at it until next week.

**Comment by justin808** [comment]
@marcusmolchany Any word on this one?

**Comment by marcusmolchany** [comment]
hey @justin808 looking at this again today, i'll keep you posted!

**Comment by squadette** [comment]
I did some updating and rebasing on https://github.com/squadette/react_on_rails/commits/use-yarn branch.

https://github.com/shakacode/react_on_rails/pull/646 is also there.

I'll submit PR when ready.

Thanks,

**Comment by justin808** [comment]
@squadette Any update? I'd like to get this one ASAP.

**Comment by marcusmolchany** [comment]
@squadette @justin808 i haven't had time to update my branch so going to stop working on this if you are making progress

**Comment by squadette** [comment]
Well, few more commits later it passes the test suite.  I'm going to rebase commits in a logical order.

But, suddenly, rubocop decided to run and find 300+ trivial "offences", I wonder if that's really necessary.

**Comment by justin808** [comment]
@squadette Did you submit a PR?

**Comment by squadette** [comment]
This is my current branch: https://github.com/squadette/react_on_rails/commits/yarn-for-upstream

but it's failing in Travis, because of some issue with Yarn which looks like bug in Yarn.  however, this is extremely suspicious, because it's the first time I see bugs in Yarn!

Here is the travis build: https://travis-ci.org/squadette/react_on_rails/builds/195203670

If anybody can fix that (maybe it's possible by downgrading Yarn back to 0.18.1) — feel free to use that branch.  

I'm going to continue working on that again later.

**Comment by justin808** [comment]
@squadette Thanks for working on this...You might want to

1. Run basic generator, commit and push to github repo
2. Make changes needed for yarn and Webpack v2 in a PR and I'll review.
3. Once we agree on the changes, then we can update the generators.

Yarn and Webpack v2 are ready!

**Comment by squadette** [comment]
Please see https://github.com/shakacode/react_on_rails/pull/715

**Comment by justin808** [comment]
See #715. version 6.6.0!

**Pull request closed without merging**
