### PR TITLE
Extracts Options for react_component helper

### PR DESCRIPTION
**Pull request by mapreal19**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/384)

### CODE REVIEW

**Comment by justin808** [comment]
Looks good -- CI needs to pass and please don't remove the comments per the comments below.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[app/helpers/react_on_rails_helper.rb, line 104 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/384#-KFIj5B90AIAQxAKDKH5:-KFIj5B90AIAQxAKDKH6:1071522396) ([raw file](https://github.com/shakacode/react_on_rails/blob/5e0b7d5042996b4da9a1c9e2c88acbccada356e7/app/helpers/react_on_rails_helper.rb#L104)):*
Please do not remove these comments

---

*[app/helpers/react_on_rails_helper.rb, line 111 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/384#-KFIjBkglNHglPU0Mira:-KFIjBkglNHglPU0Mirb:1071522396) ([raw file](https://github.com/shakacode/react_on_rails/blob/5e0b7d5042996b4da9a1c9e2c88acbccada356e7/app/helpers/react_on_rails_helper.rb#L111)):*
Please do not remove these comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/384#-:-KFIjHtF127mRIWgqtZr:-1597676270)*

**Comment by mapreal19** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/helpers/react_on_rails_helper.rb, line 104 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/384#-KFIj5B90AIAQxAKDKH5:-KFOG-kJrPiRtepvksaU:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/5e0b7d5042996b4da9a1c9e2c88acbccada356e7/app/helpers/react_on_rails_helper.rb#L104)):*
Done.

---

*[app/helpers/react_on_rails_helper.rb, line 111 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/384#-KFIjBkglNHglPU0Mira:-KFOG0uvzvt3GOayTGQy:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/5e0b7d5042996b4da9a1c9e2c88acbccada356e7/app/helpers/react_on_rails_helper.rb#L111)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/384)*

**Comment by justin808** [comment]
:lgtm: @mapreal19 Please sync with master and I'll merge this.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/384#-:-KFm5GJ52O-TlK53Xna9:258540305)*

**Comment by mapreal19** [comment]
Done :shipit: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/384#-:-KFmSLuKF_xEpwn_UwJ1:959478094)*

**Pull request merged**
