### PR TITLE
Update all gems with bundle update

### PR DESCRIPTION
**Pull request by justin808**
Also updated with some rubocop fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/657)

### CODE REVIEW

**Comment by justin808** [comment]
@volkanunsal I'm working on the changes here. I'll notify you when these are complete.

**Comment by justin808** [comment]
@volkanunsal for some reason, this passes CI, but not locally. Can you try to run this locally and let me know if it passes for you?

**Comment by volkanunsal** [comment]
@justin808 I get a few Capybara::Poltergeist::DeadClient errors coming from

```

rspec ./spec/features/integration_spec.rb:173 # Code Splitting w/ Server Rendering loading an asyncronous route should not cause a client/server checksum mismatch
rspec './spec/features/integration_spec.rb[16:1:1]' # 2 react components, 1 store, client only, defer /client_side_hello_world_shared_store_defer Type in one component changes the other component
```

**Comment by justin808** [comment]
@volkanunsal I seem to be having a problem with my local setup. Can you please review the changes and if you get 👍 , then I'll merge this.

CC: @robwise @Judahmeek

**Comment by justin808** [comment]
I need to update all the node dependencies to run on Mac 10.12.2.  Node-sass would not install at the older version.

These routes are failing locally for me:
https://github.com/shakacode/react_on_rails/pull/581/files#diff-9add427c64dd00c28db028f434f8fc11L22

@jtibbertsma @volkanunsal @Judahmeek 

I'd be extremely grateful if any of you want to give me a hand with this.

**Comment by jtibbertsma** [comment]
@justin808 Yeah, I'll take a look.

**Comment by jtibbertsma** [comment]
@justin808 These routes still work as long as you navigate to them before going to the main react router route. This is actually [#613](https://github.com/shakacode/react_on_rails/issues/613).

Also, I'm getting `Poltergeist::DeadClient` errors when I run rspec. Could be related to code splitting?

**Comment by jtibbertsma** [comment]
The tests pass when using anything other than Poltergeist. How strange.

**Comment by justin808** [comment]
@jtibbertsma I updated for the linters.

PLEASE be sure to rm -rf the node module directories at the top level and in spec/dummy/client

**Comment by justin808** [comment]
I just did another lint fix.

If anybody could update to this version of the linter: 13.2.0: https://github.com/shakacode/style-guide-javascript/blob/master/packages/eslint-config-shakacode/README.md, I'd really appreciate it!

**Comment by justin808** [comment]
@volkanunsal I got the linting to pass, and I updated the linters.

Let's fix these tests related to your prior test. Please fork/branch off of this branch.
```
Failures:

  1) Manual Rendering renderer function is called successfully
     Failure/Error: background { visit "/client_side_manual_render" }

     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       Exception in rendering!
       Exception in rendering!
           at :53 in default
       message: _registerComponent(...): Target container is not a DOM element.
       message: _registerComponent(...): Target container is not a DOM element.
           at :65 in default
       stack: invariant
       _renderNewRootComponent
       _renderSubtreeIntoContainer
       render
       default
       createReactElement
       render
       forEach
       forEachComponent
       reactOnRailsPageLoaded
       dispatchEvent@[native code]
       triggerEvent@http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5235:34
       http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5604:19
       stack: invariant
       _renderNewRootComponent
       _renderSubtreeIntoContainer
       render
       default
       createReactElement
       render
       forEach
       forEachComponent
       reactOnRailsPageLoaded
       dispatchEvent@[native code]
       triggerEvent@http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5235:34
       http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5604:19
           at :66 in default
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/browser.rb:376:in `command'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/browser.rb:35:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/driver.rb:97:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:148:in `block (2 levels) in <top (required)>'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:112:in `block in run'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:101:in `loop'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:101:in `run'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:30:in `block (2 levels) in setup'

  2) Code Splitting clicking on async route causes async component to be fetched
     Failure/Error: background { visit "/deferred_render_with_server_rendering" }

     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       Exception in rendering!
       Exception in rendering!
           at :53 in default
       message: _registerComponent(...): Target container is not a DOM element.
       message: _registerComponent(...): Target container is not a DOM element.
           at :65 in default
       stack: invariant
       _renderNewRootComponent
       _renderSubtreeIntoContainer
       render



       done

       getComponentsForRoute


       forEach@[native code]
       mapAsync
       getComponents
       finishEnterHooks
       runTransitionHooks
       runEnterHooks

       runTransitionHooks
       runChangeHooks
       finishMatch

       next
       loopAsync
       matchRoutes
       match
       match
       DeferredRenderAppRenderer
       createReactElement
       render
       forEach
       forEachComponent
       reactOnRailsPageLoaded
       dispatchEvent@[native code]
       triggerEvent@http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5235:34
       http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5604:19
       stack: invariant
       _renderNewRootComponent
       _renderSubtreeIntoContainer
       render



       done

       getComponentsForRoute


       forEach@[native code]
       mapAsync
       getComponents
       finishEnterHooks
       runTransitionHooks
       runEnterHooks

       runTransitionHooks
       runChangeHooks
       finishMatch

       next
       loopAsync
       matchRoutes
       match
       match
       DeferredRenderAppRenderer
       createReactElement
       render
       forEach
       forEachComponent
       reactOnRailsPageLoaded
       dispatchEvent@[native code]
       triggerEvent@http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5235:34
       http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5604:19
           at :66 in default
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/browser.rb:376:in `command'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/browser.rb:35:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/driver.rb:97:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:158:in `block (2 levels) in <top (required)>'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:112:in `block in run'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:101:in `loop'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:101:in `run'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:30:in `block (2 levels) in setup'

  3) Code Splitting w/ Server Rendering loading an asyncronous route should not cause a client/server checksum mismatch
     Failure/Error: background { visit "/deferred_render_with_server_rendering/async_page" }

     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       Exception in rendering!
       Exception in rendering!
           at :53 in default
       message: undefined is not an object (evaluating 'reactElementOrRouterResult.redirectLocation')
       message: undefined is not an object (evaluating 'reactElementOrRouterResult.redirectLocation')
           at :65 in default
       stack: isRouterResult
       render
       forEach
       forEachComponent
       reactOnRailsPageLoaded
       dispatchEvent@[native code]
       triggerEvent@http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5235:34
       http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5604:19
       stack: isRouterResult
       render
       forEach
       forEachComponent
       reactOnRailsPageLoaded
       dispatchEvent@[native code]
       triggerEvent@http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5235:34
       http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:5604:19
           at :66 in default
       Invariant Violation: _registerComponent(...): Target container is not a DOM element.
       Invariant Violation: _registerComponent(...): Target container is not a DOM element.
           at undefined:51 in invariant
           at :311 in _renderNewRootComponent
           at :401 in _renderSubtreeIntoContainer
           at :422 in render
           at :51
           at :67
           at :99
           at :79 in done
           at :85
           at :35
           at http://127.0.0.1:53545/assets/application_static-694400e84f289e5549515d908a790d589bb7c000dbe0589740c2c0e1b8b27238.js:41 in webpackJsonpCallback
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/browser.rb:376:in `command'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/browser.rb:35:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/poltergeist-1.12.0/lib/capybara/poltergeist/driver.rb:97:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:172:in `block (2 levels) in <top (required)>'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:112:in `block in run'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:101:in `loop'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:101:in `run'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:30:in `block (2 levels) in setup'

Finished in 26.55 seconds (files took 6.48 seconds to load)
74 examples, 3 failures

Failed examples:

rspec ./spec/features/integration_spec.rb:149 # Manual Rendering renderer function is called successfully
rspec ./spec/features/integration_spec.rb:159 # Code Splitting clicking on async route causes async component to be fetched
rspec ./spec/features/integration_spec.rb:173 # Code Splitting w/ Server Rendering loading an asyncronous route should not cause a client/server checksum mismatch
```

**Comment by justin808** [comment]
@jtibbertsma @volkanunsal I got it. Please rebase your PRs on top of this one after I merge.

**Pull request merged**
