### PR TITLE
Improve i18n Integration

### PR DESCRIPTION
**Pull request by justin808**
* Better error message if the value of the i18n directory is invalid.
* Added test for configuration error message.
* DRY'd up code for checking if this config value is set.
* Improved comments in sample react_on_rails.rb config file

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/748)

### CODE REVIEW

**Comment by justin808** [comment]
@JasonYCHuang Please review!

**Comment by justin808** [comment]
@robwise any quick review?

**Comment by justin808** [comment]
@JasonYCHuang and @robwise Please review!

**Comment by JasonYCHuang** [comment]
:lgtm:

I created a test project to test this, and it works good.

Maybe we can add red color to error message in the future. 
That will be easier to identify what happens.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/748#-:-KeSopLcwMV4kDu4Nm2q:b-gp09yb)*

**Pull request merged**
