### PR TITLE
have rails start on port 3000 (foreman uses 5000 by default)

### PR DESCRIPTION
**Pull request by joyvuu-dave**
This addresses #402.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/456)

### CODE REVIEW

**Comment by justin808** [comment]
@jbhatab Can you please review. This concerned the generator changes.

**Comment by jbhatab** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/456)*

**Comment by jbhatab** [comment]
LGTM

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/456#-:-KM6XmKNLfN-xikrdN87:676834233)*

**Comment by justin808** [comment]
See #467. Merged.

**Pull request closed without merging**
