### PR TITLE
Use <script type="application/json"> for props and store

### PR DESCRIPTION
**Pull request by cheremukhin23**
See discussion in https://github.com/shakacode/react_on_rails/pull/760

Change code according to unresolved discussions in https://github.com/shakacode/react_on_rails/pull/760

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/775)

### CODE REVIEW

**Comment by justin808** [comment]
Looks excellent! Just a couple small comments.

---

Reviewed 13 of 17 files at r1, 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/react_component/options.rb, line 9 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGetrZR7fW60cDMPTJ:-KgGetrZR7fW60cDMPTK:b-nf9yya) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/lib/react_on_rails/react_component/options.rb#L9)):*
> ```Ruby
> 
>       NO_PROPS = {}.freeze
>       HIDDEN = "display:none".freeze
> ```

I think we can remove HIDDEN

---

*[lib/react_on_rails/react_component/options.rb, line 57 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGf8_3lic2Lf2DVFt7:-KgGf8_3lic2Lf2DVFt8:b-js942m) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/lib/react_on_rails/react_component/options.rb#L57)):*
> ```Ruby
>       end
> 
>       def style
> ```

We can probably remove `style` since we're removing HIDDEN

---

*[spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, line 62 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGfajE_odoX00NyVAR:-KgGfajE_odoX00NyVAS:b-hk7wvw) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/spec/dummy/spec/helpers/react_on_rails_helper_spec.rb#L62)):*
> ```Ruby
>     let(:id) { "App-react-component-0" }
> 
>     # rubocop:disable Metrics/LineLength
> ```

You can break the string with `\` at the end, so the line is not crazy long, and remove the lint disable

---

*[spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, line 93 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGhHqqnmMvuN2fDelr:-KgGhHqqnmMvuN2fDels:b1abr2m) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/spec/dummy/spec/helpers/react_on_rails_helper_spec.rb#L93)):*
> ```Ruby
> 
>       let(:react_definition_script) do
>         # rubocop:disable Metrics/LineLength
> ```

try to avoid if possible

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-:-KgGhQIi6ZKYc17Ro8nV:b3wyd00)*

**Comment by justin808** [comment]
@cheremukhin23: CI failures:

```
Failures:
  1) Pages/Index Server Rendering with Options changes name in message according to input
     Failure/Error: is_expected.to have_content new_text
       expected to find text "John Doe" in "Hello, Mr. Server Side Rendering!"
     Shared Example Group: "React Component" called from ./spec/features/integration_spec.rb:61
     # ./spec/features/integration_spec.rb:9:in `block (2 levels) in change_text_expect_dom_selector'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.12.1/lib/capybara/session.rb:310:in `within'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.12.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:8:in `block in change_text_expect_dom_selector'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.12.1/lib/capybara/session.rb:310:in `within'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.12.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:6:in `change_text_expect_dom_selector'
     # ./spec/features/integration_spec.rb:18:in `block (2 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec/retry.rb:112:in `block in run'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec/retry.rb:101:in `loop'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec/retry.rb:101:in `run'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec/retry.rb:30:in `block (2 levels) in setup'
  2) Turbolinks across pages changes name in message according to input
     Failure/Error: is_expected.to have_content new_text
       expected to find text "John Doe" in "Hello, Mr. Server Side Rendering!"
     # ./spec/features/integration_spec.rb:9:in `block (2 levels) in change_text_expect_dom_selector'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.12.1/lib/capybara/session.rb:310:in `within'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.12.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:8:in `block in change_text_expect_dom_selector'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.12.1/lib/capybara/session.rb:310:in `within'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.12.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:6:in `change_text_expect_dom_selector'
     # ./spec/features/integration_spec.rb:72:in `block (2 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec/retry.rb:112:in `block in run'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec/retry.rb:101:in `loop'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec/retry.rb:101:in `run'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.3/lib/rspec/retry.rb:30:in `block (2 levels) in setup'
Finished in 49.89 seconds (files took 5.38 seconds to load)
72 examples, 2 failures
Failed examples:
rspec ./spec/features/integration_spec.rb[1:2:2] # Pages/Index Server Rendering with Options changes name in message according to input
rspec ./spec/features/integration_spec.rb:68 # Turbolinks across pages changes name in message according to input
```

**Comment by cheremukhin23** [comment]
Review status: 14 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, line 62 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGfajE_odoX00NyVAR:-KgJWw2KUAR3ORFaDxv9:batf88g) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/spec/dummy/spec/helpers/react_on_rails_helper_spec.rb#L62)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

You can break the string with `\` at the end, so the line is not crazy long, and remove the lint disable
</blockquote></details>

Deleted rubocop exclusions and formatted string. Since we use squish on string, we can just format the string to be readable

---

*[spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, line 93 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGhHqqnmMvuN2fDelr:-KgJXGpo4sxQlk5HZtLU:b-gmknsa) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/spec/dummy/spec/helpers/react_on_rails_helper_spec.rb#L93)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

try to avoid if possible
</blockquote></details>

Deleted rubocop exclusion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/775)*

**Comment by cheremukhin23** [comment]
Review status: 13 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/react_on_rails/react_component/options.rb, line 9 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGetrZR7fW60cDMPTJ:-KgJnC_vbXQil7atugJr:brlf3dc) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/lib/react_on_rails/react_component/options.rb#L9)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I think we can remove HIDDEN
</blockquote></details>

Removed it

---

*[lib/react_on_rails/react_component/options.rb, line 57 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGf8_3lic2Lf2DVFt7:-KgJnFRB3L9F0Y6jufWt:brlf3dc) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/lib/react_on_rails/react_component/options.rb#L57)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

We can probably remove `style` since we're removing HIDDEN
</blockquote></details>

Removed it

---

*[spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, line 62 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGfajE_odoX00NyVAR:-KgJn4frWgindAhUwnVH:b-e1zj0r) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/spec/dummy/spec/helpers/react_on_rails_helper_spec.rb#L62)):*
<details><summary><i>Previously, cheremukhin23 (Dmitriy Cheremukhin) wrote…</i></summary><blockquote>

Deleted rubocop exclusions and formatted string. Since we use squish on string, we can just format the string to be readable
</blockquote></details>

Changed format to single quotes and \

---

*[spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, line 93 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgGhHqqnmMvuN2fDelr:-KgJm_3x9-MJVQ69psjt:b-e1zj0r) ([raw file](https://github.com/shakacode/react_on_rails/blob/c64db943c7232431dda1378530da1a53c0e8eb0f/spec/dummy/spec/helpers/react_on_rails_helper_spec.rb#L93)):*
<details><summary><i>Previously, cheremukhin23 (Dmitriy Cheremukhin) wrote…</i></summary><blockquote>

Deleted rubocop exclusion
</blockquote></details>

Changed format to single quotes and \

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/775)*

**Comment by cheremukhin23** [comment]
Currently CI fails because the lib can't handle  props: @app_props_server_render.to_json , only  props: @app_props_server_render. It seems it happens because of code in clientStartup.js. 
props = JSON.parse(el.textContent) can't be properly parsed
Working on this issue now

**Comment by cheremukhin23** [comment]
@justin808 All checks pass now

**Comment by justin808** [comment]
One really important comment:

> I think that the conversion of the string JSON props to an object should happen on the Rails side, so that there's no need to double parse on the client side.

> We also need a unit test to confirm that a XSS cannot be introduced if the JSON string is passed, rather than object.

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[node_package/src/clientStartup.js, line 101 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgO5_umVmKhs3x7I_Lo:-KgO5_umVmKhs3x7I_Lp:bjgybf7) ([raw file](https://github.com/shakacode/react_on_rails/blob/09b03e55a6f5b585d19afcc2da9f1d116e8736f2/node_package/src/clientStartup.js#L101)):*
> ```JavaScript
>   const context = findContext();
>   const jsonEl = JSON.parse(el.textContent, (key, value) =>
>     (key === 'props' && typeof value === 'string' ? JSON.parse(value) : value),
> ```

I think that the conversion of the string JSON props to an object should happen on the Rails side, so that there's no need to double parse on the client side.

We also need a unit test to confirm that a XSS cannot be introduced if the JSON string is passed, rather than object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-:-KgO66wegxsr5TsQm3Pz:b6uvqv9)*

**Comment by cheremukhin23** [comment]
Moved this part to the Rails side

---

Review status: 11 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[node_package/src/clientStartup.js, line 101 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-KgO5_umVmKhs3x7I_Lo:-KgQgb3Sy8_VLJGAh8jm:breej1t) ([raw file](https://github.com/shakacode/react_on_rails/blob/09b03e55a6f5b585d19afcc2da9f1d116e8736f2/node_package/src/clientStartup.js#L101)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I think that the conversion of the string JSON props to an object should happen on the Rails side, so that there's no need to double parse on the client side.

We also need a unit test to confirm that a XSS cannot be introduced if the JSON string is passed, rather than object.
</blockquote></details>

Moved it to the rails side to ReactOnRails::ReactComponent::Options. Now we parse all incoming props to hash. Wrote test to ensure we have sanitized react component after passing props as json string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-:-KgQKUs2hWoIp9n7M9SA:bswlcjx)*

**Comment by cheremukhin23** [comment]
@justin808 Should work after build is passed. Any comments on last improvements?

**Comment by justin808** [comment]
:LGTM:

Looks EXCELLENT!

We just need the CHANGELOG.md entry and I'll release this.

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-:-KgQtvNk7KSsaW3TWHH1:by17n2k)*

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/775#-:-KgTPxjIlhMOxSQ87bPE:bnfp4nl)*

**Comment by squadette** [comment]
Hi, sorry for disappearance.

I've upgraded my project to react-on-rails to 6.9.2 and tested, it works perfectly.  Thanks for finishing that!

**Comment by justin808** [comment]
@squadette Please update to 6.9.3!

**Pull request merged**
