### PR TITLE
Typo in rescue for server rendering

### PR DESCRIPTION
**Pull request by railsme**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/963)

### CODE REVIEW

**Comment by justin808** [comment]
@railsme this is GREAT!

Can you please add a CHANGELOG.md entry and I'll merge this.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/963#-:-KxC5uC-KPoANupOsuXR:b-1myeb1)*

**Comment by railsme** [comment]
done :ok_hand: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/963#-:-KxD45xzs7JRKxijCDUg:b-4i36w9)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGELOG.md, line 11 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/963#-KxLIcHZiYxjRMW4dmzg:-KxLIcH_5bDBB0_lCwIu:bpugxlo) ([raw file](https://github.com/shakacode/react_on_rails/blob/712ba0acfc1bccbf09ca766e424e9c28fe1073c5/CHANGELOG.md#L11)):*
> ```Markdown
> *Please add entries here for your pull requests.*
> #### Fixed
> - rubocop disabling comments in rescue statements [PR 963](https://github.com/shakacode/react_on_rails/pull/963) by [railsme](https://github.com/railsme).
> ```

We can make this description a bit more detailed, along the lines of the rubocop comment broke...and this fixed ...

plus, please rebase your change on master

I can't merge right now due to a conflict...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/963)*

**Comment by railsme** [comment]
Should be better now 😃

**Comment by justin808** [comment]
@railsme We're not passing Travis

**Comment by railsme** [comment]
@justin808 #899 broke the build. Should I try to fix it in my PR or wait for fix from the author? 🤔

**Comment by justin808** [comment]
If you can fix it, I’d be thrilled. In this pr is fine.

**Comment by railsme** [comment]
@justin808, I've found that we are using empty strings as default values for not set config options.
I have doubts about checking directory in LocalesToJs because we have similar checks [here](https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/configuration.rb#L23).
I suppose that #899 should be reverted or totally replaced in separate PR because this is not part of the current fix.

**Comment by railsme** [comment]
@justin808 
Please, check and accept #967.
I will rebase current branch on top of master.

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/963#-:-KxZfgm5iXReSSt2mofr:bnfp4nl)*

**Pull request merged**
