### PR TITLE
Upgrade Babel version to 7

### PR DESCRIPTION
**Pull request by tricknotes**
This change has been suggested in https://github.com/shakacode/react_on_rails/pull/1140 .

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1141)

### CODE REVIEW

**Comment by tricknotes** [comment]
Oops, some tests are failed :<
I'll check it later.

**Comment by tricknotes** [comment]
All tests are passed on Travis CI.

@justin808
Could you review this PR?

**Comment by justin808** [comment]
Thank you @tricknotes! Merged. I'll release. I also invited you to https://shakacode.slack.com/

**Comment by tricknotes** [comment]
Woot, great thanks!
Also thanks for your invitation! Now I joined ;)

**Pull request merged**
