### PR TITLE
Update Basic Generator & Linters

### PR DESCRIPTION
**Pull request by Judahmeek**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/624)

### CODE REVIEW

**Comment by Judahmeek** [comment]
Overlooked rspec. Fixing now.

**Comment by justin808** [comment]
:lgtm:

HOWEVER.

Regarding the linter update...

We should make sure the generated code passes the linter. 

We should NOT mix the lint changes for react on rails with the change to the generator.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/generators/react_on_rails/templates/no_redux/base/client/app/bundles/HelloWorld/startup/registration.jsx.tt, line 8 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXV-BsaSMpfbsxQ3_T4:-KXV-BsaSMpfbsxQ3_T5:bdaoub3) ([raw file](https://github.com/shakacode/react_on_rails/blob/f61d2c7660280a4e41df47878dda194878a53d2a/lib/generators/react_on_rails/templates/no_redux/base/client/app/bundles/HelloWorld/startup/registration.jsx.tt#L8)):*
> ```
> ReactOnRails.register({
>   HelloWorld,
> });
> ```

missing return

---

*[node_package/src/serverRenderReactComponent.js, line 29 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXUzyOERRg7P_RnN4Z2:-KXUzyOERRg7P_RnN4Z3:b-ddcj2z) ([raw file](https://github.com/shakacode/react_on_rails/blob/f61d2c7660280a4e41df47878dda194878a53d2a/node_package/src/serverRenderReactComponent.js#L29)):*
> ```JavaScript
>         const redirectPath = redirectLocation.pathname + redirectLocation.search;
>         console.log(`\
> ROUTER REDIRECT: ${name} to dom node with id: ${domNodeId}, redirect to ${redirectPath}`,
> ```

I don't know if these will work. Node stuff is not updated to handle this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-:-KXV-EXL1-79Tv8qdbXL:brn5muy)*

**Comment by Judahmeek** [comment]
Review status: 14 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[node_package/src/serverRenderReactComponent.js, line 29 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXUzyOERRg7P_RnN4Z2:-KXbrOE2eRgAUIv1m0R5:bosgd9y) ([raw file](https://github.com/shakacode/react_on_rails/blob/f61d2c7660280a4e41df47878dda194878a53d2a/node_package/src/serverRenderReactComponent.js#L29)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> I don't know if these will work. Node stuff is not updated to handle this.
</details>
I assumed that Babel could handle this, but I'll change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/624)*

**Comment by justin808** [comment]
:lgtm: 

Please confirm works locally, and travis passes. I might turn on codeship as well. 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-:-KXbvOlu_-B0eoaYgU0E:blp5hvd)*

**Comment by justin808** [comment]
Reviewed 1 of 20 files at r3.
Review status: 13 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 58 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXi4q30PUdSOZH9j0ac:-KXi4q30PUdSOZH9j0ad:b-djieuh) ([raw file](https://github.com/shakacode/react_on_rails/blob/f61d2c7660280a4e41df47878dda194878a53d2a/package.json#L58)):*
> ```JSON
>     "flow": "flow check node_package",
>     "lint": "npm run eslint && npm run flow",
>     "lint:fix": "node_package/scripts/lint-fix",
> ```

why did you remove this?

However, I'd suggest:

1. Make lint only do eslint, so we can do `npm run lint -- --fix`
2. Move the flow part under the check task.

`  "check": "npm run lint && npm run flow && npm run test",`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/624)*

**Comment by justin808** [comment]
@judahmeek I'd like to see us simplify this by taking out some of the options to put in the templates.

We should have the index.html.erb refer to "HelloWorldApp" for redux and "HelloWorld" for the simple no-redux.

Let's see what @robwise says.

---

Reviewed 8 of 20 files at r3, 11 of 12 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/generators/react_on_rails/react_no_redux_generator.rb, line 20 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXi8QEiiFPukDMehgH5:-KXi8QEiiFPukDMehgH6:btzu9ae) ([raw file](https://github.com/shakacode/react_on_rails/blob/8fccc926ef8d3082f12c5812b77c5ccb05c5eea2/lib/generators/react_on_rails/react_no_redux_generator.rb#L20)):*
> ```Ruby
>         }
>         template(source + "/startup/registration.jsx" + ".tt", location + "/startup/registration.jsx", config)
>         template(source + "/components/HelloWorld.jsx" + ".tt", location + "/components/HelloWorldApp.jsx", config)
> ```

I don't think we need the HelloWorldApp if there's no redux.

---

*[lib/generators/react_on_rails/react_with_redux_generator.rb, line 35 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXi8v5B8f9KElAnhqyX:-KXi8v5B8f9KElAnhqyY:b-2k9hnu) ([raw file](https://github.com/shakacode/react_on_rails/blob/8fccc926ef8d3082f12c5812b77c5ccb05c5eea2/lib/generators/react_on_rails/react_with_redux_generator.rb#L35)):*
> ```Ruby
>         %w(/startup/registration.jsx
>            /components/HelloWorld.jsx).each do |file|
>              template(base_path + destination + file + ".tt", destination + file, config)
> ```

normally, we prefer string interpolation rather than addition.

`"#{base_path"}#{destination}"`

---

*[lib/generators/react_on_rails/templates/base/base/client/app/bundles/HelloWorld/components/HelloWorld.jsx.tt, line 3 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXi9PuRTPNUu73s3iUZ:-KXi9PuRTPNUu73s3iU_:bixb0b1) ([raw file](https://github.com/shakacode/react_on_rails/blob/8fccc926ef8d3082f12c5812b77c5ccb05c5eea2/lib/generators/react_on_rails/templates/base/base/client/app/bundles/HelloWorld/components/HelloWorld.jsx.tt#L3)):*
> ```
> import React, { PropTypes } from 'react';
> 
> export default class <%= config[:class_name] %> extends React.Component {
> ```

I've no idea on why we're changing this to use the config[:class_name]

I'd rather see the source file called something like `HelloWorldNoRedux.jsx.tt` and have it copied to the right location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-:-KXi9ttkvXwkqrQ6I0pf:bduqo92)*

**Comment by Judahmeek** [comment]
I see what you're suggesting. I should be able to make those changes pretty quickly.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 58 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXi4q30PUdSOZH9j0ac:-KXmcCDQWTpvI0d9d7Ao:baddql2) ([raw file](https://github.com/shakacode/react_on_rails/blob/f61d2c7660280a4e41df47878dda194878a53d2a/package.json#L58)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why did you remove this?

However, I'd suggest:

1. Make lint only do eslint, so we can do `npm run lint -- --fix`
2. Move the flow part under the check task.

`  "check": "npm run lint && npm run flow && npm run test",`
</blockquote></details>

I removed that script and the lint-fix script file because the file encouraged the manual use of jscs, which has been rolled into eslint now making the script & file seem doubly irrelevant.

I'll add your suggested changes immediately.

---

*[lib/generators/react_on_rails/react_no_redux_generator.rb, line 20 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXi8QEiiFPukDMehgH5:-KXmh60c74-H9q_66IDt:b-bqivcu) ([raw file](https://github.com/shakacode/react_on_rails/blob/8fccc926ef8d3082f12c5812b77c5ccb05c5eea2/lib/generators/react_on_rails/react_no_redux_generator.rb#L20)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I don't think we need the HelloWorldApp if there's no redux.
</blockquote></details>

Will fix.

---

*[lib/generators/react_on_rails/react_with_redux_generator.rb, line 35 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXi8v5B8f9KElAnhqyX:-KXmccl8Pz6UTxLB6MqA:b-khbk9b) ([raw file](https://github.com/shakacode/react_on_rails/blob/8fccc926ef8d3082f12c5812b77c5ccb05c5eea2/lib/generators/react_on_rails/react_with_redux_generator.rb#L35)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

normally, we prefer string interpolation rather than addition.

`"#{base_path"}#{destination}"`
</blockquote></details>

Will fix. In my defense, most of the other code already here was string addition. I'll go ahead and fix all the other string addition code in the files I've been playing in.

---

*[lib/generators/react_on_rails/templates/base/base/client/app/bundles/HelloWorld/components/HelloWorld.jsx.tt, line 3 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-KXi9PuRTPNUu73s3iUZ:-KXmcySKFmXGfIbzEA3S:ba3dcgj) ([raw file](https://github.com/shakacode/react_on_rails/blob/8fccc926ef8d3082f12c5812b77c5ccb05c5eea2/lib/generators/react_on_rails/templates/base/base/client/app/bundles/HelloWorld/components/HelloWorld.jsx.tt#L3)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I've no idea on why we're changing this to use the config[:class_name]

I'd rather see the source file called something like `HelloWorldNoRedux.jsx.tt` and have it copied to the right location.
</blockquote></details>

The reason I made the class name conditional is because the current `index.erb.html` needs a `HelloWorldApp` component, but if `HelloWorldContainer` exists, then it looks for a `HelloWorld` component (and I figured that having a HelloWorldApp component in a HelloWorldApp container might cause issues, semantic and otherwise).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-:-KXmeL1E5n7VG9s89DeM:b-lb1ikc)*

**Comment by justin808** [comment]
:lgtm:

Awesome job @judahmeek! I'll try this out and merge it! 

---

Reviewed 1 of 21 files at r3, 2 of 13 files at r4, 11 of 11 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/624#-:-KXnnXYnqxa0a0Yea-oi:bvclq50)*

**Comment by justin808** [comment]
Thanks @Judahmeek!

**Pull request merged**
