### PR TITLE
Components with hook

### PR DESCRIPTION
**Pull request by sveredyuk**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1205)

### CODE REVIEW

**Comment by tahsin352** [comment]
@justin808 I have implemented component hook by passing props 

```
export default props => <HookExample {...props} />;
```
But the below is not working

```
export default HookExample;
```
I investigated react-rails. they implemented useState() on helper. I think we need to implement a similar function in reactOnRails.js . Please suggest me. Thanks.

**Comment by justin808** [comment]
I'm pretty sure we need to wrap the code using the hook in a wrapper component. I don't know why React on Rails requires that.  Let's do a video call to go over this sometime soon. https://meetings.hubspot.com/justingordon/30-minute-consultation.

**Comment by zx6658** [comment]
Why this pr is not merged..?! i think it is necessary to use hook with react :(

**Comment by sveredyuk** [comment]
@zx6658 Because it not finished yet :(

**Comment by zx6658** [comment]
@sveredyuk oh i see :) i am waiting for your pr is merged 🙏

**Comment by zx6658** [comment]
I have to wrap component with `React.memo` to use with react_component()  react on rails function to deal with this problem..(picture below) if you finish your pr , Will your pr solve the problem?
스크린샷 2019-06-20 오후 4 48 40

**Comment by justin808** [comment]
@Judahmeek @behraaangm Let's try to get an example of a hook in there...

**Comment by Judahmeek** [comment]
@justin808 #1268 resolves this PR.

**Pull request closed without merging**
