### PR TITLE
Applying for the Full Stack Developer

### PR DESCRIPTION
**Pull request by aj-anuragjain**
**1. update react-router.md for react router v4**
   1.1 update client-side router docs
   1.2 update server-side router docs

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1218)

### CODE REVIEW

**Comment by justin808** [comment]
@aj-anuragjain Looks good. Did you test this code by any chance?

**Comment by justin808** [comment]
@Judahmeek can you take a look at this one.

**Comment by Judahmeek** [comment]
@justin808 These updated docs match our code in https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/bundles/comments/startup/ (server & client). We should merge this.

**Comment by justin808** [comment]
Merged! Thank you @aj-anuragjain and @Judahmeek!

**Pull request merged**
