### PR TITLE
Support for rails 3.2+

### PR DESCRIPTION
**Pull request by liorbrauer**
Changed gem's dependency from Rails >= 4.0.0  to >= 3.2

### CODE REVIEW

**Comment by justin808** [comment]
Thanks @liorbrauer for trying this out!

**Comment by flynfish** [comment]
I'm running 3.2 and trying to run the generators it fails because of the hide! method:

```
[WARNING] Could not load generator "generators/react_on_rails/base_generator". Error: undefined method `hide!' for ReactOnRails::Generators::BaseGenerator:Class
```

**Comment by justin808** [comment]
@flynfish Any chance that you can submit a PR on this one? @liorbrauer Let me know if you have any thoughts on this one. CC: @rstudner.

**Comment by justin808** [comment]
@flynfish a work around would be to copy/paste from these examples: https://github.com/shakacode/react_on_rails-generator-results

**Comment by flynfish** [comment]
@justin808 I was thinking just check if hide! method exists and if it doesn't don't call it. If that's acceptable I will submit a PR

**Comment by justin808** [comment]
@flynfish that sounds OK.

**Comment by liorbrauer** [comment]
@justin808 haven't used the latest version yet with Rails 3.2+, I will try it when I have a moment and see.

**Comment by flynfish** [comment]
PR #165 submitted

**Pull request merged**
