### PR TITLE
v9 Migration Doc

### PR DESCRIPTION
**Pull request by Judahmeek**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/957)

### CODE REVIEW

**Comment by justin808** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[docs/basics/upgrading-react-on-rails.md, line 9 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-KwdcHbhDFSdtxc8UfF8:-KwdcHbhDFSdtxc8UfF9:bfkzwr0) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L9)):*
> ```Markdown
> * If you have `react_component` returning hashes, then switch to `react_component_hash` instead
> 
> ## Upgrading to version 9
> ```

from v8?

---

*[docs/basics/upgrading-react-on-rails.md, line 20 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-KwdcQmC8iu0cRz6sar-:-KwdcQmC8iu0cRz6sar0:b-dvq4on) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L20)):*
I don't follow this one.

webpacker just makes it so you don't have to do your own webpack configuration


>  This enables your webpack bundles to bypass the Rails asset pipeline and it's extra minification

that's moving beyond v7 of RoR

---

*[docs/basics/upgrading-react-on-rails.md, line 23 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-KwdcLqRJghnuNcEjwZz:-KwdcLqRJghnuNcEjw_-:b-ubf3no) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L23)):*
> ```Markdown
> 
> #### From version 8
> See [our changelog for instructions](https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md#90-from-8x-upgrade-instructions)
> ```

let's include this here

---

*[docs/basics/upgrading-react-on-rails.md, line 32 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kwdch89tcYolmYCChoY:-Kwdch89tcYolmYCChoZ:b-lrotjk) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L32)):*
> ```Markdown
> *   `Gemfile`: bump `react_on_rails` and add `webpacker`
> *   layout views: anything bundled by webpack will need to be requested by a `javascript_pack_tag` or `stylesheet_pack_tag`
> *   `config/initializers/assets.rb`: Delete it. You don't need it anymore.
> ```

maybe revert back to default for assets.rb? I'm not sure about deleting it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/957)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/957)*

**Comment by Judahmeek** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[docs/basics/upgrading-react-on-rails.md, line 20 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-KwdcQmC8iu0cRz6sar-:-KwrSnUddmXDGZzSCFxc:b-aqxebs) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L20)):*
Webpacker does make it so that you don't have to do your own webpack configuration, but clients with legacy projects are likely to want to maintain control of their webpack configuration. Therefore, the only other reason a client would want to integrate webpacker is to bypass the double minification.

> that's moving beyond v7 of RoR
Anything involving webpacker is moving beyond RoR v7. What's your point?

---

*[docs/basics/upgrading-react-on-rails.md, line 23 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-KwdcLqRJghnuNcEjwZz:-KwrTIAspnkL0lWdIO0l:bhy9ot6) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L23)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

let's include this here
</blockquote></details>

Will do.

---

*[docs/basics/upgrading-react-on-rails.md, line 32 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kwdch89tcYolmYCChoY:-KwrTV_EA4rraAjWjN05:b1iclwg) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L32)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

maybe revert back to default for assets.rb? I'm not sure about deleting it.
</blockquote></details>

Well, if we're going to tell people to revert it, then we'll have to identify exactly what changes RoR made to it. Shall we assume the client installed RoR v7?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/957)*

**Comment by justin808** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/basics/upgrading-react-on-rails.md, line 20 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-KwdcQmC8iu0cRz6sar-:-Kx0Ft--xqjW8PocybMj:b-r62b0f) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L20)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

Webpacker does make it so that you don't have to do your own webpack configuration, but clients with legacy projects are likely to want to maintain control of their webpack configuration. Therefore, the only other reason a client would want to integrate webpacker is to bypass the double minification.

> that's moving beyond v7 of RoR
Anything involving webpacker is moving beyond RoR v7. What's your point?
</blockquote></details>

This makes no sense at all to me.

Webpacker provides 2 things:

1. View helpers that support bypassing the asset pipeline to enable things like avoiding double minification and proper source maps. This is 100% a best practice.
2. A default Webpack config so that you only need to do minimal modifications and customizations. However, if you're doing server rendering, you may not want to give up control. Since Webpacker's default webpack config is changing often, we can give you definitive advice on this one. In general, if you're happy with doing your own Webpack configuration, then stick to that. Most bigger projects will prefer having more control.

---

*[docs/basics/upgrading-react-on-rails.md, line 11 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kx0FmBQW9wOBOyrg4FL:-Kx0FmBQW9wOBOyrg4FM:bbxa04q) ([raw file](https://github.com/shakacode/react_on_rails/blob/fdeb447a9efb468b005821e3868e7ca7c7ddf30e/docs/basics/upgrading-react-on-rails.md#L11)):*
> ```Markdown
> ## Upgrading to version 9
> 
> ### With no interest of integrating webpacker
> ```

Need a few sentences of pros and cons of either way.

---

*[docs/basics/upgrading-react-on-rails.md, line 16 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kx0FRVEsqvoY_NJ_kiX:-Kx0FRVEsqvoY_NJ_kiY:b-7zh2ej) ([raw file](https://github.com/shakacode/react_on_rails/blob/fdeb447a9efb468b005821e3868e7ca7c7ddf30e/docs/basics/upgrading-react-on-rails.md#L16)):*
> * In `/config/initializers/react_on_rails.rb`, rename:
>     *   config.npm_build_test_command ==> config.build_test_command
>     *   config.npm_build_production_command ==> config.build_production_command
> * Also create `config.node_modules_location` and set it to `"client"`


```
* In `/config/initializers/react_on_rails.rb`:
    *  Rename `config.npm_build_test_command` ==> `config.build_test_command`
    *  Rename `config.npm_build_production_command` ==> `config.build_production_command`
    *  Add `config.node_modules_location = "client"`
```

---

*[docs/basics/upgrading-react-on-rails.md, line 23 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kx0GZXujRhA6OlT7XA1:-Kx0GZXujRhA6OlT7XA2:bt8969f) ([raw file](https://github.com/shakacode/react_on_rails/blob/fdeb447a9efb468b005821e3868e7ca7c7ddf30e/docs/basics/upgrading-react-on-rails.md#L23)):*
> ```Markdown
> Reason for doing this: This enables your webpack bundles to bypass the Rails asset pipeline and it's extra minification, enabling you to use source-maps in production, while still maintaining total control over everything in the client directory
> 
> #### From version 8
> ```

Most people are upgrading from 7 or earlier to 9 or later, so this is a bit confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/957)*

**Comment by justin808** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/957)*

**Comment by justin808** [comment]
suggestions provided

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/basics/upgrading-react-on-rails.md, line 32 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kwdch89tcYolmYCChoY:-Kx0GnIQ2MVS0zPU9sZS:b-9hu6y0) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L32)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

Well, if we're going to tell people to revert it, then we'll have to identify exactly what changes RoR made to it. Shall we assume the client installed RoR v7?
</blockquote></details>

No idea on this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-:-Kx0Gp6HGX1BymfS99q8:bjfx3sp)*

**Comment by Judahmeek** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/basics/upgrading-react-on-rails.md, line 20 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-KwdcQmC8iu0cRz6sar-:-KxCEoCVOjKUaMjdORJT:bzecz2k) ([raw file](https://github.com/shakacode/react_on_rails/blob/220aa3be127b6ee038e481c5a17773201afbff74/docs/basics/upgrading-react-on-rails.md#L20)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

This makes no sense at all to me.

Webpacker provides 2 things:

1. View helpers that support bypassing the asset pipeline to enable things like avoiding double minification and proper source maps. This is 100% a best practice.
2. A default Webpack config so that you only need to do minimal modifications and customizations. However, if you're doing server rendering, you may not want to give up control. Since Webpacker's default webpack config is changing often, we can give you definitive advice on this one. In general, if you're happy with doing your own Webpack configuration, then stick to that. Most bigger projects will prefer having more control.



</blockquote></details>

Stolen

---

*[docs/basics/upgrading-react-on-rails.md, line 11 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kx0FmBQW9wOBOyrg4FL:-KxCGa2eMVhV8LWIy_UV:b-e2qsej) ([raw file](https://github.com/shakacode/react_on_rails/blob/fdeb447a9efb468b005821e3868e7ca7c7ddf30e/docs/basics/upgrading-react-on-rails.md#L11)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Need a few sentences of pros and cons of either way.
</blockquote></details>

Used your own comments with minor modifications

---

*[docs/basics/upgrading-react-on-rails.md, line 16 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kx0FRVEsqvoY_NJ_kiX:-KxCH4e39muRbyseU1qU:bb6un1j) ([raw file](https://github.com/shakacode/react_on_rails/blob/fdeb447a9efb468b005821e3868e7ca7c7ddf30e/docs/basics/upgrading-react-on-rails.md#L16)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

> * In `/config/initializers/react_on_rails.rb`, rename:
>     *   config.npm_build_test_command ==> config.build_test_command
>     *   config.npm_build_production_command ==> config.build_production_command
> * Also create `config.node_modules_location` and set it to `"client"`


```
* In `/config/initializers/react_on_rails.rb`:
    *  Rename `config.npm_build_test_command` ==> `config.build_test_command`
    *  Rename `config.npm_build_production_command` ==> `config.build_production_command`
    *  Add `config.node_modules_location = "client"`
```
</blockquote></details>

Done

---

*[docs/basics/upgrading-react-on-rails.md, line 23 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-Kx0GZXujRhA6OlT7XA1:-KxCErYMRWK88vdtNPL1:b-a8m7r9) ([raw file](https://github.com/shakacode/react_on_rails/blob/fdeb447a9efb468b005821e3868e7ca7c7ddf30e/docs/basics/upgrading-react-on-rails.md#L23)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Most people are upgrading from 7 or earlier to 9 or later, so this is a bit confusing.
</blockquote></details>

I moved this section to the end

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/957)*

**Comment by justin808** [comment]
@judahmeek Any final questions for me? Ready to merge?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/957#-:-KxCfSIkTc7Jc6YAXDr4:b-sp3gof)*

**Comment by Judahmeek** [comment]
@justin808 Yes, ready to merge.

**Pull request merged**
