### PR TITLE
Delete the -N Node option from the Generator.

### PR DESCRIPTION
**Pull request by EEtancelin**
Delete the  -N and --node option from the generator the associate test and the corresponding section in Usage.
Why : Issue #874

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/898)

### CODE REVIEW

**Comment by EEtancelin** [comment]
Why coveralls is still pending ?

**Comment by justin808** [comment]
@EEtancelin Close!

* Rebase on top of master
* Add an entry to CHANGELOG.md
* Remove this directory: https://github.com/shakacode/react_on_rails/tree/master/lib/generators/react_on_rails/templates/node/base/client/node

**Comment by justin808** [comment]
@EEtancelin Should this one still be merged? There's merge conflicts.

**Comment by justin808** [comment]
Was previously merged.

**Pull request closed without merging**
