### PR TITLE
Alternative turbolinks fix

### PR DESCRIPTION
**Pull request by Judahmeek**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1425)

### CODE REVIEW

**Comment by justin808** [comment]
@Judahmeek what should we do with this?

**Comment by justin808** [comment]
@Judahmeek should we close this?

**Comment by justin808** [comment]
@Judahmeek @templeman15, should we close this one?

Is there any doc PR needed?

**Comment by justin808** [comment]
@templeman15, Thanks! 

Can you link to the issue that you reference?

What is RTK?

**Comment by templeman15** [comment]
> Can you link to the issue that you reference?

This is the general idea: https://github.com/shakacode/react_on_rails/issues/1139

It was why we contacted you initially. Two API requests would happen when visiting cached pages when only one was supposed to happen. It would also make the loading state on the component come in twice and data appear, disappear, then re appear with the two API requests.
 
> What is RTK?

[Redux Tool Kit - Query](https://redux-toolkit.js.org/rtk-query/overview)

**Comment by justin808** [comment]
@templeman15 thanks for sharing your research.

**Pull request closed without merging**
