### PR TITLE
React refresh webpack plugin

### PR DESCRIPTION
**Pull request by behraaangm**
added react refresh, removed hmr from client, upgraded webpacker to v5

This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1265)

### CODE REVIEW

**Comment by behraaangm** [comment]
___
*[spec/dummy/package.json, line 10 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1265#-M4fE7Po6NmukbAvEdeh:-M4iiYfs6LrXY-iIbezt:bcai57y) ([raw file](https://github.com/shakacode/react_on_rails/blob/1d11c45f7635ffa4688a95af0755d36c1d22c676/spec/dummy/package.json#L10)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Would it make sense to update the babel versions here? Why or why not?
</blockquote></details>

This is updated due to rails/webpacker v5 update instructions here:
https://github.com/rails/webpacker#upgrading

**Comment by behraaangm** [comment]
___
*[spec/dummy/bin/webpack, line 10 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1265#-M4fDWTi6a5rv76ykNl-:-M4iizCz91b73wJL6da4:bk0um51) ([raw file](https://github.com/shakacode/react_on_rails/blob/ca07f5284ccc555d6870239ad91da26ad521f732/spec/dummy/bin/webpack#L10)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

@behraaangm how did this cleanup come about about? Did you compare to the defaults for rails/webpacker v5?
</blockquote></details>

This is also updated due to rails/webpacker v5 update instructions here:
https://github.com/rails/webpacker#upgrading

**Comment by justin808** [comment]
We need to remove anything related to the old hot reloading, like:

https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/Procfile.hot#L6
https://github.com/shakacode/react_on_rails/search?q=react-hot-loader&unscoped_q=react-hot-loader

**Comment by justin808** [comment]
See #1292

**Comment by justin808** [comment]
See #1293

**Pull request closed without merging**
