### PR TITLE
Better documentation for test helpers, check config messages

### PR DESCRIPTION
**Pull request by justin808**
* Throw if configuration.generated_assets_dir specified, and using
  webpacker, and if that doesn't match the public_output_path.
* Otherwise, warn if generated_assets_dir is specified
* Fix the setup for tests for spec/dummy so they automatically rebuild
  by correctly setting the source_path in the webpacker.yml
* Updated documentation for the testing setup.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1072)

### CODE REVIEW

**Comment by Judahmeek** [comment]
Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[lib/react_on_rails/configuration.rb, line 40 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LAw2R0V0T7P1IF-HpLM:-LAw2R0V0T7P1IF-HpLN:b-ru6dq) ([raw file](https://github.com/shakacode/react_on_rails/blob/44a8a119c5504a85b1e22fc2d6d174872d5d3c2a/lib/react_on_rails/configuration.rb#L40)):*
> ```Ruby
>       msg = <<-MSG.strip_heredoc
>         Error configuring /config/initializers/react_on_rails.rb: You are using webpacker
>         and you specified value for generated_assets_dir = #{@configuration.generated_assets_dir}
> ```

Should be `...and your specified value...`

---


*Comments from [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1072)*

**Comment by mapreal19** [comment]
:lgtm: some suggestions but feel free to merge and address this later if agreeing with suggestions

---

Reviewed 10 of 15 files at r1, 12 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[lib/react_on_rails/configuration.rb, line 25 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0KwnZ0YARoQ1CFgbr:-LB0KwnZ0YARoQ1CFgbs:b9fijh1) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/configuration.rb#L25)):*
> ```Ruby
>   end
> 
>   def self.error_if_using_webpacker_and_generated_assets_dir_not_match_public_output_path
> ```

is there a test for this new method?

---

*[lib/react_on_rails/utils.rb, line 9 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0L8dlBN_CoraEjMyi:-LB0L8dlBN_CoraEjMyj:b7bgtc2) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/utils.rb#L9)):*
> ```Ruby
> require "active_support/core_ext/string"
> 
> # Naming: goal is that path is a full_path and dir means relative to the rails root.
> ```

what about using `full_path` and `relative_dir` or anything better you can think of. The goal is to have self documenting code. If not it would be hard for a reader to find this comment since we could be using this naming pattern in other files

---

*[lib/react_on_rails/webpacker_utils.rb, line 7 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0MnBP0s0LoFH8GVz9:-LB0MnBP0s0LoFH8GVzA:b-q6wmrw) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/webpacker_utils.rb#L7)):*
> ```Ruby
>     end
> 
>     # Full absolute path of webpacker output files.
> ```

instead of writing comments here what about having a spec with this info? In the spec we could see if returning a full path, pathname, etc.  Easier to see future errors when upgrading webpacker too. 

---

*[lib/react_on_rails/webpacker_utils.rb, line 14 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0MZcf0nxfGfOLFMqt:-LB0MZcf0nxfGfOLFMqu:b-14qk70) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/webpacker_utils.rb#L14)):*
> ```Ruby
> 
>     def self.bundle_js_file_path_from_webpacker(bundle_name)
>       # Note Webpacker 3.4.3 manifest lookup is inside of the public_output_path
> ```

remove comment after upgrading 3.4.3?

---


*Comments from [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-:-LB0OF46CSv0J-jfeXFc:blhiprr)*

**Comment by justin808** [comment]
added some tests

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/react_on_rails/configuration.rb, line 25 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0KwnZ0YARoQ1CFgbr:-LB4tEXtCmyKrfY9ps_m:bsik5gx) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/configuration.rb#L25)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary><blockquote>

is there a test for this new method?
</blockquote></details>

Yes, added one!

---

*[lib/react_on_rails/utils.rb, line 9 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0L8dlBN_CoraEjMyi:-LB4tK_Z0iA4iKlvrpAP:bb6k12l) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/utils.rb#L9)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary><blockquote>

what about using `full_path` and `relative_dir` or anything better you can think of. The goal is to have self documenting code. If not it would be hard for a reader to find this comment since we could be using this naming pattern in other files
</blockquote></details>

good idea! but didn't change much, but one method name.

---

*[lib/react_on_rails/webpacker_utils.rb, line 7 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0MnBP0s0LoFH8GVz9:-LB50raRCjRGW7ucKYjM:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/webpacker_utils.rb#L7)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary><blockquote>

instead of writing comments here what about having a spec with this info? In the spec we could see if returning a full path, pathname, etc.  Easier to see future errors when upgrading webpacker too. 
</blockquote></details>

Done.

---

*[lib/react_on_rails/webpacker_utils.rb, line 14 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0MZcf0nxfGfOLFMqt:-LB50r7mE6vM7bXLJPuw:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/webpacker_utils.rb#L14)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary><blockquote>

remove comment after upgrading 3.4.3?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-:-LB50tNVA4dAzI_ddc_y:brujj8a)*

**Comment by mapreal19** [comment]
Reviewed 13 of 13 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[lib/react_on_rails/utils.rb, line 9 at r3](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-LB0L8dlBN_CoraEjMyi:-LB5U2UE-ihweSwUYXOh:b-8fx2u7) ([raw file](https://github.com/shakacode/react_on_rails/blob/dc5657a1c95ccef0386321f9113702d16c2cae2d/lib/react_on_rails/utils.rb#L9)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

good idea! but didn't change much, but one method name.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1072)*

**Comment by mapreal19** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1072#-:-LB5UM_fBg7OqoAYNBq9:b-uwkowd)*

**Pull request merged**
