### PR TITLE
Document optional configuration for bundle caching with ReactOnRailsPro

### PR DESCRIPTION
**Pull request by Judahmeek**
See https://github.com/shakacode/react_on_rails_pro/pull/179

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1370)

### CODE REVIEW

**Review by justin808 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1370)* status: all files reviewed, 1 unresolved discussion (waiting on @Judahmeek)

___
*[docs/basics/configuration.md, line 80 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1370#-MZl53CKC-L9q7KF_jcg:-MZl53CKC-L9q7KF_jch:b-af1e0) ([raw file](https://github.com/shakacode/react_on_rails/blob/048697a5e5e6f2ba8b9728637e9a9340e742c81f/docs/basics/configuration.md#L80)):*
> ```Markdown
>   # See bottom for an example of the BuildProductionCommand module.
>   # config.build_production_command = BuildProductionCommand
>   # If you wish to utilize ReactOnRailsPro production bundle caching logic, then use
> ```

...React on Rails Pro's production...

**Review by justin808 — COMMENTED** [review]
LGTM

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1370#-:-M_--jAE0kBfpjSQFw3o:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @Judahmeek)

**Comment by Judahmeek** [comment]
Now we've got CircleCI, Github Actions, & Travis? :joy: Do you want me to fix the Travis issues? Possibly travis configuration since the other two CI are passing.

**Comment by justin808** [comment]
LGTM.

Travis seems to be failing on linting.

**Review by justin808 — COMMENTED** [review]
LGTM

> Reviewed 3 of 5 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1370#-:-M_Pc68398mVm1F3RjKp:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @Judahmeek)

**Pull request merged**
