### PR TITLE
Fix rubocop

### PR DESCRIPTION
**Pull request by reconstructions**
* Minimum Ruby version advanced to 2.1.0
* Docker configuration files checked in

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1015)

### CODE REVIEW

**Comment by justin808** [comment]
@reconstructions Please rebase on top of master.

**Comment by reconstructions** [comment]
Will do, @justin808, should I have done that to begin with, or did I misinterpret the [contributor instructions](https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md#summary) to "squash all commits down to one with a nice commit message ONLY once final review is given"?

**Comment by justin808** [comment]
@reconstructions best to squash before you rebase to avoid multiple merge conflicts.

I can merge multiple commits from github now, so not critical once you're sync'd with master.

**Comment by reconstructions** [comment]
@justin808 thanks for the tip.  I usually use `rebase -i interactive` to squash to a single commit, always ready to learn better ways.  I need to keep an eye out to make sure my fork is up-to-date before pushing PR's.

**Pull request closed without merging**
