### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by evgenTraytyak**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/560)

### CODE REVIEW

**Comment by justin808** [comment]
@evgenTraytyak Please update to latest so I can merge.

**Comment by justin808** [comment]
@evgenTraytyak please reapply your change (rebase on top of origin/master):
```
git checkout patch-1
git fetch
git rebase origin/master
git push -f
```

**Comment by justin808** [comment]
@evgenTraytyak can you reapply your change? I can't merge as is

**Comment by evgenTraytyak** [comment]
@justin808 :shipit:

**Comment by justin808** [comment]
Thanks @evgenTraytyak

**Pull request merged**
