### PR TITLE
Add EnsureAssetsCompiled feature

### PR DESCRIPTION
**Pull request by robwise**
[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/222)

### CODE REVIEW

**Comment by justin808** [comment]
Looking good!

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/additional_reading/rspec_configuration.md, line 2 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8psrMwNpOXSuYv0rqB:-K8psrMwNpOXSuYv0rqC:-1024766173) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L2)):*
If  you did use stale Webpack assets, you will get invalid test results as your tests do not use the very latest JavaScript code.

---

*[docs/additional_reading/rspec_configuration.md, line 4 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8pt7YOZ1EIAF_brJnC:-K8pt7YOZ1EIAF_brJnD:-1868572408) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L4)):*
@samnang Please review. I'm pretty sure we need to pass config.

---

*[docs/additional_reading/rspec_configuration.md, line 6 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8ptDZZ573jVOaHd_CR:-K8ptDZZ573jVOaHd_CS:1691874430) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L6)):*
and only if you do not have the `webpack -w` processes that would build the generated  files.

---

*[docs/additional_reading/rspec_configuration.md, line 8 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8ptRc3_oBvNWQBPOM6:-K8ptRc3_oBvNWQBPOM7:-1990258417) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L8)):*
per my prior statement. I would not mention TDD workflow.

    If you do not want to be slowed down by re-compiling webpack assets from scratch every test run, you can call ...

---

*[README.md, line 379 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8ptjxsC4U22tXxkmKF:-K8ptjxsC4U22tXxkmKG:262468467) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/README.md#L379)):*
:thumbsup: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-:-K8ptw-at-BPJUxdGfl9:1637267586)*

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/additional_reading/rspec_configuration.md, line 2 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8psrMwNpOXSuYv0rqB:-K8q1SiLS6G6606wmS8S:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L2)):*
Done.

---

*[docs/additional_reading/rspec_configuration.md, line 6 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8ptDZZ573jVOaHd_CR:-K8q1Y_xPUHi6TpQoasu:-772052568) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L6)):*
see below I address that next

---

*[docs/additional_reading/rspec_configuration.md, line 8 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8ptRc3_oBvNWQBPOM6:-K8q1tHaw4MjIkcFmviR:1641549245) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L8)):*
what prior statement?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/222)*

**Comment by justin808** [comment]
:lgtm_strong: :tada: :clap: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-:-K8quPcTj1TbUxejRSS_:1829659553)*

**Comment by samnang** [comment]
*[docs/additional_reading/rspec_configuration.md, line 4 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8pt7YOZ1EIAF_brJnC:-K8wB_uzj6KQsrSfd_5-:-2121742451) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L4)):*
@justin808 @robwise Great stuff. I have few comments on this:

1) instead of doing `before(:example)`, we should use `before(:suite)`.
2) Instead letting users of our gem to know about the method and we need to expose that, we just have `lib/react_on_rails/rspec` file helper, so the user just require that file `react_on_rails/rspec` in their rails helper to have this integration helper.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/222)*

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/additional_reading/rspec_configuration.md, line 4 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/222#-K8pt7YOZ1EIAF_brJnC:-K8zGJhw6wCmcjYz1PCY:-587460760) ([raw file](https://github.com/shakacode/react_on_rails/blob/e04314e1ba1f33c43505696edcb1ffa648417ad7/docs/additional_reading/rspec_configuration.md#L4)):*
@samnang 

1) If I do before suite, the thing will compile webpack bundles even if the user is just doing a quick unit test that has nothing to do with webpack.
2) We need access to the RSpec config, so we have to have the user pass it as a variable. Also, there was an issue where if we have auto-executing code on require, then this runs twice (once on requiring of the gem by Rails, once on requiring in the rails helper)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/222)*

**Pull request merged**
