### PR TITLE
Improving the Readme

### PR DESCRIPTION
**Pull request by Judahmeek**
An attempt to improve the clarity and focus of the readme. Feel free to cherry-pick through it.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/524)

### CODE REVIEW

**Comment by justin808** [comment]
@Judahmeek Great suggestions! I'll work on getting this merged in shortly. I'll be taking 90% of this!

**Comment by justin808** [comment]
Really awesome work @judahmeek! I left you a few comments. 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 3 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPddi4W3L9jzI_UTrWB:-KPddi4W3L9jzI_UTrWC:b-8z9jw7) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L3)):*
> ```Markdown
> [Build Status](https://travis-ci.org/shakacode/react_on_rails)  [Dependency Status](https://gemnasium.com/shakacode/react_on_rails) [Gem Version](https://badge.fury.io/rb/react_on_rails) [npm version](https://badge.fury.io/js/react-on-rails) [Code Climate](https://codeclimate.com/github/shakacode/react_on_rails) [Coverage Status](https://coveralls.io/github/shakacode/react_on_rails?branch=master)
> 
> Aloha from Justin Gordon and the [ShakaCode](http://www.shakacode.com) Team! We're actively looking for new projects. If you like **React on Rails**, please consider contacting me if we could potentially help you in any way. Besides consulting on bigger projects, [ShakaCode](http://www.shakacode.com) is doing Skype plus Slack/Github based coaching for React on Rails. [Click here](http://www.shakacode.com/work/index.html) for more information.
> ```

contacting me ==> link for email `[justin@shakacode.com](mailto:justin@shakacode.com)`

---

*[README.md, line 11 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdgyU88MqAOTUpLKYw:-KPdgyU88MqAOTUpLKYx:b-ss67jc) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L11)):*
> ```Markdown
> Your support keeps this project going.
> 
> (Want to become a contributor? [Contact us](mailto:contact@shakacode.com) for an Slack team invite! Also, see ["easy" issues](https://github.com/shakacode/react_on_rails/labels/easy) and [issues for the full tutorial](https://github.com/shakacode/react-webpack-rails-tutorial/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy).)
> ```

why in parens?

---

*[README.md, line 14 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdeM0C8pH5ut9Z_gaq:-KPdeM0C8pH5ut9Z_gar:b-ghln0w) ([raw file](https://github.com/shakacode/react_on_rails/blob/c81fbc2949a9bb48ae705138dc79809e0c6194e4/README.md#L14)):*
> ```Markdown
> * The generator of React on Rails does not setup CSS modules and hot reloading via the Rails server as is demonstrated in the [shakacode/react-webpack-rails-tutorial](https://github.com/shakacode/react-webpack-rails-tutorial/). *We do support this, but we don't generate the code.* If you did generate a fresh app from react_on_rails and wanted to move to CSS Modules, then see [PR 175: Babel 6 / CSS Modules / Rails hot reloading](https://github.com/shakacode/react-webpack-rails-tutorial/pull/175). Note, while there are probably fixes after this PR was accepted, this has the majority of the changes. See [the tutorial](https://github.com/shakacode/react-webpack-rails-tutorial/#news) for more information. For more information on how to setup hot reloading in a Rails app, see [Hot Reloading of Assets For Rails Development](docs/additional-reading/hot-reloading-rails-development.md).
> * See [Projects](PROJECTS.md) using and [KUDOS](./KUDOS.md) for React on Rails. Please submit yours! Please edit either page or [email us](mailto:contact@shakacode.com) and we'll add your info. We also **love stars** as it helps us attract new users and contributors.
> * On Twitter, follow [@railsonmaui](https://twitter.com/railsonmaui) and [@shakacode](https://twitter.com/shakacode) for updates on releases. We've got a forum category dedicated to [react_on_rails](http://forum.shakacode.com/c/rails/reactonrails).
> ```

Where did you put the above?

The CSS modules stuff should get addressed somewhere, and I agree that it shouldn't be at the top.

The other links should be very visible.

---

*[README.md, line 32 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdeXf70ocDPdFrspgq:-KPdeXf70ocDPdFrspgr:b-1k04dk) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L32)):*
> ```Markdown
>     - [Installation Summary](#installation-summary)
>     - [Initializer Configuration: config/initializers/react_on_rails.rb](#initializer-configuration)
> 	  - [Including your React Component in your Rails Views](#including-your-react-component-in-your-rails-views)
> ```

no tabs

---

*[README.md, line 71 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdevdK4aIwUj1UNjk9:-KPdevdK4aIwUj1UNjkA:bu754ox) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L71)):*
> ```Markdown
> We're definitely not doing that. With react_on_rails, webpack is mainly generating a nice JavaScript file for inclusion into `application.js`. We're going to KISS. And that's all relative given how much there is to get right in an enterprise class web application.
> 
> For a complete example, see our live demo at [www.reactrails.com](http://www.reactrails.com). ([Source Code](https://github.com/shakacode/react-webpack-rails-tutorial))
> ```

This should be at the top, IMHO, per prior comment.

---

*[README.md, line 451 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdfGZYibDESUGw-Sy4:-KPdfGZYibDESUGw-Sy5:b-yzm78v) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L451)):*
> ```Markdown
> Node.js can be used as the backend for server-side rendering instead of [execJS](https://github.com/rails/execjs). Before you try this, consider the tradeoff of extra complexity with your deployments versus *potential* performance gains. We've found that using ExecJS with [mini_racer](https://github.com/discourse/mini_racer) to be "fast enough" so far. That being said, we've heard of other large websites using Node.js for better server rendering performance. See [Node.js for Server Rendering](docs/additional-reading/node-server-rendering.md) for more information.
> 
> ## Additional Documentation
> ```

I really like the way you did this!

---

*[README.md, line 531 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdfpa43v3krKDNOOgR:-KPdfpa43v3krKDNOOgS:boo10rz) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L531)):*
> ```Markdown
> 
> # FINAL NOTES
> * See [Projects](PROJECTS.md) using and [KUDOS](./KUDOS.md) for React on Rails. Please submit yours! Please edit either page or [email us](mailto:contact@shakacode.com) and we'll add your info. We also **love stars** as it helps us attract new users and contributors.
> ```

While I do realize that  the part on the removed is a little repetitive (the very top), and personal, it's intentional. We fund this and our other open source projects through doing consulting based on it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-:-KPdgVrczxqD8r6zBtoC:b-o6m1rj)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[README.md, line 3 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdh6DKAeo1ODqbuyEP:-KPdh6DKAeo1ODqbuyEQ:b-e3c65y) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L3)):*
> ```Markdown
> [Build Status](https://travis-ci.org/shakacode/react_on_rails)  [Dependency Status](https://gemnasium.com/shakacode/react_on_rails) [Gem Version](https://badge.fury.io/rb/react_on_rails) [npm version](https://badge.fury.io/js/react-on-rails) [Code Climate](https://codeclimate.com/github/shakacode/react_on_rails) [Coverage Status](https://coveralls.io/github/shakacode/react_on_rails?branch=master)
> 
> Aloha from Justin Gordon and the [ShakaCode](http://www.shakacode.com) Team! We're actively looking for new projects. If you like **React on Rails**, please consider contacting me if we could potentially help you in any way. Besides consulting on bigger projects, [ShakaCode](http://www.shakacode.com) is doing Skype plus Slack/Github based coaching for React on Rails. [Click here](http://www.shakacode.com/work/index.html) for more information.
> ```

`Aloha from Justin Gordon ([bio](http://www.railsonmaui.com/about))`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/524)*

**Comment by Judahmeek** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[README.md, line 3 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPddi4W3L9jzI_UTrWB:-KPf9dPwyHM7rreCEz1P:bhy9ot6) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L3)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> contacting me ==> link for email `[justin@shakacode.com](mailto:justin@shakacode.com)`
</details>
Will do.

---

*[README.md, line 3 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdh6DKAeo1ODqbuyEP:-KPf9fbdhuSrmQEnqufI:bxdh81z) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L3)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> `Aloha from Justin Gordon ([bio](http://www.railsonmaui.com/about))`
</details>
On it.

---

*[README.md, line 11 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdgyU88MqAOTUpLKYw:-KPf7I1eWX1FBkb8QJJ4:bck0fap) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L11)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> why in parens?
</details>
From what I've read, the last sentence of a paragraph is the most memorable. I hoped that by making the "Want to a contributor?" section a Post Scriptum, it would make the "Your support keeps this project going." sentence more sticky.

I assumed that contributing tips have enough significance of their own to those who desire to contribute (like myself) that being placed in parenstheses wouldn't lower conversion of non-contributors to contributors.

---

*[README.md, line 14 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdeM0C8pH5ut9Z_gaq:-KPf4z_xmcFxhOsa417s:b-88f44) ([raw file](https://github.com/shakacode/react_on_rails/blob/c81fbc2949a9bb48ae705138dc79809e0c6194e4/README.md#L14)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Where did you put the above?
> 
> The CSS modules stuff should get addressed somewhere, and I agree that it shouldn't be at the top.
> 
> The other links should be very visible.
> 
> 
> 
</details>
I scattered the notes throughout the readme according to their relevance. You've found most of them according to your other comments.

I actually removed the CSS modules note **from this readme** because this issue is addressed by a section in the tutorial repository's readme and viewing that tutorial seemed to be the only way a developer could gain the expectation that the generators would generate the CSS module and hot reloading functionality.

I'd be happy to re-add the section if you believe it should be in both readmes (Btw, I've submitted a PR for the tutorial repo's readme as well.)

---

*[README.md, line 32 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdeXf70ocDPdFrspgq:-KPf49pHX_kolKtgQEyz:b-bqivcu) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L32)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> no tabs
</details>
Will fix.

---

*[README.md, line 71 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdevdK4aIwUj1UNjk9:-KPf46fTY3QBAvZQcfSH:b13pu5d) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L71)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> This should be at the top, IMHO, per prior comment.
</details>
Can do!

---

*[README.md, line 451 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdfGZYibDESUGw-Sy4:-KPf9sagB9p5LIUi0jla:b-ucfknh) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L451)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> I really like the way you did this!
</details>
Thanks!

---

*[README.md, line 531 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdfpa43v3krKDNOOgR:-KPf3at13JWCfYj0wG4U:b-dqvy7f) ([raw file](https://github.com/shakacode/react_on_rails/blob/7f5bde62292fdb1309eb61410b0cf6b6727ab603/README.md#L531)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> While I do realize that  the part on the removed is a little repetitive (the very top), and personal, it's intentional. We fund this and our other open source projects through doing consulting based on it.
</details>
No problem. Would you like me to copy the top section and append it to the bottom?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/524)*

**Comment by justin808** [comment]
:lgtm:

Fabulous job. Thanks @judahmeek 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 14 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-KPdeM0C8pH5ut9Z_gaq:-KPfSe4iOKncB3z6opqv:b3ytnmp) ([raw file](https://github.com/shakacode/react_on_rails/blob/e61c35fca9789a9ae0d2d44854c66f00a093bc36/README.md#L14)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary>
> I scattered the notes throughout the readme according to their relevance. You've found most of them according to your other comments.
> 
> I actually removed the CSS modules note **from this readme** because this issue is addressed by a section in the tutorial repository's readme and viewing that tutorial seemed to be the only way a developer could gain the expectation that the generators would generate the CSS module and hot reloading functionality.
> 
> I'd be happy to re-add the section if you believe it should be in both readmes (Btw, I've submitted a PR for the tutorial repo's readme as well.)
> 
</details>
Sounds good. However, we should reference that topic somewhere in the README.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/524#-:-KPfStN-6ksU7sxLQHMn:b-sng2fa)*

**Pull request merged**
