### PR TITLE
Update #uncommitted_changes? to handle missing Git

### LINKED ISSUE #888: Install generator fails in environment without Git
When running the install generator in an environment without Git, it will fail to run citing:

```
react_on_rails-8.0.3/lib/react_on_rails/git_utils.rb:8:in `uncommitted_changes?': undefined method `empty?' for nil:NilClass (NoMethodError)
```

It will still fail when using `--ignore-warnings` because it tries to evaluate what git status is coming back before looking at the ignore flag. I ran into this specifically because I use docker and exclude the `.git` folders from my containers.

### PR DESCRIPTION
**Pull request by jasonblalock**
- Fix for GitUtils.uncommitted_changes? throwing an error when called in
  an environment that does not have git installed
- Add tests for GitUtils.uncommitted_changes? scenariors
- Fixes #888

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/889)

### CODE REVIEW

**Comment by jasonblalock** [comment]
So for this I worked under the assumption that since Git wasn't installed there were definitely "uncommitted changes" and thus `#uncommitted_changes?` should return true. However I'm open to how you want to handle it.

**Comment by justin808** [comment]
see my question

thanks!

---

Reviewed 3 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/git_utils.rb, line 8 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-KoHHy2eba8feFtoHNVv:-KoHHy2eba8feFtoHNVw:b-y3nll8) ([raw file](https://github.com/shakacode/react_on_rails/blob/43ac002c4880dae2f736f2860ec2872e1d358ae3/lib/react_on_rails/git_utils.rb#L8)):*
> ```Ruby
>       return false if ENV["COVERAGE"] == "true"
>       status = `git status --porcelain`
>       return false if !status.nil? && status.empty?
> ```

Is the status nil if git is not installed?

---

*[spec/react_on_rails/git_utils_spec.rb, line 7 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-KoHI2Y8RTaeAXcItHJH:-KoHI2Y8RTaeAXcItHJI:bfpccl5) ([raw file](https://github.com/shakacode/react_on_rails/blob/43ac002c4880dae2f736f2860ec2872e1d358ae3/spec/react_on_rails/git_utils_spec.rb#L7)):*
> ```Ruby
> module ReactOnRails
>   RSpec.describe GitUtils do
>     describe ".uncommitted_changes?" do
> ```

Is there a test for the case of git is not installed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-:-KoHI8BEOO1SQeSvEOGS:b-1h4e5s)*

**Comment by jasonblalock** [comment]
Thanks, replied and updated.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/git_utils.rb, line 8 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-KoHHy2eba8feFtoHNVv:-KoItYuXGTaBYl2_q1vb:bxmwfbv) ([raw file](https://github.com/shakacode/react_on_rails/blob/43ac002c4880dae2f736f2860ec2872e1d358ae3/lib/react_on_rails/git_utils.rb#L8)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Is the status nil if git is not installed?
</blockquote></details>

I've updated the code to explicitly look at the exit status of the command because I was seeing inconsistency on the return value of a command that was not found. So if exit status is 0 (successful) we can look at the result. Otherwise `uncommitted_changes?` returns true.

---

*[spec/react_on_rails/git_utils_spec.rb, line 7 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-KoHI2Y8RTaeAXcItHJH:-KoIuGJAC4zb_Em4UNHg:b6nt338) ([raw file](https://github.com/shakacode/react_on_rails/blob/43ac002c4880dae2f736f2860ec2872e1d358ae3/spec/react_on_rails/git_utils_spec.rb#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Is there a test for the case of git is not installed?
</blockquote></details>

Yes it's the third context. I've updated the description to be more explicit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-:-KoIuXasr0KcIHdkFax5:brz6qt)*

**Comment by jasonblalock** [comment]
@justin808 Looks like there was a ReadTimeout on one of the Travis builds, could somebody rebuild it?

**Comment by justin808** [comment]
> If you don't have git installed, isn't this error message misleading? @jasonblalock 

I'd say we get more "direct" and check if git is installed.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/git_utils.rb, line 12 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-KoP9XSu8Z7NVW22bve1:-KoP9XSu8Z7NVW22bve2:b-3sylt6) ([raw file](https://github.com/shakacode/react_on_rails/blob/b0bb4ef41ff5243b8b4efc5ca92cffd72c4eb9c3/lib/react_on_rails/git_utils.rb#L12)):*
> ```Ruby
>       return false if $CHILD_STATUS.success? && status.empty?
>       error = "You have uncommitted code. Please commit or stash your changes before continuing"
>       message_handler.add_error(error)
> ```

If you don't have git installed, isn't this error message misleading? @jasonblalock 

---

*[spec/react_on_rails/git_utils_spec.rb, line 47 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-KoP9gluVBUzqEqyPkxs:-KoP9gluVBUzqEqyPkxt:b-ue3ert) ([raw file](https://github.com/shakacode/react_on_rails/blob/b0bb4ef41ff5243b8b4efc5ca92cffd72c4eb9c3/spec/react_on_rails/git_utils_spec.rb#L47)):*
> ```Ruby
>           allow_any_instance_of(Process::Status).to receive(:success?).and_return(false)
>           expect(message_handler).to receive(:add_error)
>             .with("You have uncommitted code. Please commit or stash your changes before continuing")
> ```

this message is misleading if git is not installed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-:-KoP9kXwzWozI79tOqKp:b-gd0hpv)*

**Comment by jasonblalock** [comment]
So we already were checking if Git was installed via `$CHILD_STATUS.success?` so I updated the messaging to indicate if that were not the case.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/git_utils.rb, line 12 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-KoP9XSu8Z7NVW22bve1:-Ko_wKVRYN4rdLk7-9A8:b-5k6y2g) ([raw file](https://github.com/shakacode/react_on_rails/blob/b0bb4ef41ff5243b8b4efc5ca92cffd72c4eb9c3/lib/react_on_rails/git_utils.rb#L12)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

If you don't have git installed, isn't this error message misleading? @jasonblalock 
</blockquote></details>

Updated error messaging to indicate if Git is not installed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-:-Ko_w8g2telzUeytl9Fx:bvcgknn)*

**Comment by jasonblalock** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[spec/react_on_rails/git_utils_spec.rb, line 47 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-KoP9gluVBUzqEqyPkxs:-Ko_wcv0Mrk9VN6UoZiE:b-886gsx) ([raw file](https://github.com/shakacode/react_on_rails/blob/b0bb4ef41ff5243b8b4efc5ca92cffd72c4eb9c3/spec/react_on_rails/git_utils_spec.rb#L47)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

this message is misleading if git is not installed
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/889)*

**Comment by jasonblalock** [comment]
Updated with explicit messaging for git not being installed @justin808

**Comment by justin808** [comment]
:lgtm:

Thanks @jasonblalock 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/889#-:-KpERgLc6sARHMLJR3XG:b-8vavpd)*

**Pull request merged**
