### PR TITLE
Added errors if a null component is registered

### PR DESCRIPTION
**Pull request by justin808**
[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/273)

### CODE REVIEW

**Comment by justin808** [comment]
@robwise @jbhatab or @alexfedoseev, please review so I can merge.

**Comment by justin808** [comment]
@robwise There's an error with auto-rebuilding of the server rendering file:

### Repro:

```sh
rake examples:gen_basic-server-rendering
cd gen-examples/examples/basic-server-rendering
rspec
```

But if you then run: `foreman start -f Procfile.dev` and then run rspec, tests pass.

**Comment by justin808** [comment]
@alexfedoseev Please review.

**Comment by justin808** [comment]
@robwise Looks like it was a transient issue.

**Comment by alexfedoseev** [comment]
Looks good! :+1:

**Comment by jbhatab** [comment]
LGTM

**Pull request merged**
