### PR TITLE
VERSION 9.0: Fixing rails 3.2 test run

### PR DESCRIPTION
**Pull request by morozovm**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/926)

### CODE REVIEW

**Comment by morozovm** [comment]
hi @justin808 i fixed 3.2 but run into Server Rendering spec failing
```
Server Rendering
  reloading the server bundle
    reloads the server bundle on a new request if was changed
```
```
ActionView::Template::Error (uninitialized constant ReactOnRails::ServerRenderingPool::Exec::Webpacker):
    1: <%= render "header" %>
    2: 
    3: <%= react_component("HelloWorld",
    4:                     props: @app_props_server_render.to_json,
    5:                     prerender: true,
    6:                     trace: true,
  app/views/pages/server_side_hello_world_with_options.html.erb
```
in log/test.log

is there some ReactOnRails configuration changes missing in dummy_no_webpacker or it is actual issue?

**Comment by justin808** [comment]
@morozovm We need to make sure that lines like this:
https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/utils.rb#L77

are never executed if the Webpacker Gem is not installed...

In most cases, we can call `using_webpacker?` before any call that will use Webpacker methods.

I'm not sure what to do on the rescue statement, other than maybe when the app loads if Webpacker is not defined, then we'll create the `Webpacker::Manifest::MissingEntryError`. Alternately, we can catch any `StandardError` and then check if using_webpacker? and the error is the `Webpacker::Manifest::MissingEntryError` and then do the appropriate thing or else log the error and re-throw.

I think probably the latter is simpler.

**Comment by justin808** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[rakelib/run_rspec.rake, line 25 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-KtUCcUEdoj8bChaS4Pc:-KtUCcUEdoj8bChaS4Pd:b-4me70d) ([raw file](https://github.com/shakacode/react_on_rails/blob/17fe25dab5e98e7deff179b075742f31220d789c/rakelib/run_rspec.rake#L25)):*
> ```Ruby
>     rspec_args = "spec/react_on_rails --tag ~webpacker --exclude-pattern "\
>                  "\"**/generators/*_spec.rb,"\
>                  "**/test_helper/webpack_*_spec.rb\""
> ```

Nice job on adding the webpacker tag.

CC: @alexfedoseev 

---

*[spec/react_on_rails/spec_helper.rb, line 30 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-KtUCqoD4Zbx7wnE9Sau:-KtUCqoD4Zbx7wnE9Sav:bjd05om) ([raw file](https://github.com/shakacode/react_on_rails/blob/17fe25dab5e98e7deff179b075742f31220d789c/spec/react_on_rails/spec_helper.rb#L30)):*
> ```Ruby
> require_relative "./simplecov_helper"
> # prevent Test::Unit's AutoRunner from executing during RSpec's rake task
> Test::Unit.run = true if defined?(Test::Unit) && Test::Unit.respond_to?(:run=)
> ```

Why was this happening, @morozovm? 

---

*[spec/react_on_rails/utils_spec.rb, line 17 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-KtUCvSaEN7089eHfKT_:-KtUCvSaEN7089eHfKTa:bde6soj) ([raw file](https://github.com/shakacode/react_on_rails/blob/17fe25dab5e98e7deff179b075742f31220d789c/spec/react_on_rails/utils_spec.rb#L17)):*
> context "With Webpacker enabled and file in manifest", :webpacker => true do·

`context "With Webpacker enabled and file in manifest", webpacker: true do`

or 

`context "With Webpacker enabled and file in manifest", :webpacker do`

Will either of those work? I typically do the latter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926)*

**Comment by morozovm** [comment]
*[spec/react_on_rails/utils_spec.rb, line 17 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-KtUCvSaEN7089eHfKT_:-KtbF21uD4R4iTCxq_h8:b-7ql1td) ([raw file](https://github.com/shakacode/react_on_rails/blob/17fe25dab5e98e7deff179b075742f31220d789c/spec/react_on_rails/utils_spec.rb#L17)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

> context "With Webpacker enabled and file in manifest", :webpacker => true do·

`context "With Webpacker enabled and file in manifest", webpacker: true do`

or 

`context "With Webpacker enabled and file in manifest", :webpacker do`

Will either of those work? I typically do the latter.

</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926)*

**Comment by morozovm** [comment]
@justin808  
safe_constantize should do the trick

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-:-KtbFTQRdXPHiBn4Iye4:b7gm568)*

**Comment by morozovm** [comment]
*[spec/react_on_rails/spec_helper.rb, line 30 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-KtUCqoD4Zbx7wnE9Sau:-KtbXHbPRLV1kd1C2A4I:b-4g3oc8) ([raw file](https://github.com/shakacode/react_on_rails/blob/17fe25dab5e98e7deff179b075742f31220d789c/spec/react_on_rails/spec_helper.rb#L30)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Why was this happening, @morozovm? 
</blockquote></details>

activesupport 3.2.22.5 demands test-unit to be loaded
```
begin
  require 'test/unit/testcase'
rescue LoadError => e
  raise LoadError, "Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (#{e.message})", e.backtrace
end
```
this hack is solution to loading test-unit and rspec simultaneously by tricking test-unit in into thinking it is already done running. As far as i can see it is only viable solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926)*

**Comment by morozovm** [comment]
*[rakelib/run_rspec.rake, line 25 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-KtUCcUEdoj8bChaS4Pc:-KtbaUN8Sw1RlVyWMNml:b44u47) ([raw file](https://github.com/shakacode/react_on_rails/blob/17fe25dab5e98e7deff179b075742f31220d789c/rakelib/run_rspec.rake#L25)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Nice job on adding the webpacker tag.

CC: @alexfedoseev 
</blockquote></details>

🙏

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926)*

**Comment by justin808** [comment]
@morozovm Please rebase your changes on top of master and when github says I can merge, I will.

**Comment by justin808** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/utils.rb, line 77 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-Ktd8_pW88r9iNXRPJZ9:-Ktd8_pW88r9iNXRPJZA:bj87ujq) ([raw file](https://github.com/shakacode/react_on_rails/blob/2073c96961e718e3fd6480b3e005e5b456b9480c/lib/react_on_rails/utils.rb#L77)):*
> ```Ruby
>       @server_bundle_path = begin
>         bundle_js_file_path(bundle_name)
>       rescue ActiveSupport::Inflector.safe_constantize("Webpacker::Manifest::MissingEntryError")
> ```

@morozovm did you try this thoroughly and provide tests for the cases:

1. exception is thrown
1a. with Wepbacker
1b. without Webpacker

I created a small test, and `rescue nil` seems to crash.
```ruby
require "active_support/all"

def start_summer
  raise "overheated!"
end

begin
  start_summer
rescue ActiveSupport::Inflector.safe_constantize("Xyz")
  puts "Let me tell you about heat! #{e.inspect}"
end
```

output:
```
/Users/justin/.rvm/rubies/ruby-2.4.1/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/justin/Library/Preferences/RubyMine2017.2/scratches/scratch_1.rb
/Users/justin/Library/Preferences/RubyMine2017.2/scratches/scratch_1.rb:9:in `rescue in <top (required)>': class or module required for rescue clause (TypeError)
	from /Users/justin/Library/Preferences/RubyMine2017.2/scratches/scratch_1.rb:7:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
``` 

---

*[spec/react_on_rails/spec_helper.rb, line 30 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-KtUCqoD4Zbx7wnE9Sau:-KtdJLEXAbuMb8HAEtoC:bldw1ws) ([raw file](https://github.com/shakacode/react_on_rails/blob/17fe25dab5e98e7deff179b075742f31220d789c/spec/react_on_rails/spec_helper.rb#L30)):*
<details><summary><i>Previously, morozovm (Maksim Morozov) wrote…</i></summary><blockquote>

activesupport 3.2.22.5 demands test-unit to be loaded
```
begin
  require 'test/unit/testcase'
rescue LoadError => e
  raise LoadError, "Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (#{e.message})", e.backtrace
end
```
this hack is solution to loading test-unit and rspec simultaneously by tricking test-unit in into thinking it is already done running. As far as i can see it is only viable solution.
</blockquote></details>

what's the resolution of this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926)*

**Comment by morozovm** [comment]
*[lib/react_on_rails/utils.rb, line 77 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-Ktd8_pW88r9iNXRPJZ9:-Ktet5jgrhZB6aNHJs74:buitflv) ([raw file](https://github.com/shakacode/react_on_rails/blob/2073c96961e718e3fd6480b3e005e5b456b9480c/lib/react_on_rails/utils.rb#L77)):*
@justin808
oops! i guess they changed this behavior long time ago https://bugs.ruby-lang.org/issues/9335
> Status changed from Open to Rejected
> It had been allowed on 1.9.3 accidentally.
> In other words, it's a fixed bug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926)*

**Comment by morozovm** [comment]
*[spec/react_on_rails/spec_helper.rb, line 30 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-KtUCqoD4Zbx7wnE9Sau:-Ktf09YdnKJeZ-mr52-G:bcvc9em) ([raw file](https://github.com/shakacode/react_on_rails/blob/17fe25dab5e98e7deff179b075742f31220d789c/spec/react_on_rails/spec_helper.rb#L30)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

what's the resolution of this one?
</blockquote></details>

the solution is to set Test::Unit.run = true if Test::Unit defined as i did or i misunderstood the question?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926)*

**Comment by morozovm** [comment]
changes rebased

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-:-Ktf4QMnpIj-1S_B_L-i:b-me0crm)*

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/926#-:-KthAGE_EAz_TIMdnb9M:bnfp4nl)*

**Pull request merged**
