### PR TITLE
Address linting issues

### PR DESCRIPTION
**Pull request by justin808**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/528)

### CODE REVIEW

**Comment by justin808** [comment]
@jbhatab Please work off of this. I got a start on this for you.

@alleycat-at-git Please be sure your change for big initialization data went in here.

**Comment by justin808** [comment]
Some comments

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.eslintignore, line 8 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/528#-KPj3ixa1xK8KZucxGSN:-KPj3ixa1xK8KZucxGSO:b-wqd8t1) ([raw file](https://github.com/shakacode/react_on_rails/blob/e206f1e380e0c0eff3b869d53dc00fc7f9c4b51f/.eslintignore#L8)):*
> ```
> node_package/tests/node_modules
> node_package/webpack.config.js
> gen-examples/examples
> ```

@robwise @jbhatab We want to lint these.

---

*[lib/generators/react_on_rails/templates/node/base/client/node/server.js, line 73 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/528#-KPj3fmdorAqKd4_lexy:-KPj3fmebHQwDpjjp8Je:b-ngb39g) ([raw file](https://github.com/shakacode/react_on_rails/blob/e206f1e380e0c0eff3b869d53dc00fc7f9c4b51f/lib/generators/react_on_rails/templates/node/base/client/node/server.js#L73)):*
> ```JavaScript
>     }
> 
>     require(bundlePath + bundleFileName);
> ```

let's put the global require disable here, not at the top

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/528#-:-KPj3n_tZtAW-r0ZWREr:bv6hrbv)*

**Comment by jbhatab** [comment]
*[.eslintignore, line 8 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/528#-KPj3ixa1xK8KZucxGSN:-KPjestOuAKJwaB7jHkN:b-hfpv0l) ([raw file](https://github.com/shakacode/react_on_rails/blob/e206f1e380e0c0eff3b869d53dc00fc7f9c4b51f/.eslintignore#L8)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> @robwise @jbhatab We want to lint these.
</details>
removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/528)*

**Comment by justin808** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/528#-:-KPk3N3YKlyWLdc2uwI4:bg7igkv)*

**Pull request merged**
