### PR TITLE
Compatibility with Ruby 2.0+

### PR DESCRIPTION
**Pull request by bbonamin**
First of all, let me express how grateful I am for this gem. I've recently been learning about react and webpack, and react_on_rails has made it a breeze to implement what I've learned in my Rails projects! It's allowed us to add "sprinkles" of React in certain Rails views, without commiting to rewriting everything from scratch. Thank you!

Now, for a project I'm currently working on, we need compatibility with Ruby 2.0 (yeah yeah, I know it's not receiving fixes or patches anymore, but we can't upgrade yet.)

The [rubygems page for react_on_rails](https://rubygems.org/gems/react_on_rails) doesn't specify a minimum ruby version, but if you try to use the gem with < 2.1, it breaks because of the required keyword arguments that were introduced in 2.1.

The changes in this PR do "backport" this behavior to 2.0. I couldn't find anything else other than these syntax changes that would make the gem incompatible with 2.0, and tests seem to pass.

Thoughts?

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/651)

### CODE REVIEW

**Comment by bbonamin** [comment]
Something seems to be up with TravisCI trying to install fsevents. The build was green when I removed it from the npm shrinkwrap file on my fork, but of course that was a change that I didn't want to include in this

**Comment by justin808** [comment]
@samnang @mapreal19 @robwise This one looks OK to me. Ugly, but I guess some people need it.

I vote for this one. How about you guys?

**Comment by samnang** [comment]
@justin808 To me, it's okay if we want to support them for a while and pay attention of features that might break for this, but it shouldn't a long term because Rails 5 already drop their support. If we just trying with minimum dependency on Rails, then it might not be a problem.

**Comment by mapreal19** [comment]
@justin808 @bbonamin we could remove the duplication for those required arguments with a helper method. Take a look at this answer http://stackoverflow.com/a/15078852/2273578

I would rather see those methods like this:

```ruby
def  rails_context(server_side: required) 
```

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/651#-:-KZgjK8FxR6yD2g7oTXG:b-weycta)*

**Comment by robwise** [comment]
lol I vote for this just the way I voted for it the last time someone did this almost a year ago, this repo really hardly uses keyword arguments so it's a no-brainer to keep it backwards compatible. I'm not sure why we keep re-introducing breaking changes: 

 https://github.com/shakacode/react_on_rails/blob/28776cbc36b22dc3aa91a5b1fe9f9b2b3c20fdc7/CHANGELOG.md#210---2016-01-26

**Comment by bbonamin** [comment]
@mapreal19 I've pushed a change with a DRYer approach to doing to required validation. Let me know if you think it's good 😃

**Comment by justin808** [comment]
Please rebase your changes on top of my latest commit.

**Comment by bbonamin** [comment]
Done 👍 ! Merry Christmas! 🎄

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGELOG.md, line 9 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/651#-KZrNDoFmecDuNTz0YqK:-KZrNDoGCbRIl2kjFu8M:b-qyrq38) ([raw file](https://github.com/shakacode/react_on_rails/blob/ab689f0b6982f37322f2291f3de6b23c06e019b7/CHANGELOG.md#L9)):*
> ```Markdown
> *Please add entries here for your pull requests.*
> ##### Fixed
> - Added support for Ruby 2.0.
> ```

Please see the other changelog entries and make consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/651)*

**Comment by justin808** [comment]
Please put your changelog comments under 6.3.3.

**Comment by bbonamin** [comment]
@justin808 Thanks for the feedback! I've addressed your comments, and added a `required_ruby_version` to the gemspec (http://guides.rubygems.org/specification-reference/), so it's picked up by rubygems.org

**Comment by justin808** [comment]
:lgtm:

GREAT JOB!

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/651#-:-KZsUl_rJt2Vex4Owgdv:b-smg5tk)*

**Comment by mapreal19** [comment]
:lgtm: Thanks @bbonamin!

---

Reviewed 1 of 7 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/651#-:-KZvcxFThVUU0etVwkJh:b-d3bguf)*

**Pull request merged**
