### PR TITLE
Using yarn instead of npm

### PR DESCRIPTION
**Pull request by squadette**
Here is preliminary pull-request for using yarn.  It seems to be passing tests on my machine (the same as for vanilla npm).

Currently it fails in Travis because of https://github.com/yarnpkg/yarn/issues/683#issuecomment-267953198

I'm going to add `--mutex network` and try again.  Please test this in your environments.

NB: first two commits are mostly written by @justin808, but were improved/fixed by me.  Justin, please feel free to adjust attribution before merging however you wish. 

Thanks,

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/715)

### CODE REVIEW

**Comment by justin808** [comment]
Lots of comments. Good start!

---

Reviewed 54 of 54 files at r1.
Review status: 50 of 54 files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntL0V1cNABeCkvt5j:-KcntL0V1cNABeCkvt5k:b-1gyqyz) ([raw file](https://github.com/shakacode/react_on_rails/blob/0ec2f39ad9817716f890fe49d9fe8fa4fa3137cd/.travis.yml#L9)):*
> ```YAML
>   - 2.1.10
>   - 2.2.6
>   - 2.3.1
> ```

should not be removed

we want to support older versions of ruby and also ruby 2.4!

---

*[CONTRIBUTING.md, line 99 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntW6BNi0LavYhNH97:-KcntW6BNi0LavYhNH98:b7mh8cb) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/CONTRIBUTING.md#L99)):*
> ```Markdown
> ```
> 
> When you use a relative path, be sure to run the above `yarn` command whenever you change the node package for react-on-rails.
> ```

Please double check on if there is a yarn link that we can use.

---

*[package.json, line 59 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntjgzwxQ2q74Nj54p:-KcntjgzwxQ2q74Nj54q:bziex89) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/package.json#L59)):*
> ```JSON
>     "lint": "yarn run eslint && yarn run jscs && yarn run flow",
>     "lint:fix": "node_package/scripts/lint-fix",
>     "check": "yarn run lint && yarn run test",
> ```

where is flow?

---

*[docs/additional-reading/node-dependencies-and-npm.md, line 9 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntvOnHo-5Dg09GdW0:-KcntvOnHo-5Dg09GdW1:b-jab1zc) ([raw file](https://github.com/shakacode/react_on_rails/blob/0ec2f39ad9817716f890fe49d9fe8fa4fa3137cd/docs/additional-reading/node-dependencies-and-npm.md#L9)):*
> ```Markdown
> npm install -g npm-check-updates
> rm npm-shrinkwrap.json
> npm-check-updates -u
> ```

this updates the dependencies

I still use this with yarn

Please investigate

---

*[lib/generators/react_on_rails/dev_tests_generator.rb, line 33 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcnuKFWRxCQJWUbHWJ7:-KcnuKFWRxCQJWUbHWJ8:bslsjx9) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/lib/generators/react_on_rails/dev_tests_generator.rb#L33)):*
> ```Ruby
>         old_contents = File.read(package_json)
>         new_contents = old_contents.gsub(/"react-on-rails": ".+",/,
>                                          '"react-on-rails": "file:../../../..",')
> ```

why this change?

yarn change?

---

*[lib/react_on_rails/test_helper/node_process_launcher.rb, line 4 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcnuZRVt1E9e3zbGQer:-KcnuZRVt1E9e3zbGQes:b8471y7) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/lib/react_on_rails/test_helper/node_process_launcher.rb#L4)):*
> ```Ruby
>   module TestHelper
>     def self.launch_node
>       if ReactOnRails.configuration.server_render_method == "NodeJS"
> ```

this will probably cause a lint error

rubocop wants a guard clause

---

*[spec/dummy/package.json, line 45 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcnukEelapRRKz3m7Yp:-KcnukEelapRRKz3m7Yq:b-hkj53c) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/spec/dummy/package.json#L45)):*
> ```JSON
>     "react": ">= 0.14",
>     "react-dom": ">= 0.14",
>     "react-on-rails": "file:../.."
> ```

this is wrong

all of this should be in spec/dummy/client/package.json

---

*[spec/react_on_rails/generators/dev_tests_generator_spec.rb, line 27 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcoLKa-d5yN1ZhhAI27:-KcoLKa-d5yN1ZhhAI28:b-snnzkh) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/spec/react_on_rails/generators/dev_tests_generator_spec.rb#L27)):*
> ```Ruby
>     it "changes package.json to use local react-on-rails version of module" do
>       assert_file("client/package.json") do |contents|
>         assert_match('"react-on-rails": "file:../../../.."', contents)
> ```

Not sure on this one. Please explain.

---

*[spec/react_on_rails/generators/install_generator_spec.rb, line 94 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcoLP_qnlWQFbYmzlre:-KcoLP_qnlWQFbYmzlrf:b2v7i7e) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/spec/react_on_rails/generators/install_generator_spec.rb#L94)):*
> ```Ruby
>               bundle && yarn
> 
>           - Run the foreman command to load the rails server and webpack process
> ```

start?

why change to load?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-:-KcoLaGehjriXFxiQED9:b-pzqk38)*

**Comment by justin808** [comment]
@squadette I'm going to wait to hear from you. I don't understand why you moved node_package. It doesn't make sense for react_on_rails to have a subdirectory called react-on-rails.

---

Reviewed 68 of 68 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 25 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcoVGINIhCQRgHRsdZm:-KcoVGINIhCQRgHRsdZn:bqebhii) ([raw file](https://github.com/shakacode/react_on_rails/blob/cc0baf9ceebfba50b9b722bae7e4a967effb7129/.gitignore#L25)):*
> ```
> node_modules
> 
> react-on-rails/node_package/lib
> ```

why this change?

---

*[package.json, line 59 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntjgzwxQ2q74Nj54p:-KcoVMKWYM7dl2giFOjr:b-w6pyo4) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/package.json#L59)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

where is flow?
</blockquote></details>

@squadette Please try to answer my questions within https://reviewable.io/reviews/shakacode/react_on_rails/715#-KcntjgzwxQ2q74Nj54p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-:-KcoVtPqWYMgWWqpGYjz:bs70q4q)*

**Comment by squadette** [comment]
> I don't understand why you moved node_package.

Of course.  I had a theory, but looks like i"m wrong.  I'll either move it back or explain why this change is needed.  I'm still fighting :)

**Comment by squadette** [comment]
Okay, looks like tests pass: https://travis-ci.org/squadette/react_on_rails/builds/200978571

Except for eslint warnings in: https://travis-ci.org/squadette/react_on_rails/builds/200978571#L4634

**Comment by squadette** [comment]
Review status: 43 of 54 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntL0V1cNABeCkvt5j:-KcogQ-Af7Llk9USW49e:b-btg3jt) ([raw file](https://github.com/shakacode/react_on_rails/blob/0ec2f39ad9817716f890fe49d9fe8fa4fa3137cd/.travis.yml#L9)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

should not be removed

we want to support older versions of ruby and also ruby 2.4!
</blockquote></details>

Of course, it's just for my tests to be faster.  Before the merge this part will be reverted.  Thanks for the reminder.

---

*[spec/dummy/package.json, line 45 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcnukEelapRRKz3m7Yp:-KcogtqKQ7jDYG8tVeR7:b1711d0) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/spec/dummy/package.json#L45)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

this is wrong

all of this should be in spec/dummy/client/package.json
</blockquote></details>

you're right, I remove this in a separate commit. Thank you, 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715)*

**Comment by justin808** [comment]
@squadette Let me know when you're ready for more review.

**Comment by squadette** [comment]
Review status: 41 of 57 files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[.gitignore, line 25 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcoVGINIhCQRgHRsdZm:-Kd3L2Wxo4oy-c99u1P5:bpvzqxc) ([raw file](https://github.com/shakacode/react_on_rails/blob/cc0baf9ceebfba50b9b722bae7e4a967effb7129/.gitignore#L25)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

I think I've seen yarn creating those files, but maybe it's a false memory.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntL0V1cNABeCkvt5j:-Kd3L8niNa2PoMYKliJI:ber4y2x) ([raw file](https://github.com/shakacode/react_on_rails/blob/0ec2f39ad9817716f890fe49d9fe8fa4fa3137cd/.travis.yml#L9)):*
<details><summary><i>Previously, squadette (Alexey Mahotkin) wrote…</i></summary><blockquote>

Of course, it's just for my tests to be faster.  Before the merge this part will be reverted.  Thanks for the reminder.
</blockquote></details>

returned all the versions.  Tries to introduce 2.4.0, but that's too hard for now, there will be a separate PR.

---

*[CONTRIBUTING.md, line 99 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntW6BNi0LavYhNH97:-Kd3LR4-F59ddUaFqHGj:b-25uub2) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/CONTRIBUTING.md#L99)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Please double check on if there is a yarn link that we can use.
</blockquote></details>

Let's try to change to yarn link later.  I don't understand exactly how yarn link works.

---

*[package.json, line 59 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntjgzwxQ2q74Nj54p:-Kd3N48P7NUbldHVL7Q_:bimusf5) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/package.json#L59)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

@squadette Please try to answer my questions within https://reviewable.io/reviews/shakacode/react_on_rails/715#-KcntjgzwxQ2q74Nj54p
</blockquote></details>

Merge issue. Thank you,

---

*[docs/additional-reading/node-dependencies-and-npm.md, line 9 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcntvOnHo-5Dg09GdW0:-Kd3N8PxWC8PlpNu3Q_w:b3nr8ut) ([raw file](https://github.com/shakacode/react_on_rails/blob/0ec2f39ad9817716f890fe49d9fe8fa4fa3137cd/docs/additional-reading/node-dependencies-and-npm.md#L9)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

this updates the dependencies

I still use this with yarn

Please investigate
</blockquote></details>

To upgrade all dependencies, use `yarn upgrade`.  

---

*[lib/react_on_rails/test_helper/node_process_launcher.rb, line 4 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcnuZRVt1E9e3zbGQer:-Kd3J_YyQWPxq0un82_Y:b-yis5n7) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/lib/react_on_rails/test_helper/node_process_launcher.rb#L4)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

this will probably cause a lint error

rubocop wants a guard clause
</blockquote></details>

yep, fixed.

---

*[spec/dummy/package.json, line 45 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcnukEelapRRKz3m7Yp:-Kd3JcfuafcZEvabFKbl:b-7ql1td) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/spec/dummy/package.json#L45)):*
<details><summary><i>Previously, squadette (Alexey Mahotkin) wrote…</i></summary><blockquote>

you're right, I remove this in a separate commit. Thank you, 
</blockquote></details>

fixed

---

*[spec/react_on_rails/generators/dev_tests_generator_spec.rb, line 27 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcoLKa-d5yN1ZhhAI27:-Kd3Jn_CGpvPZJmStsTF:b-o7fyha) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/spec/react_on_rails/generators/dev_tests_generator_spec.rb#L27)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Not sure on this one. Please explain.
</blockquote></details>

It just checks for a string, and the string changed because of yarn syntax for modules in a directory.

---

*[spec/react_on_rails/generators/install_generator_spec.rb, line 94 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcoLP_qnlWQFbYmzlre:-Kd3KafDP5BnM-d9g6jt:b-kzogml) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/spec/react_on_rails/generators/install_generator_spec.rb#L94)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

start?

why change to load?
</blockquote></details>

This is taken from your commit https://github.com/shakacode/react_on_rails/commit/cfc10a9549413166b1fd4eee95766aa3f5a8e4ba#diff-08931bab4b6ac3bc6fa0986cadb6a576 :)  If you don't like the wording then please change it as you wish.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715)*

**Comment by squadette** [comment]
Update: Travis passed: https://travis-ci.org/squadette/react_on_rails/builds/202086175

@justin808, please consider merging this PR. 

Thank you,

**Comment by squadette** [comment]
Review status: 42 of 54 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[lib/generators/react_on_rails/dev_tests_generator.rb, line 33 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcnuKFWRxCQJWUbHWJ7:-Kd3UKzoZdPgAUJtP2jl:b-uinws0) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/lib/generators/react_on_rails/dev_tests_generator.rb#L33)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why this change?

yarn change?
</blockquote></details>

yes.  a syntax for module in a directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715)*

**Comment by justin808** [comment]
A few comments. Getting close!

CC: @robwise @alexfedoseev 

---

Reviewed 14 of 66 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 41 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-Kd5A1yngt-hEGayQZt3:-Kd5A1yngt-hEGayQZt4:b-hxhdjo) ([raw file](https://github.com/shakacode/react_on_rails/blob/5301e8121f33c554c64082f6318183286087384f/.travis.yml#L41)):*
> ```YAML
>   - nvm install node
>   - node -v
>   - npm i -g yarn@0.19.0
> ```

0.19.1 but check

maybe we best not specify the version and we'll get the latest

---

*[package.json, line 86 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-Kd5ABSJix7rQFBRNadl:-Kd5ABSJix7rQFBRNadm:bh5b05x) ([raw file](https://github.com/shakacode/react_on_rails/blob/5301e8121f33c554c64082f6318183286087384f/package.json#L86)):*
> ```JSON
>   "homepage": "https://github.com/shakacode/react_on_rails#readme",
>   "dependencies": {
>     "jscs": "^3.0.7"
> ```

what is this? this probably needs to be removed.

eslint replaced jscs a while back.

---

*[spec/dummy/client/package.json, line 66 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-Kd5ASmOQ6VC1wZH3pzd:-Kd5ASmOQ6VC1wZH3pze:b-pifj4g) ([raw file](https://github.com/shakacode/react_on_rails/blob/5301e8121f33c554c64082f6318183286087384f/spec/dummy/client/package.json#L66)):*
> ```JSON
>   },
>   "scripts": {
>     "lint": "yarn run eslint --silent && yarn run jscs --silent",
> ```

remove jscs

---

*[spec/dummy/client/package.json, line 69 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-Kd5APjZ1mWCXh3aOYih:-Kd5APjZ1mWCXh3aOYii:b-lc7wps) ([raw file](https://github.com/shakacode/react_on_rails/blob/5301e8121f33c554c64082f6318183286087384f/spec/dummy/client/package.json#L69)):*
> ```JSON
>     "eslint": "eslint --ext .js,.jsx .",
>     "jscs": "jscs --verbose .",
>     "jscs:fix": "jscs --verbose -x . --silent",
> ```

get rid of jscs

---

*[spec/react_on_rails/generators/install_generator_spec.rb, line 94 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-KcoLP_qnlWQFbYmzlre:-Kd59_70TyF2O0cDjIWw:bsy9342) ([raw file](https://github.com/shakacode/react_on_rails/blob/16c4c34fe4288a2128eaecffe66e13eaf4c70a3d/spec/react_on_rails/generators/install_generator_spec.rb#L94)):*
> Run the foreman command to start the rails server and run webpack in watch mode.

let's revert that line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-:-Kd5Aj32zR3cIkjh2Rpk:b-e21kgh)*

**Comment by squadette** [comment]
Review status: 48 of 54 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 41 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-Kd5A1yngt-hEGayQZt3:-Kd7oVt1dnFZrWS6dCbv:b-rg7t5s) ([raw file](https://github.com/shakacode/react_on_rails/blob/5301e8121f33c554c64082f6318183286087384f/.travis.yml#L41)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

0.19.1 but check

maybe we best not specify the version and we'll get the latest
</blockquote></details>

0.20.3 even.  (no we did not get the latest last time I tried.  Plus it's better to control the testing environment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715)*

**Comment by justin808** [comment]
:lgtm:

Thanks for the contribution! Great work!

---

Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-:-Kd81TuRUqiNEMXfMfRG:b-obygse)*

**Comment by squadette** [comment]
Updated finally.  My build passes: https://travis-ci.org/squadette/react_on_rails/builds/202424502

shakacode build could just be restarted, it's a spurious error.

Thanks,

**Comment by squadette** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[package.json, line 86 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-Kd5ABSJix7rQFBRNadl:-KdFxKjyrAnoeWa2aPwD:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/5301e8121f33c554c64082f6318183286087384f/package.json#L86)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

what is this? this probably needs to be removed.

eslint replaced jscs a while back.
</blockquote></details>

Done.

---

*[spec/dummy/client/package.json, line 66 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-Kd5ASmOQ6VC1wZH3pzd:-KdFxM-KsYUMXP5VVCGp:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/5301e8121f33c554c64082f6318183286087384f/spec/dummy/client/package.json#L66)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

remove jscs
</blockquote></details>

Done.

---

*[spec/dummy/client/package.json, line 69 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-Kd5APjZ1mWCXh3aOYih:-KdFxMX2VlzkArbOfmcN:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/5301e8121f33c554c64082f6318183286087384f/spec/dummy/client/package.json#L69)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

get rid of jscs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715)*

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/715#-:-KdI5bqcvwjpntf31sbz:bnfp4nl)*

**Comment by justin808** [comment]
@squadette I'm testing locally and I'll merge if I see no issues!

**Comment by justin808** [comment]
Great job @squadette! Next is Webpack v2.2.0 and the improved serialization of props!

**Comment by squadette** [comment]
Thank for merging :)

**Comment by squadette** [comment]
Btw, I've just migrated my project to Webpack 2.2.0.  It required two trivial changes to webpack.config.js:

```
diff --git a/client/webpack.config.js b/client/webpack.config.js
index f9a1c6c..7ac7951 100644
--- a/client/webpack.config.js
+++ b/client/webpack.config.js
@@ -27,7 +27,7 @@ const config = {
   },
 
   resolve: {
-    extensions: ['', '.js', '.jsx'],
+    extensions: ['.js', '.jsx'],
     alias: {
       react: path.resolve('./node_modules/react'),
       'react-dom': path.resolve('./node_modules/react-dom'),
@@ -44,7 +44,7 @@ const config = {
     loaders: [
       {
         test: require.resolve('react'),
-        loader: 'imports?shim=es5-shim/es5-shim&sham=es5-shim/es5-sham',
+        loader: 'imports-loader?shim=es5-shim/es5-shim&sham=es5-shim/es5-sham',
       },
       {
         test: /\.jsx?$/,
````

Also, dedupePlugin needs to be removed, and tree shaking can enabled by 

````
diff --git a/client/.babelrc b/client/.babelrc
index 9b7d435..0b1ef27 100644
--- a/client/.babelrc
+++ b/client/.babelrc
@@ -1,3 +1,3 @@
 {
-  "presets": ["es2015", "stage-0", "react"]
+  "presets": [ ["es2015", { modules: false } ], "stage-0", "react"]
 }
````

After that, everything works at least for me.

**Comment by justin808** [comment]
@squadette Yes, let's convert the whole project to be using Webpack 2.2.x!

**Pull request merged**
