### PR TITLE
Fixes turbolinks loading issue

### PR DESCRIPTION
**Pull request by justin808**
Code was checking that turbolinks was installed when it was not yet
because some setups load turbolinks after the bundles. The changes to
the code will check if turbolinks is installed after the page loaded
event fires.

Code was also added to allow easy debugging of Turbolinks, which should
be useful when v5 of Turbolinks is released shortly.

Details of how to configure Turbolinks with troubleshooting were added
to docs/additional_reading/turbolinks.md.

Also:

* Changed generation of the examples apps to /tmp/examples. This allows
  one to configure editors to ignore /tmp. Ignoring /examples is
  problematic as one deletes the /examples directory frequently.

[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/221)

### CODE REVIEW

**Comment by justin808** [comment]
@alexfedoseev Can you please review ASAP

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/221#-:-K8movxlaUkisHuIspgY:856170078)*

**Comment by alexfedoseev** [comment]
@justin808 Looks good! One small comment.

---

Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[spec/dummy/client/app/components/HelloWorld.jsx, line 22 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/221#-K8n3GrXdfSdrRQ2Ilqz:-K8n3GrXdfSdrRQ2Ilr-:1086489533) ([raw file](https://github.com/shakacode/react_on_rails/blob/dbd07e62f56a3fdb9eb27ae324de45d47a77a47b/spec/dummy/client/app/components/HelloWorld.jsx#L22)):*
This is kinda legacy way.

```js
setDomRef(domNode) {
  this.myDomRef = domNode;
}

handleChange() {
  const myDomNode = this.myDomRef;
  // ...
}

render() {
  return (
    <div
      ref={this.setDomRef}
      onChange={this.handleChange}
    />
  );
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/221#-:-K8n5FWI-EpD8I-rEkzg:1600952566)*

**Comment by robwise** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/221)*

**Comment by justin808** [comment]
Review status: 22 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[spec/dummy/client/app/components/HelloWorld.jsx, line 22 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/221#-K8n3GrXdfSdrRQ2Ilqz:-K8p1P018nFRbEeVlALT:1909557357) ([raw file](https://github.com/shakacode/react_on_rails/blob/dbd07e62f56a3fdb9eb27ae324de45d47a77a47b/spec/dummy/client/app/components/HelloWorld.jsx#L22)):*
@alexfedoseev Any reference? Why is this better?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/221)*

**Comment by robwise** [comment]
Review status: 22 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[spec/dummy/client/app/components/HelloWorld.jsx, line 22 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/221#-K8n3GrXdfSdrRQ2Ilqz:-K8p1rOvZbHKNpLqb7sQ:-559013532) ([raw file](https://github.com/shakacode/react_on_rails/blob/dbd07e62f56a3fdb9eb27ae324de45d47a77a47b/spec/dummy/client/app/components/HelloWorld.jsx#L22)):*
I still think `<input ref={(ref) => this.name = ref} />` is the slickest, but the style guide won't allow it :(

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/221)*

**Comment by robwise** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/221)*

**Comment by alexfedoseev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[spec/dummy/client/app/components/HelloWorld.jsx, line 22 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/221#-K8n3GrXdfSdrRQ2Ilqz:-K8p2TnI55WDVMLsTYW1:2046070189) ([raw file](https://github.com/shakacode/react_on_rails/blob/dbd07e62f56a3fdb9eb27ae324de45d47a77a47b/spec/dummy/client/app/components/HelloWorld.jsx#L22)):*
http://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/221)*

**Comment by robwise** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/221)*

**Comment by justin808** [comment]
Woo hoo! releasing later today!!!

**Pull request merged**
