### PR TITLE
Add clear timeout polyfill

### PR DESCRIPTION
**Pull request by martyphee**
Added clearTimeout to `execjs_timer_polyfills`.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/451)

### CODE REVIEW

**Comment by martyphee** [comment]
@justin808 I didn't see any current tests to add this to.  We're currently running 5.2.  I have to see about upgrading to 6.x

**Comment by xiaopow** [comment]
@martyphee Anyway I can start using this code for my app? I haven't found any other work around. Would you know how to write to the beginning of the webpack bundled file through settings in webpack config?

**Comment by martyphee** [comment]
I have a work around for anyone interested.

`cd client`
`rm -rf node_modules`
`npm install`
`npm shrinkwrap`

Edit shrinkwrap.json.  Update process like this.

**Comment by martyphee** [comment]
I have a work around for anyone interested.

`cd client`
`rm -rf node_modules`
`npm install`
`npm shrinkwrap`

Edit shrinkwrap.json.  Update process like this.

```
"process": {
    "version": "0.11.3",
    "from": "process@>=0.11.0 <0.12.0",
    "resolved": "http://registry.npmjs.org/process/-/process-0.11.3.tgz"
}
```

**Comment by martyphee** [comment]
@justin808 I have a PR out there to polyFill and I have a PR for our codebase to bump it to 6.x of `react_on_rails`.

**Comment by justin808** [comment]
I'm reviewing. Tests would be a bonus.

<details><summary><i>Previously, martyphee (Marty Phee) wrote…</i></summary>
> @justin808 I have a PR out there to polyFill and I have a PR for our codebase to bump it to 6.x of `react_on_rails`. 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/451#-:-KK0Hd3us77sPyN0xOTe:-2003673541)*

**Comment by justin808** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/react_on_rails/server_rendering_pool/exec.rb, line 137 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/451#-KK0HmyBuejXxiqA7AzH:-KK0HmyBuejXxiqA7AzI:1997892065) ([raw file](https://github.com/shakacode/react_on_rails/blob/2318c9a661b2f3a6fa7e563c941a8ff10c19eb2e/lib/react_on_rails/server_rendering_pool/exec.rb#L137)):*
> ```Ruby
> 
> function clearTimeout() {
>   #{undefined_for_exec_js_logging('setTimeout')}
> ```

should be 'clearTimeout'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/451)*

**Comment by justin808** [comment]
One comment.

<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> I'm reviewing. Tests would be a bonus.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/451#-:-KK0IPy5cmcutC8pHB_N:-2016547890)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/451)*

**Comment by martyphee** [comment]
Just pushed update.  Sorry about that.

**Comment by justin808** [comment]
@martyphee Please update the Changelog.md per the examples, and I'll merge and release 6.0.4.

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6560685)
> 
> Coverage remained the same at 82.305% when pulling **5c971652f79a16ddacc065c41a31a0b47edbcc4d on martyphee:add-clearTimeout-polyfill** into **3fe05f917145876e62846d9689c4ae82778f8c6b on shakacode:master**.
> 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/451#-:-KK0uL2yxbuADI5LWxmT:1216109573)*

**Comment by martyphee** [comment]
Done

**Comment by justin808** [comment]
Please see the comment and squash to one commit and I'll release. Thanks!

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6563543)
> 
> Coverage remained the same at 82.305% when pulling **173176ebc9790581e4df5061319bd664262c1ca9 on martyphee:add-clearTimeout-polyfill** into **3fe05f917145876e62846d9689c4ae82778f8c6b on shakacode:master**.
> 
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 8 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/451#-KK5megs8X-Sj7tZCzRe:-KK5megtct896oQSZjTH:-2137274906) ([raw file](https://github.com/shakacode/react_on_rails/blob/173176ebc9790581e4df5061319bd664262c1ca9/CHANGELOG.md#L8)):*
> ```Markdown
> ## [Unreleased]
> 
> ## [6.0.4]
> ```

See the bottom of the file for where this goes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/451#-:-KK5mhPFIusKhb4Hc-w8:582593732)*

**Comment by justin808** [comment]
:lgtm: Thanks @martyphee 

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6571617)
> 
> Coverage remained the same at 82.305% when pulling **ec2e83cb160197c7fbcf68b5ea03574be686def8 on martyphee:add-clearTimeout-polyfill** into **3fe05f917145876e62846d9689c4ae82778f8c6b on shakacode:master**.
> 
</details>


---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/451#-:-KK9u3t42NPNlUcZ67Wz:2003191917)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/451)*

**Pull request merged**
