### PR TITLE
Update rails-assets-relative-paths.md

### PR DESCRIPTION
**Pull request by justin808**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/754)

### CODE REVIEW

**Comment by justin808** [comment]
@tmobaird Please see my changes. Does this look right. We want to move all the docs to Webpack v2.

**Comment by tmobaird** [comment]
This PR looks great! I added a couple comments on some very minor things.

I agree that the docs should all use the Webpack v2 syntax (forgot to do that in my initial creation of this doc). 
 

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[docs/additional-reading/rails-assets-relative-paths.md, line 160 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/754#-KedWFtLtsZVgdmORsC5:-KedWFtLtsZVgdmORsC6:b-tm1z8y) ([raw file](https://github.com/shakacode/react_on_rails/blob/4df99740be4e51382d6f8d40899ae772e9633284/docs/additional-reading/rails-assets-relative-paths.md#L160)):*
> ```Markdown
>   ],
>   module: {
>     loaders: [
> ```

Would this be better as `rules` instead? I think webpack 2 changed this to be `rules` by default, but still works as `loaders` for now

---

*[docs/additional-reading/rails-assets-relative-paths.md, line 173 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/754#-KedXQe6xG0HC7dRF0DL:-KedXQe74fAVAXtqWFRe:b-broplw) ([raw file](https://github.com/shakacode/react_on_rails/blob/4df99740be4e51382d6f8d40899ae772e9633284/docs/additional-reading/rails-assets-relative-paths.md#L173)):*
> ```Markdown
>             shim: 'es5-shim/es5-shim',
>             sham: 'es5-shim/es5-sham',
>           },
> ```

You'll need another closing bracket after this line to end the `use` block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/754#-:-KedXzQrmKRIKTaxRwo9:bypipu)*

**Comment by tmobaird** [comment]
Looks awesome @justin808! 👍 I'll keep checking the text of the doc for anything Webpack v1 specific as well.

**Comment by justin808** [comment]
Thanks @tmobaird for the review. I made your suggested changes. I'll merge. Please feel free to submit another PR for anything I missed.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/754#-:-Keg0MEOUkugJt__1Kfa:bjq36fi)*

**Pull request merged**
