### PR TITLE
Integration tests [WIP]

### PR DESCRIPTION
**Pull request by mapreal19**

### CODE REVIEW

**Comment by mapreal19** [comment]
@dylangrafmyre could you help me with the setup? I've tried what is on the tutorial, but I'm not sure if I'm missing something

**Comment by dylangrafmyre** [comment]
@mapreal19 can you please make a branch under this repo with these changes? That way I can pull down the branch to test the issues you are experiencing. You are a collaborator on the repo. Thanks!

**Comment by mapreal19** [comment]
@dylangrafmyre is failing only on CI.

Also for pulling you could install [git extras](https://github.com/tj/git-extras/blob/master/Installation.md) and just do `git pr 45` ;)

**Comment by dylangrafmyre** [comment]
@mapreal19 Here is the fix:
https://github.com/shakacode/react_on_rails/tree/pr/45

**Comment by mapreal19** [comment]
thanks @dylangrafmyre! I'll close this and then we can continue to work on that branch

**Pull request closed without merging**
