### PR TITLE
Sync Integration Specs with React on Rails Pro

### PR DESCRIPTION
**Pull request by Judahmeek**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1382)

### CODE REVIEW

**Review by Judahmeek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1382)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @Judahmeek)

___
*[spec/dummy/spec/system/integration_spec.rb, line 214 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1382#-Mh02Cub6c1TH6Ek8qaC:-Mh02Cub6c1TH6Ek8qaD:b-7m3071) ([raw file](https://github.com/shakacode/react_on_rails/blob/64b3b1486e3610380a3cd797428b13ceab4e9fa6/spec/dummy/spec/system/integration_spec.rb#L214)):*
> ```Ruby
> end
> 
> describe "Render-Function returns renderedHtml as an object with additional HTML markups", :js, type: :system do
> ```

Adding :js here was making the `with disabled JS` & `with enabled JS` examples both run with :selenium_headless_chrome & enabled JS.
___
*[spec/dummy/spec/system/integration_spec.rb, line 248 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1382#-Mh021jx-Mz_hXid2C2Z:-Mh021jy0w_tA6HdtmTZ:b-bba8k3) ([raw file](https://github.com/shakacode/react_on_rails/blob/7321bcc53e34963f8d2d9f4a6cbc4ca54e917273/spec/dummy/spec/system/integration_spec.rb#L248)):*
> ```Ruby
>   end
> 
>   describe "with disabled JS", driver: :rack_test do
> ```

Github Actions is breaking on this example, which wasn't properly being tested before.

I can either spend extra time trying to debug the different in the environment between Github Actions & CircleCI (which is passing) or we can make the `Main` tests for Github Actions not `required`

**Review by justin808 — CHANGES_REQUESTED** [review]
LGTM

> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1382#-:-Mh708Kn3iBsufl6-2tH:bb6ywmx)* status: all files reviewed, 3 unresolved discussions (waiting on @Judahmeek)

___
*[-- commits, line 20 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1382#-Mh6y4g9B1HMWmfWTsJ8:-Mh6y4gA93sPAYdkDjPv:bc3w90l) ([raw file](https://github.com/shakacode/react_on_rails/blob/4a266bc99a92b57ab2e0551b05f3df8f48467910/-- commits#L20)):*
What is this Commits file? should it be in gitignore?
___
*[spec/dummy/spec/system/integration_spec.rb, line 214 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1382#-Mh02Cub6c1TH6Ek8qaC:-Mh706fd7wd2hr_CXCVz:b32w0x) ([raw file](https://github.com/shakacode/react_on_rails/blob/64b3b1486e3610380a3cd797428b13ceab4e9fa6/spec/dummy/spec/system/integration_spec.rb#L214)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

Adding :js here was making the `with disabled JS` & `with enabled JS` examples both run with :selenium_headless_chrome & enabled JS.
</blockquote></details>

OK
___
*[spec/dummy/spec/system/integration_spec.rb, line 248 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1382#-Mh021jx-Mz_hXid2C2Z:-Mh7-i110z3Brmcd5vZH:b5cs6zg) ([raw file](https://github.com/shakacode/react_on_rails/blob/7321bcc53e34963f8d2d9f4a6cbc4ca54e917273/spec/dummy/spec/system/integration_spec.rb#L248)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

Github Actions is breaking on this example, which wasn't properly being tested before.

I can either spend extra time trying to debug the different in the environment between Github Actions & CircleCI (which is passing) or we can make the `Main` tests for Github Actions not `required`
</blockquote></details>

Is this working on master?

If we can check this manually, I'm OK with skipping the test for now.

Please mark the test as skipped rather than deleted.

**Review by Judahmeek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1382)* status: all files reviewed, 1 unresolved discussion (waiting on @justin808)

___
*[-- commits, line 20 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1382#-Mh6y4g9B1HMWmfWTsJ8:-MhHKBYT7jTr68lbu-z2:b-xy3biv) ([raw file](https://github.com/shakacode/react_on_rails/blob/4a266bc99a92b57ab2e0551b05f3df8f48467910/-- commits#L20)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

What is this Commits file? should it be in gitignore?
</blockquote></details>

This file doesn't exist in the list of files changed on Github. This appears to be a new Reviewable feature.
___
*[spec/dummy/spec/system/integration_spec.rb, line 248 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1382#-Mh021jx-Mz_hXid2C2Z:-MhHKO3b9C21kBx2sWsr:b-l1gldz) ([raw file](https://github.com/shakacode/react_on_rails/blob/7321bcc53e34963f8d2d9f4a6cbc4ca54e917273/spec/dummy/spec/system/integration_spec.rb#L248)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Is this working on master?

If we can check this manually, I'm OK with skipping the test for now.

Please mark the test as skipped rather than deleted.
</blockquote></details>

I resolved this issue by modifying `rails_helper` so that I could actually disable JS through the use of `:rack_test`

**Review by justin808 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Judahmeek)

**Pull request merged**
