### PR TITLE
Pass-through JS error to client

### PR DESCRIPTION
**Pull request by dzirtusss**
Pass-through simple version of #485

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/521)

### CODE REVIEW

**Comment by dzirtusss** [comment]
@justin808 @robwise Please look - this is the most minimalist intrusion into error I can imagine. We just update the message and rethrow same error with all same parameters, incl. stacktrace

**Comment by justin808** [comment]
Looking good.

@robwise Take a look. 

@samnang @robwise I don't see any worthwhile way to test this. I think we can skip a new test for this change.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/src/handleError.js, line 38 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/521#-KPRW-rh_gQ8QV90iLqj:-KPRW-rijqkbRYgyDLZ_:ba0qqz8) ([raw file](https://github.com/shakacode/react_on_rails/blob/048c8d8522fbc46930bc68d7cf508c1b7ed7db72/node_package/src/handleError.js#L38)):*
> ```JavaScript
> }
> 
> export default (options) => {
> ```

const handleError = (option) => {
// blah blah
}

export default handleError;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/521#-:-KPRWL-rkkGV6g2KPhHr:b-t0jgta)*

**Comment by robwise** [comment]
I think this is a good compromise. 

Also, if we are going to be modifying original error messages like this, we should tell the user who is doing it. So `message` should be like `ReactOnRails encountered an error while rendering component: ${name}. Original message: ${e.message}`

Or something

**Comment by justin808** [comment]
@dzirtusss Let's apply Rob's suggestion and call it good!

**Comment by dzirtusss** [comment]
Done. What about `handleGeneratorFunctionIssue`? Keep?

**Comment by justin808** [comment]
:lgtm:

(Yes keep)

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/521#-:-KPXBYQxF4Wq3fsht_qm:b3zksus)*

**Comment by justin808** [comment]
I'll merge once CI passes!

**Comment by justin808** [comment]
@dzirtusss Can you please update the CHANGELOG.md.

**Comment by squaresurf** [comment]
:clap:

**Pull request merged**
