### PR TITLE
RFC: Add options block so that webpack 2.6 won't complain

### PR DESCRIPTION
**Pull request by ened**
Also, I had to include `autoprefixer` in the list of plugins to get it working here.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/873)

### CODE REVIEW

**Comment by justin808** [comment]
@ened can you paste the error you see without this? If you want to upgrade the webpack (and other library versions), then please put all into this PR.

**Comment by ened** [comment]
@justin808 - in the end, this might not even be web pack related, but is an artifact (during previous merges). I noticed it worked with the `spec/dummy/Procfile.hot` right away, which had this fixed.

Typical error messages are: 
> Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in ...

**Comment by justin808** [comment]
@ened What shall we do with this PR?

**Comment by justin808** [comment]
@ened Please get back to me on this one and let me know if we should re-open this PR.

**Pull request closed without merging**
