### PR TITLE
Fix HMR

### PR DESCRIPTION
**Pull request by Judahmeek**
So I've got hot-reloading working on `spec/dummy`, just not if both `ReduxApp` and `ReduxSharedStoreApp` are imported & registered (hot reloading works on both of them, just not both of them at once). I'm still working out why, but my assumption is that it has something to do with the dependency paths.

I also noticed that hot updates to ReduxSharedStoreApp would only apply to the second app on http://0.0.0.0:3000/client_side_hello_world_shared_store), I'm focusing on Egghead's lessoning editing form draft.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/865)

### CODE REVIEW

**Comment by justin808** [comment]
couple tiny thing, then pass CI and I will merge!

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[spec/dummy/client/package.json, line 38 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/865#-Km0JL4V-ATMmE1zPYVb:-Km0JL4V-ATMmE1zPYVc:b-7pejcb) ([raw file](https://github.com/shakacode/react_on_rails/blob/75d401dcaa265a8a759e50ac0642a3e282acd395/spec/dummy/client/package.json#L38)):*
> ```JSON
>     "react-helmet": "^5.0.3",
>     "react-hot-loader": "^3.0.0-beta.6",
>     "react-on-rails": "file:../../../",
> ```

don't change that -- we use a relative path via yarn link

---

*[spec/dummy/client/server-rails-hot.js, line 16 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/865#-Km0Jcl0bHOhEMpJJCwc:-Km0Jcl0bHOhEMpJJCwd:bse3ztw) ([raw file](https://github.com/shakacode/react_on_rails/blob/75d401dcaa265a8a759e50ac0642a3e282acd395/spec/dummy/client/server-rails-hot.js#L16)):*
> ```JavaScript
> // 3. Start up `foreman start -f Procfile.hot` to start both Rails and the hot reload server.
> 
> const webpack = require('webpack');
> ```

changed b/c babelrc must be modules false

---

*[spec/dummy/client/webpack.client.rails.hot.config.js, line 16 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/865#-Km0K-axRYXTXwIK5oc0:-Km0K-axRYXTXwIK5oc1:bu1v49z) ([raw file](https://github.com/shakacode/react_on_rails/blob/75d401dcaa265a8a759e50ac0642a3e282acd395/spec/dummy/client/webpack.client.rails.hot.config.js#L16)):*
> ```JavaScript
> module.exports = merge.strategy(
>   {
>     entry: 'prepend'
> ```

worth commenting that this is b/c react-hot-loader needs to be first

---

*[spec/dummy/client/webpack.client.rails.hot.config.js, line 106 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/865#-Km0KHrlYTYl8X9CzMKD:-Km0KHrlYTYl8X9CzMKE:bqd3lcz) ([raw file](https://github.com/shakacode/react_on_rails/blob/75d401dcaa265a8a759e50ac0642a3e282acd395/spec/dummy/client/webpack.client.rails.hot.config.js#L106)):*
> ```JavaScript
>   plugins: [
>     new webpack.HotModuleReplacementPlugin(),
>     new webpack.NamedModulesPlugin(),
> ```

worth commenting on why if you want to leave in

good if it helps to troubleshoot!

---

*[spec/dummy/client/app/startup/ClientReduxApp.jsx, line 11 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/865#-Km0KbwXGYJD4MlIKOAW:-Km0KbwXGYJD4MlIKOAX:bqad2av) ([raw file](https://github.com/shakacode/react_on_rails/blob/75d401dcaa265a8a759e50ac0642a3e282acd395/spec/dummy/client/app/startup/ClientReduxApp.jsx#L11)):*
> ```JSX
> import { AppContainer } from "react-hot-loader";
> import { render } from "react-dom";
> import consoleErrorReporter from "lib/consoleErrorReporter";
> ```

might want to remove

---

*[spec/dummy/client/lib/renderApp.js, line 1 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/865#-Km0Mkt8yyh2lJamQ-8V:-Km0Mkt8yyh2lJamQ-8W:b-jjfq6u) ([raw file](https://github.com/shakacode/react_on_rails/blob/75d401dcaa265a8a759e50ac0642a3e282acd395/spec/dummy/client/lib/renderApp.js#L1)):*
> ```JavaScript
> import React from 'react';
> ```

remove file if not used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/865#-:-Km0NIQN_13kFpTwgcwU:bsfytty)*

**Comment by justin808** [comment]
:lgtm:

Looks ready to merge!

---

Reviewed 4 of 7 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/865#-:-Km5ZpsmIhj0W0A_s6Mx:b-z2lnf0)*

**Comment by jeffling** [comment]
@justin808 Do you have any advice on setting up hot reload if we have around 20 entry points? (we use react only for dynamic parts of our page and templates for the rest.

**Comment by justin808** [comment]
@Judahmeek can tell @jeffling.

**Pull request merged**
