### PR TITLE
Make sure request's original_url is UTF-8

### PR DESCRIPTION
**Pull request by lucke84**
This situation can occur in browsers that do not encode the entire URL as UTF-8,
mostly on the Windows platform (IE11 and lower). When this happens, the encoding
string is ASCII-8BIT, which generates an error if the URL contains characters
from non-latin languages.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/527)

### CODE REVIEW

**Comment by justin808** [comment]
Please pull in latest changes from master and CI should pass.

**Comment by lucke84** [comment]
Done it. I've squashed the branch while merging, hope it's right (cause this is becoming painful :D). BTW I don't get why my branch would fail running the testing for a change in master.

**Comment by justin808** [comment]
@lucke84 you should have only *ONE* commit here: https://github.com/shakacode/react_on_rails/pull/527/commits

```
git checkout check_encoding_of_request_original_url_to_be_utf8
git reset --hard bb0eb2f59df082f10d5346c6f5e5dce96d3d3fdd
git fetch
git rebase origin/master
git push -f
```

try that

**Comment by lucke84** [comment]
Done. Sorry for the mess with the commits, I'm still getting acquainted with rebasing properly. Thanks for the help :)

**Comment by justin808** [comment]
np @lucke84 

once CI passes, I'll merge and ship 6.1

**Pull request merged**
