### PR TITLE
 Improve README structure

### PR DESCRIPTION
**Pull request by rodrigobdz**
Followed the recommendations from the [Github Guides](https://guides.github.com/features/wikis/#Formatting-a-readme).
PR for Issue [#941](https://github.com/shakacode/react_on_rails/issues/941).

I read and tried to follow the [instructions](https://github.com/shakacode/react_on_rails/blob/383de73e76e0347b9d58508e63f937cfbca6ca40/CONTRIBUTING.md#doc-changes) on creating relative links to markdown files for the [gitbook](https://github.com/shakacode/react_on_rails/issues/941#issuecomment-331261990). Let me know if I missed something.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1084)

### CODE REVIEW

**Comment by rodrigobdz** [comment]
@justin808 @Judahmeek Basically, what I did was to divide the documentation into smaller chunks to improve its readability.

From the [Github Guides](https://guides.github.com/features/wikis/#Formatting-a-readme):
> Your README should contain only the necessary information for developers to get started using and contributing to your project.

I also kept the sales pitch in the README.

**Comment by justin808** [comment]
@rodrigobdz can you please rebase on top of master.

**Comment by rodrigobdz** [comment]
@justin808 I just merged the latest [master](https://github.com/shakacode/react_on_rails/tree/master) changes into the PR.

**Comment by rodrigobdz** [comment]
Closing in favor of PR #1092.

**Pull request closed without merging**
