### PR TITLE
Use <script type="application/json"> for props and store

### PR DESCRIPTION
**Pull request by squadette**
See discussion in https://github.com/shakacode/react_on_rails/pull/660

Build passing: https://travis-ci.org/squadette/react_on_rails/builds/210095090

Thank you @eliaslopezgt for initial implementation.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/760)

### CODE REVIEW

**Comment by justin808** [comment]
@squadette What's pending here?

**Comment by squadette** [comment]
Nothing, I guess it's ready for code review, fixes (if any) and merge.

**Comment by justin808** [comment]
:lgtm: @squadette Really awesome work.

My main concerns

1. That we changed a test that uses a JSON string to a  hash. We need to support both. And be sure no XSS either way.
2. Why did a call to getAttributes change to attributes[key].value ?
3. Might need to deprecate the removal of a config value if this causes a crash.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[app/helpers/react_on_rails_helper.rb, line 226 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAS06uT7GuDBox_f_G:-KfAS06uT7GuDBox_f_H:b7um1b6) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/app/helpers/react_on_rails_helper.rb#L226)):*
> ```Ruby
> 
>   def json_safe_and_pretty(something)
>     if Rails.env.development?
> ```

Should this include Rails.env.test?

@robwise @alexfedoseev Any need to see the JSON look pretty in tests?

---

*[lib/react_on_rails/configuration.rb, line 128 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfATWvvXYKzch9GGZZi:-KfATWvvXYKzch9GGZZj:b-apu58n) ([raw file](https://github.com/shakacode/react_on_rails/blob/300df6f4f8a39818b4dd90150ee77ec9176fc089/lib/react_on_rails/configuration.rb#L128)):*
> ```Ruby
>       self.trace = trace.nil? ? Rails.env.development? : trace
>       self.raise_on_prerender_error = raise_on_prerender_error
>       self.skip_display_none = skip_display_none
> ```

Removing this may result in an error if this value is being set. 

Please set this value in the react_on_rails.rb and see if there's a crash.

If so, let's leave this around with a deprecation message, and we'll remove with version 7.0.

---

*[node_package/src/clientStartup.js, line 50 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAVFUD4yrp_l975qfq:-KfAVFUD4yrp_l975qfr:bhimhn6) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/node_package/src/clientStartup.js#L50)):*
> ```JavaScript
> 
> function forEachComponent(fn, railsContext) {
>   forEach(fn, 'js-react-on-rails-component', railsContext);
> ```

can we keep this a const at the top of the file?

---

*[node_package/src/clientStartup.js, line 55 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAV9DgsH2gEH-bR4Y6:-KfAV9DgsH2gEH-bR4Y7:b-263sjg) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/node_package/src/clientStartup.js#L55)):*
> ```JavaScript
> function initializeStore(el, railsContext) {
>   const context = findContext();
>   const name = el.attributes['data-js-react-on-rails-store'].value;
> ```

how is el.attributes different than getAttribute?

---

*[node_package/src/clientStartup.js, line 63 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAVUruc5BHqpxB_D2b:-KfAVUruc5BHqpxB_D2c:b-x4oz4h) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/node_package/src/clientStartup.js#L63)):*
> ```JavaScript
> 
> function forEachStore(railsContext) {
>   forEachByAttribute(initializeStore, 'data-js-react-on-rails-store', railsContext);
> ```

should we DRY up 'data-js-react-on-rails-store'?

---

*[spec/dummy/app/views/pages/server_side_hello_world_with_options.html.erb, line 30 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAWQgAAj5lm3ifpyy1:-KfAWQgAAj5lm3ifpyy2:bhwzzky) ([raw file](https://github.com/shakacode/react_on_rails/blob/300df6f4f8a39818b4dd90150ee77ec9176fc089/spec/dummy/app/views/pages/server_side_hello_world_with_options.html.erb#L30)):*
> ```erb
> <pre>
> <%%= react_component("HelloWorld",
>                     props: @app_props_server_render.to_json,
> ```

Sometimes we're passed props that are already a JSON string. Sometimes we're given props that are a Hash.

We need to be sure we handle both cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-:-KfAXFvRW26xfz_dSQQI:b-e9f705)*

**Comment by eliaslopezgt** [comment]
👍  amazing work

**Comment by squadette** [comment]
Thank you.  I've fixed two things, will fix the rest later.

---

Review status: 15 of 17 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[app/helpers/react_on_rails_helper.rb, line 226 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAS06uT7GuDBox_f_G:-KfO8CbnpTYlbIGAQLYY:blu3c3i) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/app/helpers/react_on_rails_helper.rb#L226)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Should this include Rails.env.test?

@robwise @alexfedoseev Any need to see the JSON look pretty in tests?
</blockquote></details>

Rewrote it to be pretty everywhere in non-production.

---

*[node_package/src/clientStartup.js, line 50 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAVFUD4yrp_l975qfq:-KfO8SA2-g7ZuuMct5ZV:b7ayri1) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/node_package/src/clientStartup.js#L50)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

can we keep this a const at the top of the file?
</blockquote></details>

I personally hate single-use constants because they inhibit grepping.  I would prefer to leave it as, but of course I can change it.

---

*[node_package/src/clientStartup.js, line 55 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAV9DgsH2gEH-bR4Y6:-KfOADDN2GoJSsEOmMHB:bs05957) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/node_package/src/clientStartup.js#L55)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

how is el.attributes different than getAttribute?
</blockquote></details>

getAttribute() is better, because it handles attributes which are not present.  Fixed, thank you.

---

*[node_package/src/clientStartup.js, line 63 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAVUruc5BHqpxB_D2b:-KfOAl1ePw7c45_NtroT:b-9xymbp) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/node_package/src/clientStartup.js#L63)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

should we DRY up 'data-js-react-on-rails-store'?
</blockquote></details>

I don't see a lot of value in micro-DRY.  How would you suggest to change it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-:-KfOAxV-JJpO_RdUy4sH:bfy2wq0)*

**Comment by justin808** [comment]
Looking good! What's pending?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[node_package/src/clientStartup.js, line 50 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAVFUD4yrp_l975qfq:-KfOCL-CvcOfFXHNnUYG:b-n132pa) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/node_package/src/clientStartup.js#L50)):*
<details><summary><i>Previously, squadette (Alexey Mahotkin) wrote…</i></summary><blockquote>

I personally hate single-use constants because they inhibit grepping.  I would prefer to leave it as, but of course I can change it.
</blockquote></details>

OK -- for single use. Keep as is. Name is self explanatory.

---

*[node_package/src/clientStartup.js, line 63 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-KfAVUruc5BHqpxB_D2b:-KfOG4HRa84pCjYvUi-X:b-wwji41) ([raw file](https://github.com/shakacode/react_on_rails/blob/f835c5f6aaffe4f2ccbc90b596fe956190615e5f/node_package/src/clientStartup.js#L63)):*
<details><summary><i>Previously, squadette (Alexey Mahotkin) wrote…</i></summary><blockquote>

I don't see a lot of value in micro-DRY.  How would you suggest to change it?
</blockquote></details>

If constant value is in two places, then declare at top of file as `const`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/760#-:-KfOGcN1aF3KqfWWuAtr:b-7lqupy)*

**Comment by justin808** [comment]
@squadette Do you need any help from me on this one? I want to get this one shipped, and to then get started on v7 with Webpacker.

**Comment by justin808** [comment]
@squadette We've got to get this one wrapped up. Any volunteers to get this one across the finish line?

**Comment by justin808** [comment]
Work is now going into #775. @squadette Thanks for your help so far, and please help us review #775.

**Pull request closed without merging**
