### PR TITLE
Linters are not the default

### PR DESCRIPTION
**Pull request by justin808**
Now you have to specify --linters or -L to add linters

### CODE REVIEW

**Comment by robwise** [comment]
Side note, having to make the changes in both `package.json`s kind of highlights how un-DRY it is to have one for non-redux and one for redux. Maybe I should just use the same ERB conditionals technique for those packages that differ between the two and that way we can have just a single `client/package.json` template.

**Comment by justin808** [comment]
@robwise I just rebased down to one commit...

**Comment by justin808** [comment]
@samnang @alexfedoseev @mapreal19 @geoffevason @dylangrafmyre @robwise We just lost a bunch of comments after a rebase and push force.

This is making me think that http://reviewable.io might be reasonable to try out for our public and internal projects. 

Here's a list: https://www.quora.com/What-are-the-best-code-review-tools

**Comment by rupurt** [comment]
@justin808 you may already know this but GitHub now allows you to configure [protected branches](https://github.com/blog/2051-protected-branches-and-required-status-checks) to disable things like force push.

**Comment by justin808** [comment]
@rupurt Yes, saw that a month or two ago. I'll set that up. force-push should be disabled for master.

**Comment by justin808** [comment]
@robwise Yes, I suggest 100% that we use a ERB partial for parts like this!

**Comment by justin808** [comment]
Switching gears.

Turning linters back on for JS (stuff in /client) and having option `--ruby-linters` for turning on ruby linters and the default for that is false. 

CC: @robwise

**Comment by mapreal19** [comment]
:+1: for reviewable!

**Pull request merged**
