### PR TITLE
Use redux in generated hello world example

### PR DESCRIPTION
**Pull request by lewaabahmad**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1006)

### CODE REVIEW

**Comment by justin808** [comment]
:lgtm:

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 36 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/1006#-L2P2zOAgTFabod59x1y:-L2P2zOAgTFabod59x1z:bi5on7j) ([raw file](https://github.com/shakacode/react_on_rails/blob/8f556082fbb3cae96cad3f27817b7553cf4df6a4/.gitignore#L36)):*
> ```
> .DS_Store
> *.swp
> *.swo
> ```

this probably doesn't need to be part of the of the .gitignore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/1006#-:-L2P35zUptRvnQTrf9mf:b9benhj)*

**Comment by justin808** [comment]
Let's remove the .gitignore change and I'll merge and publish a new version.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/1006#-:-L2P3FAQK6-WiUEWoYl9:b-swl12b)*

**Comment by justin808** [comment]
@lewaabahmad please ping me when you remove the .gitignore changes. Or let me know why they are needed.

**Comment by justin808** [comment]
@lewaabahmad Can you please let me know about the .gitignore change?

**Comment by justin808** [comment]
@lewaabahmad Can you please let me know about the .gitignore change?

**Comment by justin808** [comment]
@lewaabahmad Can you please let me know about the .gitignore change?

**Comment by justin808** [comment]
See PR #1019

**Comment by lewaabahmad** [comment]
@justin808 Sorry!!! I really didn't see those notifications! Was just checking the issue and saw it was merged. 

I added those because of Vim! Vim creates those files to make edits! 

Again, my most sincere apologies! Glad this was good! 👍

**Pull request closed without merging**
