### PR TITLE
Fix no-turbolinks ci

### PR DESCRIPTION
**Pull request by justin808**
Root cause of failures on CI might be that if gem turbolinks is installed, then we don't run the handlers for no-turbolinks.

However, that should only be affected by requiring of turbolinks.

Maybe we should change:

1. Don't worry if the Gem turbolinks is installed.
2. Only check the JS side if turbolinks is running.

[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/244)

### CODE REVIEW

**Comment by justin808** [comment]
@robwise You might want to refactor this a tiny bit.

**Comment by robwise** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[rakelib/dummy_apps.rake, line 11 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-K9G5xz0kdls86f43oHE:-K9G5xz1RcpXZ5VU_-Ri:-130001938) ([raw file](https://github.com/shakacode/react_on_rails/blob/102ad4b6694c657c7a77c5dd1d7ee73ac95f1031/rakelib/dummy_apps.rake#L11)):*
there's a helper in task_helpers.rb that we should use for this to keep it DRY, not sure why I didn't use that in the first place

---

*[rakelib/run_rspec.rake, line 26 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-K9G6Jds3mozspppdOWk:-K9G6Jds3mozspppdOWl:-850086708) ([raw file](https://github.com/shakacode/react_on_rails/blob/102ad4b6694c657c7a77c5dd1d7ee73ac95f1031/rakelib/run_rspec.rake#L26)):*
why are we bundle installing after we run the tests?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[rakelib/dummy_apps.rake, line 11 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-K9G5xz0kdls86f43oHE:-K9G9CQa40ZXyNesRKtf:-1765646278) ([raw file](https://github.com/shakacode/react_on_rails/blob/102ad4b6694c657c7a77c5dd1d7ee73ac95f1031/rakelib/dummy_apps.rake#L11)):*
agree!

---

*[rakelib/run_rspec.rake, line 26 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-K9G6Jds3mozspppdOWk:-K9G96VrSHk36tseoLWr:-1467593531) ([raw file](https://github.com/shakacode/react_on_rails/blob/102ad4b6694c657c7a77c5dd1d7ee73ac95f1031/rakelib/run_rspec.rake#L26)):*
return to prior state or else gemfile.lock is dirty

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244)*

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[rakelib/run_rspec.rake, line 26 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-K9G6Jds3mozspppdOWk:-K9G9TrsJipL5lP_gbVM:1252951868) ([raw file](https://github.com/shakacode/react_on_rails/blob/102ad4b6694c657c7a77c5dd1d7ee73ac95f1031/rakelib/run_rspec.rake#L26)):*
ah, makes sense! I think this calls for a comment here because otherwise we might forget or someone else might not know etc.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244)*

**Comment by justin808** [comment]
Debugging details:

https://github.com/shakacode/react_on_rails/issues/246#issuecomment-177457388

**Comment by justin808** [comment]
https://github.com/rackt/redux/commit/e2e14d26f09ca729ae0555442f50fcfc45bfb423#diff-1fdf421c05c1140f6d71444ea2b27638

**Comment by justin808** [comment]
See https://github.com/rackt/redux/issues/1335

**Comment by robwise** [comment]
Reviewed 8 of 8 files at r2, 1 of 4 files at r4, 4 of 4 files at r5.
Review status: 17 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[rakelib/dummy_apps.rake, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-K9ON0N569YBnReO9WVZ:-K9ON0N569YBnReO9WV_:-256747344) ([raw file](https://github.com/shakacode/react_on_rails/blob/102ad4b6694c657c7a77c5dd1d7ee73ac95f1031/rakelib/dummy_apps.rake#L10)):*
can we put this back now or this was breaking CI also?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244)*

**Comment by robwise** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244)*

**Comment by robwise** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244)*

**Comment by justin808** [comment]
👍😎

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-:-K9Pl4sm0oAn073c3M4g:-1915357274)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[rakelib/dummy_apps.rake, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-K9ON0N569YBnReO9WVZ:-K9Qrqx7ZZZrBo76D0_I:-1069599577) ([raw file](https://github.com/shakacode/react_on_rails/blob/102ad4b6694c657c7a77c5dd1d7ee73ac95f1031/rakelib/dummy_apps.rake#L10)):*
we just don't need separate bundle install

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244)*

**Comment by alexfedoseev** [comment]
:lgtm_strong: 

---

Review status: 20 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/244#-:-K9QwPrPwT1iCCp8CNVi:-1868698381)*

**Pull request merged**
