### PR TITLE
Adding Rails Assets Relative Paths Doc

### PR DESCRIPTION
**Pull request by tmobaird**
Hey @justin808, here's the doc that references #670. It may be a little wordy, but I tried to make it as detailed as possible (especially about the Webpack config) because I know that is where I struggled the most when figuring this out. Throughout the doc, I used image asset examples just because I felt those are incredibly common and easily understandable. 

I also tried to make recommendations as seldom as possible, but I might have one or two instances of them in there. Let me know if you would like me to remove those.

Feel free to let me know about any other suggestions or concerns you have. Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/750)

### CODE REVIEW

**Comment by justin808** [comment]
@tmobaird AWESOME -- a few minor comments.

Be sure to add your file to: https://github.com/tmobaird/react_on_rails/blob/master/SUMMARY.md

and maybe reference it from: https://github.com/tmobaird/react_on_rails/blob/master/docs/additional-reading/rails-assets.md (and vice versa)

and add a link to this area: https://github.com/tmobaird/react_on_rails/blob/master/README.md#additional-documentation

and FWIW, the symlinking part will be removed for React on Rails 7.0

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/additional-reading/rails-assets-relative-paths.md, line 17 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/750#-KeV35kl--OsvJXRYZJm:-KeV35kl--OsvJXRYZJn:b-u24iln) ([raw file](https://github.com/shakacode/react_on_rails/blob/9a4f036ad1baaa76f92803a4f55699f853d3fe15/docs/additional-reading/rails-assets-relative-paths.md#L17)):*
> ```Markdown
> ## The Solution: The lowdown on Webpack's file-loader, outputPaths and publicPaths
> 
> Webpack's [file-loader](https://github.com/webpack-contrib/file-loader) module is incredibly useful for including assets in your javascript and bundling them so they can live in the assets on your webserver along with your outputted webpack bundle.
> ```

We want to mention how this works with the url-loader which will inline/encode the images into the JS code. The url-loader is typically used with a parameter that images bigger than X go to the file-loader.

---

*[docs/additional-reading/rails-assets-relative-paths.md, line 68 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/750#-KeV4Nkj3VTcddAEwatL:-KeV4Nkj3VTcddAEwatM:bu2ptog) ([raw file](https://github.com/shakacode/react_on_rails/blob/9a4f036ad1baaa76f92803a4f55699f853d3fe15/docs/additional-reading/rails-assets-relative-paths.md#L68)):*
> ```Markdown
> Lastly, we will set the publicPath to our file(s). This will be the endpoint on our rails web server that you can visit to reach the asset (if you don't know how this works, read the [intro](#using-webpack-bundled-assets-with-the-rails-asset-pipeline)). If you've been following the previous steps, you know that we set our outputPath for our assets to be absolute at `app/assets/webpack/webpack-assets/`, which your rails app should end up hosting at `/assets/webpack-assets/file-name+hash.ext` when the server is run.
> 
> Note: _If you're having a hard time figuring out what an asset's path will be on your rails server, simply run `rake assets:precompile` and `cd public/`. The path from there to your file will then be the path/url on your web server to that asset._
> ```

we should definitely add a note to see docs/additional-reading/rails-assets.md

what happens is that Rails will publish whatever's there with ANOTHER hash on top of our hash, and we need to 'de-hash' the double hash, and we do that automatically with symlinks

React on Rails 7.0 is going to use a much more direct approach that avoids the symlink step!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/750#-:-KeV4eu_6r2-fBiDMLfz:blcnx8f)*

**Comment by tmobaird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/additional-reading/rails-assets-relative-paths.md, line 17 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/750#-KeV35kl--OsvJXRYZJm:-KeWtg6iRO587jtp4Pbt:b-r5pnhv) ([raw file](https://github.com/shakacode/react_on_rails/blob/9a4f036ad1baaa76f92803a4f55699f853d3fe15/docs/additional-reading/rails-assets-relative-paths.md#L17)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

We want to mention how this works with the url-loader which will inline/encode the images into the JS code. The url-loader is typically used with a parameter that images bigger than X go to the file-loader.
</blockquote></details>

Done. :+1: 

---

*[docs/additional-reading/rails-assets-relative-paths.md, line 68 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/750#-KeV4Nkj3VTcddAEwatL:-KeWtjgdKjcDOp0OWCBH:b-gnkcov) ([raw file](https://github.com/shakacode/react_on_rails/blob/9a4f036ad1baaa76f92803a4f55699f853d3fe15/docs/additional-reading/rails-assets-relative-paths.md#L68)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

we should definitely add a note to see docs/additional-reading/rails-assets.md

what happens is that Rails will publish whatever's there with ANOTHER hash on top of our hash, and we need to 'de-hash' the double hash, and we do that automatically with symlinks

React on Rails 7.0 is going to use a much more direct approach that avoids the symlink step!
</blockquote></details>

Awesome! Added this :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/750)*

**Comment by tmobaird** [comment]
@justin808 I have made all the changes per the suggestions you made!

**Comment by justin808** [comment]
:lgtm:

Thanks @tmobaird! 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/750#-:-KeXOvMRR2A9nZBE9vrB:b3ey4nz)*

**Pull request merged**
