### PR TITLE
Add ClientPropsExtension support

### PR DESCRIPTION
**Pull request by Judahmeek**
#### The goal of this PR is to add the possibility of handling the props differently for the client and the server:

Changes: 
- Added `client_props_extension` entry to config that accepts a hash with a module for `extensor_name` key and a method for the `method` key
- Allow process the props differently if the configuration is provided and `prerender` is set to `false`

This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1413)

### CODE REVIEW

**Review by justin808 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1413)* status: 1 of 23 files reviewed, 2 unresolved discussions (waiting on @Judahmeek and @justin808)

___
*[docs/guides/configuration.md, line 135 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-Ms8Ksy64-aL9GiH2ox4:-Ms8Ksy73Xwl79mUrUT5:b-a8z0ob) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/docs/guides/configuration.md#L135)):*
Let's rename

`config.rendering_props_extension`

and have one method on there:

`adjust_props_for client_side_hydration`


and document that:

> This configuration allows props to be used for server-side-rendering and stripped out of the props passed for client hydration.


(and adjust as you see fit)
___
*[spec/dummy/Gemfile.lock, line 68 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-Ms8LYF03Lg6tCPwU60w:-Ms8LYF03Lg6tCPwU60x:b-ov57ia) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/spec/dummy/Gemfile.lock#L68)):*
> ```
>       activesupport (= 7.0.0)
>       marcel (~> 1.0)
>       mini_mime (>= 1.1.0)
> ```

Use another PR for Rails 7

**Comment by justin808** [comment]
@Judahmeek can you rebase on master?

**Review by justin808 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 21 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1413)* status: all files reviewed, 7 unresolved discussions (waiting on @Judahmeek)

___
*[docs/guides/configuration.md, line 133 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsbcG1U7Bqmc9Ny_gZ8:-MsbcG1V5gF6lrrAawoK:b-ezwewr) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/docs/guides/configuration.md#L133)):*
> ```Markdown
> 
>   # To handle client-side & server-side props differently,
>   # Add a module with a modify_props method that expects the component's name & props hash
> ```

Let's use:

```
  config.rendering_props_extension = RenderingPropsExtension
```

with method:

```
adjust_props_for client_side_hydration
```
___
*[docs/guides/configuration.md, line 228 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsbcN1G1CTlZiTBpMZV:-MsbcN1G1CTlZiTBpMZW:b-e95r25) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/docs/guides/configuration.md#L228)):*
> ```Markdown
> module ClientPropsExtension
>   # The modify_props method will be called by ReactOnRails::ReactComponent::RenderOptions if config.client_props_extension is defined
>   def self.modify_props(component_name, props)
> ```

see above on the naming
___
*[lib/react_on_rails/configuration.rb, line 54 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-Msbd4Mo90Ciwx_lE-25:-Msbd4Mo90Ciwx_lE-26:b-dojqoc) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/lib/react_on_rails/configuration.rb#L54)):*
> ```Ruby
>                   :i18n_dir, :i18n_yml_dir, :i18n_output_format,
>                   :server_render_method, :random_dom_id,
>                   :same_bundle_for_client_and_server, :client_props_extension
> ```

see above on naming
___
*[lib/react_on_rails/react_component/render_options.rb, line 32 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsbdDpc1l2LJyaQ9WKF:-MsbdDpc1l2LJyaQ9WKG:b-yw093) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/lib/react_on_rails/react_component/render_options.rb#L32)):*
> ```Ruby
>       def client_props
>         props_extension = ReactOnRails.configuration.client_props_extension
>         props_extension ? props_extension.modify_props(react_component_name, props.clone) : props
> ```

if somebody used "" then we'd evaluate as true.

use 

```
props_extension.present?
```
___
*[spec/dummy/config/initializers/react_on_rails.rb, line 18 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsbdUaT9diAFF_yA4hy:-MsbdUaT9diAFF_yA4hz:b-njdvid) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/spec/dummy/config/initializers/react_on_rails.rb#L18)):*
> ```Ruby
> end
> 
> module ClientPropsExtension
> ```

see renaming at top

**Review by Judahmeek — COMMENTED** [review]
Rebased!

> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-:-Msbw16n6v5IAqJ5w4vr:bncveg6)* status: all files reviewed, 7 unresolved discussions (waiting on @justin808)

___
*[docs/guides/configuration.md, line 133 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsbcG1U7Bqmc9Ny_gZ8:-Msbuhpj34ZTqI6wbc85:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/docs/guides/configuration.md#L133)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Let's use:

```
  config.rendering_props_extension = RenderingPropsExtension
```

with method:

```
adjust_props_for client_side_hydration
```
</blockquote></details>

Done.
___
*[docs/guides/configuration.md, line 135 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-Ms8Ksy64-aL9GiH2ox4:-MsbuiSE4KwwxaTh9CyO:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/docs/guides/configuration.md#L135)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Let's rename

`config.rendering_props_extension`

and have one method on there:

`adjust_props_for client_side_hydration`


and document that:

> This configuration allows props to be used for server-side-rendering and stripped out of the props passed for client hydration.


(and adjust as you see fit)




</blockquote></details>

Done.
___
*[docs/guides/configuration.md, line 228 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsbcN1G1CTlZiTBpMZV:-Msbujcs5I-zUISqnAnZ:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/docs/guides/configuration.md#L228)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

see above on the naming
</blockquote></details>

Done.
___
*[lib/react_on_rails/configuration.rb, line 54 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-Msbd4Mo90Ciwx_lE-25:-MsbvGZxAxLTM7zgpmcE:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/lib/react_on_rails/configuration.rb#L54)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

see above on naming
</blockquote></details>

Done.
___
*[lib/react_on_rails/react_component/render_options.rb, line 32 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsbdDpc1l2LJyaQ9WKF:-MsbvoJ-5dxdDGjshYmj:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/lib/react_on_rails/react_component/render_options.rb#L32)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

if somebody used "" then we'd evaluate as true.

use 

```
props_extension.present?
```
</blockquote></details>

Done.
___
*[spec/dummy/Gemfile.lock, line 68 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-Ms8LYF03Lg6tCPwU60w:-MsbvpgUEV5SAn7B0fZP:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/spec/dummy/Gemfile.lock#L68)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Use another PR for Rails 7
</blockquote></details>

Done.
___
*[spec/dummy/config/initializers/react_on_rails.rb, line 18 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsbdUaT9diAFF_yA4hy:-MsbvrGi31iRlHB3HKRf:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/spec/dummy/config/initializers/react_on_rails.rb#L18)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

see renaming at top
</blockquote></details>

Done.

**Comment by justin808** [comment]
@Judahmeek please get CI to pass.

**Review by justin808 — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1413)* status: all files reviewed, 3 unresolved discussions (waiting on @Judahmeek)

___
*[lib/react_on_rails/react_component/render_options.rb, line 32 at r4](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MschUEx0uekzJ09xD0U:-MschUEx0uekzJ09xD0V:bvx3q4j) ([raw file](https://github.com/shakacode/react_on_rails/blob/d8c4ad41d5614f392429fed7d8330430227d4a00/lib/react_on_rails/react_component/render_options.rb#L32)):*
> ```Ruby
>       def client_props
>         props_extension = ReactOnRails.configuration.rendering_props_extension
>         props_extension.present? && props_extension.respond_to?(:adjust_props_for_client_side_hydration) ? props_extension.adjust_props_for_client_side_hydration(react_component_name, props.clone) : props
> ```

if present but not responding, let's raise a helpful message
___
*[spec/dummy/bin/rails, line 3 at r4](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MscheOG17BWcDaOCgP4:-MscheOG17BWcDaOCgP5:bzbbufe) ([raw file](https://github.com/shakacode/react_on_rails/blob/d8c4ad41d5614f392429fed7d8330430227d4a00/spec/dummy/bin/rails#L3)):*
> ```
> #!/usr/bin/env ruby
> APP_PATH = File.expand_path("../config/application", __dir__)
> require_relative "../config/boot"
> ```

how is this related to this PR?
___
*[spec/dummy/client/app/components/HelloWorldProps.jsx, line 8 at r4](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MschkexBvHm3j8or5A0:-MschkexBvHm3j8or5A1:bba7uhv) ([raw file](https://github.com/shakacode/react_on_rails/blob/d8c4ad41d5614f392429fed7d8330430227d4a00/spec/dummy/client/app/components/HelloWorldProps.jsx#L8)):*
> ```JavaScript
> 
>   const [name, setName] = useState(props.helloWorldData.name);
>   // a trick to display a client-only prop value without creating a server/client conflict
> ```

awesome!
___
*[spec/dummy/Gemfile.lock, line 68 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-Ms8LYF03Lg6tCPwU60w:-MschwVo0AjrJzygg6lB:b-vb5352) ([raw file](https://github.com/shakacode/react_on_rails/blob/b01b64117b73b24fa394d96c1ebdc1046d03caff/spec/dummy/Gemfile.lock#L68)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

seems many extraneous files still

**Review by Judahmeek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1413)* status: 17 of 23 files reviewed, 3 unresolved discussions (waiting on @justin808)

___
*[lib/react_on_rails/react_component/render_options.rb, line 32 at r4](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MschUEx0uekzJ09xD0U:-MscpaPN8OgSDadVfqoh:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/d8c4ad41d5614f392429fed7d8330430227d4a00/lib/react_on_rails/react_component/render_options.rb#L32)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

if present but not responding, let's raise a helpful message
</blockquote></details>

Done.
___
*[spec/dummy/client/app/components/HelloWorldProps.jsx, line 8 at r4](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MschkexBvHm3j8or5A0:-MscpbOY7Z7kNTn4cjvS:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/d8c4ad41d5614f392429fed7d8330430227d4a00/spec/dummy/client/app/components/HelloWorldProps.jsx#L8)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

awesome!
</blockquote></details>

Done.
___
*[spec/dummy/bin/rails, line 3 at r4](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MscheOG17BWcDaOCgP4:-MscpdPP01L9h4Hl5FZp:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/d8c4ad41d5614f392429fed7d8330430227d4a00/spec/dummy/bin/rails#L3)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

how is this related to this PR?
</blockquote></details>

Done.

**Review by justin808 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1413)* status: all files reviewed, 1 unresolved discussion (waiting on @Judahmeek)

___
*[lib/react_on_rails/react_component/render_options.rb, line 38 at r5](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsdYfcb0CZ78oOMlz-G:-MsdYfcc2rt4oZ5ibpKP:b-kid6cb) ([raw file](https://github.com/shakacode/react_on_rails/blob/7aaa277917a0e8f8d0b7d3412fd63c845a9e83bf/lib/react_on_rails/react_component/render_options.rb#L38)):*
> ```Ruby
>           end
> 
>           Rails.logger.warn "ReactOnRails: your rendering_props_extension module is missing the "\
> ```

that is warn, not raise

see my comment!

it's too easy to miss something in the logs

**Review by Judahmeek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1413)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @justin808)

___
*[lib/react_on_rails/react_component/render_options.rb, line 38 at r5](https://reviewable.io/reviews/shakacode/react_on_rails/1413#-MsdYfcb0CZ78oOMlz-G:-MshpsgL0hukVUz3LogB:b6p6bkr) ([raw file](https://github.com/shakacode/react_on_rails/blob/7aaa277917a0e8f8d0b7d3412fd63c845a9e83bf/lib/react_on_rails/react_component/render_options.rb#L38)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

that is warn, not raise

see my comment!

it's too easy to miss something in the logs
</blockquote></details>

My bad. In my defence, you said "raise a helpful message", not "throw an error".

**Pull request merged**
