### PR TITLE
Customizable DOM prefix for react components, stores, and contexts

### PR DESCRIPTION
**Pull request by anveo**
Requested in https://github.com/shakacode/react_on_rails/issues/381.

If there was a vulnerability, I suppose this could help stop attackers from fingerprinting what libraries are being used on a site. Some people also like to have control over their markup. If you think this is useful I could improve the documentation and add some tests.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/387)

### CODE REVIEW

**Comment by justin808** [comment]
@anveo Can you please provide specifics on "a vulnerability"?

**Comment by anveo** [comment]
I just meant that the default `js-react-on-rails-` prefix exposes that a site is using react_on_rails. Some people might not like that for aesthetic reasons.

The security angle is kinda contrived, but if there was a vulnerability in react_on_rails, then scanners might search for that tag. Just trying to think of reasons #381 might have been requested for.

**Comment by justin808** [comment]
Let's see what other community members think of this one.

**Comment by justin808** [comment]
I'm leaning toward accepting this one. @thewoolleyman, @samnang, @robwise, @alexfedoseev, thoughts?

**Comment by robwise** [comment]
I don't see the relation to #381, is there someone who needs this? I guess I sort of can see the security through obscurity thing, but you can't change the `data-reactid` attributes that come from vanilla React, right? So you're going to be tipping your hand in that sense anyway?

**Comment by alexfedoseev** [comment]
It makes sense for the case, when somebody found security hole in this gem and scans web for `js-react-on-rails-` to make something bad. I'd call it `wordpress case` lol. With that said I 👍 here.

**Comment by thewoolleyman** [comment]
Sounds reasonable, +1

**Comment by samnang** [comment]
👍

**Comment by justin808** [comment]
@anveo VERY NICE work! I had zero code comments. Exactly as I would have done this.

---

Reviewed 2 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/387#-:-KGKSeIy0d7cxKVqoJSc:1277618924)*

**Comment by justin808** [comment]
@anveo Can you please rebase this fix on top of master and I'll merge.

**Comment by anveo** [comment]
@justin808 I rebased against master, but now 4 additional commits are showing up in this PR. Any ideas on how I can fix that?

**Comment by justin808** [comment]
Your rebase did not go correctly.

We need to squash your commits into one commit.

You can do this a couple ways. It might be easiest to:

0. pull master (be updated)
1. create a new branch "my-branch"
2. git merge --squash "old-branch" into this branch
3. Once you verify, then you can rename the old branch to something else (or delete) and rename this new branch to match the one on this PR. Then do a "push -f".

**Comment by anveo** [comment]
@justin808 Thanks for the advice. I ended up rebasing from upstream/master and force pushing. Seems to have corrected itself.

**Comment by justin808** [comment]
:lgtm_strong: 

Merging if this passes CI.

---

Reviewed 6 of 6 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/387#-:-KGUaqWT3w-DSL_1HGSs:-20569596)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/src/ReactOnRails.js, line 55 \[r8\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/387#-KGVByAOWRJVdIGMQc5r:-KGVByAOWRJVdIGMQc5s:918453978) ([raw file](https://github.com/shakacode/react_on_rails/blob/504a002ce27a656ec94c07069ce1314dd5fa1d9a/node_package/src/ReactOnRails.js#L55)):*
Now that I look at this, I really wonder if there's a way that this can only be in one spot, like the rails config file.

```
domPrefix: string  If specified, it must match ReactOnRails.config.dom_prefix
```

I thought a bit about this and the only sensical alternative would be to:


1. Have a JSON file read by both react_on_rails Ruby and the webpack config.
2. The webpack config can set a value for the global value.
3. The JS code will use the global value rather than the options.

@jbhatab and I were discussing a couple places where we needed both the webpack and the rails to have the same value, such as the name of the server rendering file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/387)*

**Comment by justin808** [comment]
One more comment. The key question is if we could DRY this up so there's no chance of a misconfiguration between the JS and the Rails code.

I think we could with a little bit of work.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/src/ReactOnRails.js, line 55 \[r8\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/387#-KGVByAOWRJVdIGMQc5r:-KGVEqsM-UAaBouYPkY5:-1147821248) ([raw file](https://github.com/shakacode/react_on_rails/blob/504a002ce27a656ec94c07069ce1314dd5fa1d9a/node_package/src/ReactOnRails.js#L55)):*
CC: @alexfedoseev

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/387#-:-KGVEaLtge3JD0F-aO2E:327710951)*

**Comment by justin808** [comment]
Please see https://github.com/shakacode/react_on_rails/blob/master/docs%2Fcontributor-info%2Fcontributing.md. Notably, we need a changelog entry.

I think this OK for now. We can DRY this up later.

**Comment by justin808** [comment]
@anveo @alexfedoseev @jbhatab @thewoolleyman @robwise @aaronvb @martyphee I'm sort of not convinced on the need for this, as the JS on the pages will include the ReactOnRails symbol. Given how easy it is to see that ReactOnRails is defined for a page:

```js
if (ReactOnRails) console.log("ReactOnRails is defined!");
```

I'm all for putting in security improvements, but I'm not convinced on this one.

Another issue is that components have a particular pattern of data attributes, such as `data-component-name`, `data-dom-id`, `data-props`.

**Comment by robwise** [comment]
@justin808 that's basically what I said 15 days ago: https://github.com/shakacode/react_on_rails/pull/387#issuecomment-212351642

I should point out though, that most crawlers don't evaluate JavaScript, so saying that they could just run that JavaScript on the page is not the same as being able to read a server-rendered HTML attribute, as many crawlers won't be able to do the former but will the latter.

I also pointed out the `data-` attribute pattern, but that's a tip-off of React, not necessarily ReactOnRails. 

All of that being said, I still think it's a bit obscure.

**Comment by justin808** [comment]
@alexfedoseev you commented here: https://github.com/shakacode/react_on_rails/pull/387#issuecomment-212358679

I'm tempted to close this. I'm trying to keep the docs and code simpler unless really justified.

**Comment by justin808** [comment]
@jbhatab @alexfedoseev last call if any dissenters on closing this one. Yes, somebody could scan for websites using RoR, but we intend to make our platform NOT have security issues.

**Comment by justin808** [comment]
Closing this for now. We can revisit this later if we feel this is worth doing.

**Pull request closed without merging**
