### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by robwise**
[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/259)

### CODE REVIEW

**Comment by justin808** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 11 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/259#-K9yBWS1Wx78IoyjUCIc:-K9yBWS1Wx78IoyjUCId:580011118) ([raw file](https://github.com/shakacode/react_on_rails/blob/7668f163d6d4b9d40a1a23f13e84a89605180865/CHANGELOG.md#L11)):*
additional spelling

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/259)*

**Comment by justin808** [comment]
:shipit: after you fix the typo

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/259#-:-K9yBe_v6K51VooqwBX8:274514053)*

**Comment by robwise** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 11 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/259#-K9yBWS1Wx78IoyjUCIc:-K9yZLbhsv8eh5anRTx-:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/7668f163d6d4b9d40a1a23f13e84a89605180865/CHANGELOG.md#L11)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/259)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/259)*

**Pull request merged**
