### PR TITLE
WIP: Add image handling example

### PR DESCRIPTION
**Pull request by cheremukhin23**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/768)

### CODE REVIEW

**Comment by justin808** [comment]
@cheremukhin23 Please be sure to check the Travis results:

```
-regenerator@^6.22.0Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
```

https://travis-ci.org/shakacode/react_on_rails/jobs/213883336

**Comment by justin808** [comment]
> 4f7203b: Lock webpack version in generators to 2.2.1

What caused this issue?

---

Reviewed 22 of 22 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 11 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/768#-KfyLC9iJ5BG7SBCTUfV:-KfyLC9iJ5BG7SBCTUfW:b-d5rple) ([raw file](https://github.com/shakacode/react_on_rails/blob/8443ec8871ae25f15f0cae023fd9a5f38147cd9a/CHANGELOG.md#L11)):*
> ```Markdown
> ## Fixed
> - Locked Webpack version in generators to 2.2.1
> - Added style-loaders to webpack config
> ```

This doesn't match other CHANGELOG comments...FYI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/768#-:-KfyKIVyKVNNzHK8_m6L:b-nm5l5p)*

**Comment by justin808** [comment]
@cheremukhin23 Can you try updating to 2.3.1, which is the webpack current. If that works, then let's merge. The change as it is now requires a release, so we should just move to the current version.

**Comment by cheremukhin23** [comment]
@justin808 The issue is caused by breaking change in Webpack itself. 
The output.path required to be an absolute path in webpack v2, but currently it is relative '../app/assets/webpack'.
In webpack 2.2.x there was no absolute path validation, but in 2.3.x it is added.

I'll create a separate PR with webpack update and delete version change from this one.

**Comment by cheremukhin23** [comment]
I've made webpack upgrade as a separate PR. So, I deleted last commits with webpack version lock and CHANGELOG.md.
This PR is waiting to https://github.com/shakacode/react_on_rails/pull/771 now

**Comment by justin808** [comment]
LGTM!

**Pull request merged**
