### PR TITLE
DO NOT MERGE -- Feature/generator rewrite

### PR DESCRIPTION
**Pull request by justin808**
Some WIP progress commits that we might manually merge.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/341)

### CODE REVIEW

**Comment by justin808** [comment]
@jbhatab I created a PR with your changes. I'll probably merge your doc changes in this weekend manually. I've been making lots of updates to the docs recently. Thanks for your help on this!

**Comment by jbhatab** [comment]
@justin808 it is definitely not ready for production. it needs more time.

**Comment by justin808** [comment]
I might try to extract the good work you've done, and then we'd open a new PR for future changes. I've really cleaned up tons recently.

**Comment by jbhatab** [comment]
This is no longer relevant.

**Pull request closed without merging**
