### PR TITLE
added old rails manifest.json support

### PR DESCRIPTION
**Pull request by alleycat-at-git**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/436)

### CODE REVIEW

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/tasks/assets.rake, line 34 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/436#-KIkwJ1w3whpbt1DOJ48:-KIkwJ1xKwXFiENKueXG:-1704571007) ([raw file](https://github.com/shakacode/react_on_rails/blob/42f310b8108255be46e6864931904b040f2c24a9/lib/tasks/assets.rake#L34)):*
> ```Ruby
>           next
>         end
>         manifest_path = manifest_glob.first
> ```

@alleycat-at-git If somebody upgraded, is it possible they could have both files? Seems that the code would get the first file, being the new format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/436)*

**Comment by justin808** [comment]
:lgtm:  I'd day ready to release.

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6350497)
> 
> Coverage remained the same at 82.449% when pulling **42f310b8108255be46e6864931904b040f2c24a9 on alleycat-at-git:hotfix/assets_symlinks** into **4f05cf44f684337e7bd4245f46bc121aea29bac8 on shakacode:master**.
> 
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/436#-:-KIl127WyIRIo0XQE2tC:263791520)*

**Comment by alleycat-at-git** [comment]
Theoretically it could be, but the code will take the new format file and it will be right in this case

**Comment by justin808** [comment]
:lgtm: @alleycat-at-git I'll take care of the CHANGELOG.md

<details><summary><i>Previously, alleycat-at-git (Alexey) wrote…</i></summary>
> Theoretically it could be, but the code will take the new format file and it will be right in this case 
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/436#-:-KIoO5gKbhGZCbwJafKf:-664768450)*

**Comment by justin808** [comment]
Fixed https://github.com/shakacode/react_on_rails/issues/435.

**Pull request merged**
