### PR TITLE
Slight improvement to the 'no hydrated stores' error

### PR DESCRIPTION
**Pull request by cookiefission**
Hi, 

When I was trying to set up server side rendering, I ran into the ['no hydrated stores' error](https://github.com/shakacode/react_on_rails/blob/master/node_package/src/StoreRegistry.js#L42-L46). After some digging, I realised I hadn't called `redux_store_hydration_data` anywhere in my view. 

This should hopefully make it more clear that rendering `redux_store_hydration_data` is required.

Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/605)

### CODE REVIEW

**Comment by justin808** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/src/StoreRegistry.js, line 46 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/605#-KWfS902KDkPkv19ru2m:-KWfS903KuEMAY2DzbVB:b-ajae1e) ([raw file](https://github.com/shakacode/react_on_rails/blob/14e819507c10724c87629f80c93213a34624f505/node_package/src/StoreRegistry.js#L46)):*
> ```JavaScript
>         "redux_store near the top of your controller action's view (not the layout) " +
>         'and before any call to react_component or you do not render ' +
>         '`redux_store_hydration_data` anywhere on your page';
> ```

@cookiefission this is awesome. Can you try this out with a \n to clearly delineate the "ands" and the "or".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/605)*

**Comment by cookiefission** [comment]
image

This is the error now. Is that what you were after?

**Comment by justin808** [comment]
Please see my suggestion.

Try replacing and see if you like it.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/src/StoreRegistry.js, line 46 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/605#-KWfS902KDkPkv19ru2m:-KWupwDWVXCTs6eaXXGF:b-gu69so) ([raw file](https://github.com/shakacode/react_on_rails/blob/14e819507c10724c87629f80c93213a34624f505/node_package/src/StoreRegistry.js#L46)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>       const msg = 'There are no stores hydrated and you are requesting the store ' +
>         `${name}. This can happen if you are server rendering and either \nyou do not call ` +
>         "redux_store near the top of your controller action's view (not the layout) " +
>         'and before any call to react_component \nor you do not render ' +
>         'redux_store_hydration_data anywhere on your page';
</details>


      const msg = `There are no stores hydrated and you are requesting the store ${name}.
This can happen if you are server rendering and either:
1. You do not call redux_store near the top of your controller action's view (not the layout)
and before any call to react_component.
2. You do not render redux_store_hydration_data anywhere on your page.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/605#-:-KWuqsi1lZ5hELnAzwZv:b-1s2134)*

**Comment by justin808** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/src/StoreRegistry.js, line 46 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/605#-KWfS902KDkPkv19ru2m:-KWxjmMz8fnVHsgNw0Q2:b-74yhok) ([raw file](https://github.com/shakacode/react_on_rails/blob/14e819507c10724c87629f80c93213a34624f505/node_package/src/StoreRegistry.js#L46)):*
>   const msg = `There are no stores hydrated and you are requesting the store ${name}.
> 
> 
> This can happen if you are server rendering and either:
> 1. You do not call redux_store near the top of your controller action's view (not the layout)
> and before any call to react_component.
> 2. You do not render redux_store_hydration_data anywhere on your page.`


Hey the formatting got skewered in my prior comment, @cookiefission 

```js
  const msg = 
`There are no stores hydrated and you are requesting the store ${name}.
This can happen if you are server rendering and either:
1. You do not call redux_store near the top of your controller action's view (not the layout)
and before any call to react_component.
2. You do not render redux_store_hydration_data anywhere on your page.`
```

Notice there are backticks around the whole string.
You can have embedded returns in the backtick strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/605)*

**Comment by justin808** [comment]
I updated my comment. Please use backticks.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/605#-:-KWxk5YvVV9aEM7u2Cd0:b-48p4hc)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/605)*

**Comment by justin808** [comment]
@cookiefission Did you try this out? You indented the lines, and the indents will be part of the message. I don't think you want the indents. Please paste a screenshot of how the message prints out.

**Comment by cookiefission** [comment]
image

This is how the error appears now. The `1. ...` l goes on to another line because if I didn't do that, the line of code would go over 120 chars. I can change that if you want.

Also, when this is good to go, do you want me to squash the commits down or not?

**Comment by justin808** [comment]
Thanks @cookiefission!

**Pull request merged**
