### PR TITLE
The React On Rails Doctrine

### PR DESCRIPTION
**Pull request by justin808**
First drafts of

* The React on Rails Doctrine
* Recommended Project Structure

[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/220)

### CODE REVIEW

**Comment by robwise** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[docs/coding-style/style.md, line 21 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q4t7hFGFqIkF3hGvH:-K8q4t7hFGFqIkF3hGvI:71232830) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/coding-style/style.md#L21)):*
I think this is confusing because we just linked our own style guide above, we can just let them follow that link and it explains that it's based on AirBnB over at that repo.

---

*[docs/doctrine.md, line 3 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q5A7AjGKfnpuJn6zU:-K8q5A7AjGKfnpuJn6zV:1143667638) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L3)):*
I don't think we should start putting authorship on OSS docs because it could discourage participation. Like, I rewrote a lot of the documentation on the README but I didn't put "by Rob Wise" on there or whatever, and I'm providing some editing advice on this. If you do remove the authorship thing, then I would make the rest of this doc use the same narrative as the rest of the documentation.

---

*[docs/doctrine.md, line 15 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q5xvPz8zDfWyolsAv:-K8q5xvPz8zDfWyolsAw:2100272967) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L15)):*
`Sass, actually` note the comma.

Also are you sure `arbitrarily` is the word you want to use here? And this is sort of still the case if we are using bootstrap, and it's not really about positioning so much as it is as namespacing to avoid name collisions

---

*[docs/doctrine.md, line 16 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q6OIK_I6OoWkhZENh:-K8q6OIK_I6OoWkhZENi:415363250) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L16)):*
"using Babel and Webpack, is a great language" this could use rewording. How can using something be a language? Also, no comma

---

*[docs/doctrine.md, line 17 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q6dpiIpDFenx1sb_j:-K8q6dpiIpDFenx1sb_k:1535580440) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L17)):*
You've switched from first-person singular narrative at the begining to first-person plural narrative here (https://en.wikipedia.org/wiki/Narration#Narrative_point_of_view)

---

*[docs/doctrine.md, line 20 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q6t1LsgsBvAtDjHTW:-K8q6t1LsgsBvAtDjHTX:156090310) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L20)):*
`setup` is really only valid when used as a noun (http://dictionary.reference.com/browse/setup?s=t), I would use `set up` here

---

*[docs/doctrine.md, line 21 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q75Bgaj8AOYU6FHad:-K8q75Bgaj8AOYU6FHae:1121429395) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L21)):*
"By placing all client-side development inside of..."

"...can create **their** own stub.."

The second-to-last sentence is a run-on

---

*[docs/doctrine.md, line 25 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q7kI0Nt5D2q1sVp7j:-K8q7kI1OjFCN8WykRLo:-1941606443) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L25)):*
now you're also using the 2nd-person narrative, need to keep it consistent

---

*[docs/doctrine.md, line 35 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q8FBgXY_HdqfkiT19:-K8q8FBgXY_HdqfkiT1A:815443197) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L35)):*
most of this doc you don't put a blank line under a header, which is the way I do it too, but here you do.

---

*[docs/doctrine.md, line 42 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q8PwszOuvYj17fegx:-K8q8PwtcbfwJQrI_bw1:-1287380927) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L42)):*
I'd say "provide deep links for your client-side application"

---

*[docs/doctrine.md, line 43 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q8U2EgzA_XBktfbhR:-K8q8U2EgzA_XBktfbhS:-8205555) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L43)):*
it's borderline not a Flux implementation since it does away with some parts of Flux, it's technically a "state container"

---

*[docs/doctrine.md, line 48 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q8h4Cvqun6g2AikaH:-K8q8h4Cvqun6g2AikaI:-2108182587) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L48)):*
The descriptions for each item need to have paralell construction: http://data.grammarbook.com/blog/effective-writing/parallel-construction/

---

*[docs/doctrine.md, line 55 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q9HFyvgQ15EI82xtD:-K8q9HFyvgQ15EI82xtE:-693960159) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L55)):*
"into" appears twice on either side of "No One Paradigm". I think this sentence could be reworded a little?

---

*[docs/doctrine.md, line 58 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q9c1PYehgXJbF_5I2:-K8q9c1PYehgXJbF_5I3:475130359) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L58)):*
this is controversial, but personally I think the 2nd to last item in a list should always have a trailing comma: "with the ShakaCode linters**,**"

---

*[docs/doctrine.md, line 61 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qA-4EHYOJKqDuIHcR:-K8qA-4EHYOJKqDuIHcS:1279169865) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L61)):*
"Here's why:"

---

*[docs/doctrine.md, line 64 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qAA56TZ6hBMJYKLkN:-K8qAA56TZ6hBMJYKLkO:816661748) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L64)):*
"allows for trivial set up..."

---

*[docs/doctrine.md, line 65 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qAQ2rVdalTMANOld0:-K8qAQ2rVdalTMANOld1:621175548) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L65)):*
I'd drop the first two sentences as that's a pretty debatable assertion and is just going to cause nerd rage

---

*[docs/doctrine.md, line 74 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qAfLcnDay2z5yU4cq:-K8qAfLcnDay2z5yU4cr:-960450419) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L74)):*
"push up" is not an action one would perform on a tent. 

---

*[docs/doctrine.md, line 75 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qAqTDuQGSuZHTnUsQ:-K8qAqTDuQGSuZHTnUsR:294005183) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L75)):*
The mention of RSpec here seems out of place, especially since Rails uses minitest and not RSpec by default

---

*[docs/recommended-project-structure.md, line 3 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qBGc_QCyHsc4BD1W5:-K8qBGcauZY7AnBcUYgK:-1197634324) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L3)):*
"a" not "an", and I would put "enforce" and "recommend" in italics or bold or something to emphasize the difference in wording

---

*[docs/recommended-project-structure.md, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qBdlpxQzmDIXeHMlx:-K8qBdlpxQzmDIXeHMly:1720221898) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L10)):*
I wouldn't put `HelloWorld` in `lib` as an example since that might be confusing and contradicts our generated code

---

*[docs/recommended-project-structure.md, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qC674f3YUnzo4d1u7:-K8qC675DQ2U5TCbD3vZ:2008958481) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L19)):*
they're not for JSON files, but for JSON from Ajax requests to be used by the [Normalizr](https://github.com/gaearon/normalizr) package from Dan Abramov.

We are also missing the `store` folder as is the convention for Redux apps

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[docs/coding-style/style.md, line 21 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q4t7hFGFqIkF3hGvH:-K8qiphrTQ63ILT-e4ut:-1054325829) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/coding-style/style.md#L21)):*
removed

---

*[docs/doctrine.md, line 3 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8q5A7AjGKfnpuJn6zU:-K8qjAwQNQ1dc07zZ3Xt:-677404483) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L3)):*
we'll just use my name for now

---

*[docs/doctrine.md, line 74 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qAfLcnDay2z5yU4cq:-K8qoNrNt9qdsU5NEbM9:539913898) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L74)):*
http://rubyonrails.org/doctrine/#big-tent 

---

*[docs/recommended-project-structure.md, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qC674f3YUnzo4d1u7:-K8qrh9x9lo9sj05jqIp:591054018) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L19)):*
@alexfedoseev We're not doing a store folder in our own app. Any take on that?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220)*

**Comment by justin808** [comment]
@robwise :clap: Thanks! See next commit!

---

Review status: all files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-:-K8qsYgtkNVffhdy7fng:1028615416)*

**Comment by alexfedoseev** [comment]
Review status: 1 of 4 files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[docs/recommended-project-structure.md, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qBdlpxQzmDIXeHMlx:-K8rV2Uy18UG9-hN3234:-1412778274) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L10)):*
I'm not sure about this one. I'd use `libs` as a place for non-bundle-specific commons things, otherwise I see no reason to move bundle-specific code outside the bundle folder.

---

*[docs/recommended-project-structure.md, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qC674f3YUnzo4d1u7:-K8rRMSv8U7_1w_qM9jK:1244892230) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L19)):*
We just put it in the startup from the very beginning and never focused on it b/c there was no reason. I have no objections against moving it to `store` folder :+1: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220)*

**Comment by mapreal19** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220)*

**Comment by justin808** [comment]
Review status: 1 of 4 files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[docs/recommended-project-structure.md, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qC674f3YUnzo4d1u7:-K8s4s5obWKB2Zc1gsfC:1664205231) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L19)):*
Is a store folder worth it if there can only be one store object?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220)*

**Comment by robwise** [comment]
One minor thing left, great work making all of those edits!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/doctrine.md, line 74 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qAfLcnDay2z5yU4cq:-K8tXkVo6jvat-bSINRY:941541654) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/doctrine.md#L74)):*
@justin808 Hey go with it if you want, but it's wrong and DHH is not a native English speaker!

---

*[docs/doctrine.md, line 64 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8tXYWfKhlhg6v3pAxw:-K8tXYWg_BZrvb2-4u23:-1822344535) ([raw file](https://github.com/shakacode/react_on_rails/blob/177dff4a69422ed828ce262a5111f1b1b73b19d6/docs/doctrine.md#L64)):*
"with support **for** fragment..."

---

*[docs/recommended-project-structure.md, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qC674f3YUnzo4d1u7:-K8tYoUS4ELgqxofPvvq:-1493553892) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L19)):*
@justin808 Your point is perfectly logical and I'm inclined to agree with you, but on the other hand, it's the convention or whatever, and I think it's nice to have the ReactOnRails-specific code in its own folder (`startup`)

---

*[docs/recommended-project-structure.md, line 6 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8tYZRyEfAytL_627C8:-K8tYZRyEfAytL_627C9:-1295626587) ([raw file](https://github.com/shakacode/react_on_rails/blob/177dff4a69422ed828ce262a5111f1b1b73b19d6/docs/recommended-project-structure.md#L6)):*
now that we have `widget-editing` in the example below, there may some confusion about say "We don't use dashes...for Javascript files"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-:-K8tZU4Gz55v0F8GDDTM:-1560987163)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/recommended-project-structure.md, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qC674f3YUnzo4d1u7:-K8vDs_XmU02liAY-Jdt:-2081913704) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L19)):*
So store goes in startup or separate store directory? what's the convention @alexfedoseev @robwise @jbhatab ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220)*

**Comment by justin808** [comment]
couple edits done

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-:-K8vE-o-i1XAqnSJNQmS:-1691631724)*

**Comment by robwise** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/recommended-project-structure.md, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/220#-K8qC674f3YUnzo4d1u7:-K8va9XhDc8XD78jly0y:-329381554) ([raw file](https://github.com/shakacode/react_on_rails/blob/75ecbc9d7383ef4088535b3ef0ba78b99aebfe3f/docs/recommended-project-structure.md#L19)):*
convention is its own folder: `store/configureStore.js`: https://github.com/rackt/redux/tree/master/examples/real-world/store

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/220)*

**Pull request merged**
