### PR TITLE
Update turbolinks.md

### PR DESCRIPTION
**Pull request by justin808**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/573)

### CODE REVIEW

**Comment by justin808** [comment]
@Judahmeek?

**Comment by justin808** [comment]
@robwise, @alexfedoseev, @dzirtusss Please comment.

**Comment by alexfedoseev** [comment]
@justin808 LGTM

**Comment by Judahmeek** [comment]
Nice! Reading https://github.com/turbolinks/turbolinks-classic/issues/658 was pretty awesome.

**Comment by dzirtusss** [comment]
@justin808 @alexfedoseev @Judahmeek @robwise LGTM, and just for further info, some issues I had with Turbolinks5 worth mentioning:
- CFRS tokens need thorough check with Turbolinks5. Turbolinks5 do change `head` element by JavaScript (not only `body`) on page change with correct csrf meta tag, but it was something with the way it was taken from head when several windows were opened, that our specs were not all passing. I didn't look details however, may be it is app code related, not library code. Anyway it may need additional check because there is cfrs helper in ReactOnRails and it need to work with Turbolinks5.
- Turbolinks5 send requests without `Accept: */*` in header, only exact like `Accept: text/html` which makes Rails behave a bit specifically compared to normal and do mime-parsing (which is skipped by desing when Rails see `*/*`). In my case it was triggering :mjml parser not found error, as example. For some more details on Rails and `*/*` can read http://blog.bigbinary.com/2010/11/23/mime-type-resolution-in-rails.html
- As noted above there should be no names conflict and all components need to be loaded and registered with first page load

**Pull request merged**
