### PR TITLE
Add Flowtype (WIP)

### PR DESCRIPTION
**Pull request by AlexKVal**
#### I will be gradually adding commits step by step to facilitate review and for earlier feedbacks.

--
I've started to learn [flow](https://flowtype.org). Yay \\\_o\_/ 😄 

But IMHO
Adding flowtype annotations to the library is kinda Pandora's box.
It adds a lot of additional maintenance burden.

--
The first three commits:
green https://travis-ci.org/AlexKVal/react_on_rails/builds/153954865

**src/Authenticity.js**
without **{content?: string}** it warns about
```
property `content` Property not found in HTMLElement
```
because it is a dynamic property from `document.querySelector('meta[name="csrf-token"]')`

--
The line
`lib/generators/react_on_rails/templates/node/base/client/node/server.js` has been added to `.eslintignore` because of https://github.com/shakacode/react_on_rails/pull/469 merging with linting errors 😈 
I'll remove it after the master branch will have resolved linting issues.

--
#### Notes about 'fsevents' bug
After a fresh `npm i` installation of all packages with **node@6** version
running of `npm run build` or `build-watch`
throws this node's error:
```
v8::ObjectTemplate::Set() with non-primitive values is deprecated
```
`babel-cli` uses `chokidar` which uses not the latest `fsevents` 
`npm i fsevents@latest` command solves the problem.
The cause of it https://github.com/strongloop/fsevents/pull/128
Probably we should add the latest `fsevents` version to `package.json`
via `npm i -D fsevents@latest` command.

--
#### Notes about Atom's `linter-flow`
I've managed to get it working only with **node@6.3.1** version (out of 6th versions)
`linter-flow` doesn't work with the latest (at the moment) **node@6.4.0**. (w/o errors. it just doesn't show any warnings in Atom)

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/530)

### CODE REVIEW

**Comment by alleycat-at-git** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[node_package/src/context.js, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-KPkkKSTar5IteFDdlDb:-KPkkKSTar5IteFDdlDc:botapkf) ([raw file](https://github.com/shakacode/react_on_rails/blob/9af0cd877b4ccc9da768fe1a6f2af2d0ab6f3d7f/node_package/src/context.js#L5)):*
> ```JavaScript
>  * @returns {boolean|Window|*|context}
>  * @flow
>  */
> ```

I think it might be better to put // @flow as a separate line at the top, o/w it's lost in the comment description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/530)*

**Comment by justin808** [comment]
@alexkval Did we not need to add the  params for flow?

We should probably have this in the eslintrc, but only for the library, not the samples...

```
  flowtype/require-parameter-type: 2
  flowtype/require-return-type:
    - 2
    - always
    -
      excludeArrowFunctions: expressionsOnly
  flowtype/space-after-type-colon:
    - 2
    - always
  flowtype/space-before-type-colon:
    - 2
    - never
  flowtype/require-valid-file-annotation:
    - 2
    - always
  flowtype/valid-syntax: 2
```

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[node_package/src/context.js, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-KPkkKSTar5IteFDdlDb:-KPl7B6H-itg3G1TMiPX:bsm8e3u) ([raw file](https://github.com/shakacode/react_on_rails/blob/9af0cd877b4ccc9da768fe1a6f2af2d0ab6f3d7f/node_package/src/context.js#L5)):*
<details><summary><i>Previously, alleycat-at-git (Alexey) wrote…</i></summary>
> I think it might be better to put // @flow as a separate line at the top, o/w it's lost in the comment description.
</details>
I agree with 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-:-KPl7vQJUDZap2mBSVbc:b-pwxflz)*

**Comment by justin808** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[node_package/src/Authenticity.js, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-KPlYpE8lWL8BfTFFYOP:-KPlYpE8lWL8BfTFFYOQ:byqro7g) ([raw file](https://github.com/shakacode/react_on_rails/blob/9af0cd877b4ccc9da768fe1a6f2af2d0ab6f3d7f/node_package/src/Authenticity.js#L10)):*
> ```JavaScript
>   },
> 
>   authenticityHeaders(otherHeaders: Object = {}) {
> ```

This needs to be string values in the object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/530)*

**Comment by AlexKVal** [comment]
@alleycat-at-git thank you for the help. I wasn't sure what is the best way.

@justin808 thank you for the rules for 'eslint'. I'll implement them one by one.

**Comment by justin808** [comment]
Nice work. A couple ideas.

---

Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[node_package/src/Authenticity.js, line 10 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-KPqFnrH0V0q4les2s8W:-KPqFnrH0V0q4les2s8X:b-l1gars) ([raw file](https://github.com/shakacode/react_on_rails/blob/a07244eb1d452270f5d412310c651551843543ce/node_package/src/Authenticity.js#L10)):*
> ```JavaScript
>   },
> 
>   authenticityHeaders(otherHeaders: {[id:string]: string} = {}) {
> ```

It seems a bit odd for object properties to be a string. 

However, this is from the example (kval), so maybe we use `key`

```
type MapOfNumbers = { [key: string]: number };
var numbers: MapOfNumbers = {
  ten: 10,
  twenty: 20,
};
```

---

*[node_package/src/generatorFunction.js, line 12 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-KPqLdicMFQ1R16K1k14:-KPqLdidTKKWtt6S2SFs:b-cbdepx) ([raw file](https://github.com/shakacode/react_on_rails/blob/a07244eb1d452270f5d412310c651551843543ce/node_package/src/generatorFunction.js#L12)):*
> ```JavaScript
>  * @returns {boolean}
>  */
> export default function generatorFunction(component: any) {
> ```

https://flowtype.org/docs/union-intersection-types.html#_

This one is either 

React.createClass (probably an object)
ES6 Class
Function

Then again, `any` might be good enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-:-KPqLvKXKasZb0fh_uJi:bgm6m4y)*

**Comment by AlexKVal** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[node_package/src/Authenticity.js, line 10 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-KPqFnrH0V0q4les2s8W:-KPqUjaO-1ql810LlcT7:bqpnrk6) ([raw file](https://github.com/shakacode/react_on_rails/blob/a07244eb1d452270f5d412310c651551843543ce/node_package/src/Authenticity.js#L10)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> It seems a bit odd for object properties to be a string. 
> 
> However, this is from the example (kval), so maybe we use `key`
> 
> ```
> type MapOfNumbers = { [key: string]: number };
> var numbers: MapOfNumbers = {
>   ten: 10,
>   twenty: 20,
> };
> ```
> 
</details>
Yes I just got it from `flowtype.org/examples` as is.

---

*[node_package/src/generatorFunction.js, line 12 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/530#-KPqLdicMFQ1R16K1k14:-KPqVCX9dqEW_5mojzh9:b-gn5dff) ([raw file](https://github.com/shakacode/react_on_rails/blob/a07244eb1d452270f5d412310c651551843543ce/node_package/src/generatorFunction.js#L12)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> https://flowtype.org/docs/union-intersection-types.html#_
> 
> This one is either 
> 
> React.createClass (probably an object)
> ES6 Class
> Function
> 
> Then again, `any` might be good enough.
> 
> 
</details>
I have no idea (yet) how to describe such complex types in `flowtype`.
My goal is to satisfy all warnings the simplest possible way
and only then start to re-write it with more elaborate and complex flowtype's descriptors.

--
I'm implementing `flowtype` first time ever. I have no experience with it at all.
So I really appreciate all the help! Thank you. :cherries: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/530)*

**Pull request merged**
