### PR TITLE
Running unit tests on rails 3.2 added

### PR DESCRIPTION
**Pull request by morozovm**
#814 related

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/914)

### CODE REVIEW

**Comment by morozovm** [comment]
+@justin808

**Comment by justin808** [comment]
:lgtm:

couple small question

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Rakefile, line 15 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-KrdwoD1BBwPLele5mQC:-KrdwoD1BBwPLele5mQD:b49irc7) ([raw file](https://github.com/shakacode/react_on_rails/blob/f58345cfc87be91447e373a071f3c522a1353e04/Rakefile#L15)):*
> ```Ruby
> 
> if File.basename(ENV["BUNDLE_GEMFILE"] || "") == "Gemfile.rails32"
>   tasks = %w[run_rspec:gem_rails32 lint:rubocop]
> ```

why do we need to lint again?

---

*[spec/react_on_rails/spec_helper.rb, line 5 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-Krdvs-LvPfc8-d0Kxq3:-Krdvs-LvPfc8-d0Kxq4:b-t8lnye) ([raw file](https://github.com/shakacode/react_on_rails/blob/f58345cfc87be91447e373a071f3c522a1353e04/spec/react_on_rails/spec_helper.rb#L5)):*
> ```Ruby
> $LOAD_PATH.unshift File.expand_path("../../../lib", __FILE__)
> require "react_on_rails"
> # let's us use Rails's generator testing helpers but with RSpec syntax
> ```

why was this moved?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-Krdx4Dc_ng7bCm9JHK0:bd9ocum)*

**Comment by justin808** [comment]
@morozovm It appears from https://travis-ci.org/shakacode/react_on_rails/jobs/264839798 that we didn't run the integration tests on Spec Dummy.

**Comment by morozovm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[spec/react_on_rails/spec_helper.rb, line 5 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-Krdvs-LvPfc8-d0Kxq3:-Krh4nISgyNJttCSgfs7:bwa8zgi) ([raw file](https://github.com/shakacode/react_on_rails/blob/f58345cfc87be91447e373a071f3c522a1353e04/spec/react_on_rails/spec_helper.rb#L5)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why was this moved?
</blockquote></details>

Initially i excluded a generators folder from running specs which cause to fail multiple other specs with errors looking like activesupport did not loaded (undefined method `year' , undefined method `to_json'), I am not quite sure how it related but loading "generator_spec" fix it so I moved it to spec_helper

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914)*

**Comment by morozovm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Rakefile, line 15 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-KrdwoD1BBwPLele5mQC:-Krh5_pHQXzTVPUVeaOO:b-t18e7f) ([raw file](https://github.com/shakacode/react_on_rails/blob/f58345cfc87be91447e373a071f3c522a1353e04/Rakefile#L15)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why do we need to lint again?
</blockquote></details>

I guess it is not needed since it running on other two build jobs in the matrix. Just thought it would be nice to include it here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914)*

**Comment by morozovm** [comment]
Quoting you from the text of the original issue “Don't run /spec/dummy and the generator tests.” 
I wanted to consult with you on how exactly you envision testing setup to look like on rails 3 before putting more effort because text of original issue seems a little confusing. I explored the possibility of running /spec/dummy tests on older versions and was able to run on 4.2 but not lower since /spec/dummy depends on webpacker_lite which requires rails 4.2. Should I put effort into porting  webpacker_lite to rails 3.2 ? cause whole thing of running integration tests on rails 3 looks like separate venture and too much for initial issue of testing escaping json on older version of rails.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-Krh5jse4wF0Q8EIzW1S:bzcpw2j)*

**Comment by justin808** [comment]
> Quoting you from the text of the original issue “Don't run /spec/dummy and the generator tests.”
> I wanted to consult with you on how exactly you envision testing setup to look like on rails 3 before putting more effort because text of original issue seems a little confusing. I explored the possibility of running /spec/dummy tests on older versions and was able to run on 4.2 but not lower since /spec/dummy depends on webpacker_lite which requires rails 4.2. Should I put effort into porting webpacker_lite to rails 3.2 ? cause whole thing of running integration tests on rails 3 looks like separate venture and too much for initial issue of testing escaping json on older version of rails.

@morozovm,
Good analysis.
Ideally, we should have a very simple /spec/dummy_no_webpacker rails 3 (maybe even 4 + 5) app that just has a few smoke tests, or even to start with a copy of the tests from /spec/dummy

If you copied the /spec/dummy from the last v7 release, and put in spec/dummy_no_webpacker, that might do the trick.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-Krhtrvd7H2j0DLHgU9P:bb67hmb)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Rakefile, line 15 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-KrdwoD1BBwPLele5mQC:-Krhuik9i8tNMG2Wz_KZ:b-8mkuku) ([raw file](https://github.com/shakacode/react_on_rails/blob/f58345cfc87be91447e373a071f3c522a1353e04/Rakefile#L15)):*
<details><summary><i>Previously, morozovm (Maksim Morozov) wrote…</i></summary><blockquote>

I guess it is not needed since it running on other two build jobs in the matrix. Just thought it would be nice to include it here too.
</blockquote></details>

should we remove this then?

---

*[spec/react_on_rails/spec_helper.rb, line 5 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-Krdvs-LvPfc8-d0Kxq3:-Krhukd9Pvj-6TlMKNQ8:b-f640u5) ([raw file](https://github.com/shakacode/react_on_rails/blob/f58345cfc87be91447e373a071f3c522a1353e04/spec/react_on_rails/spec_helper.rb#L5)):*
<details><summary><i>Previously, morozovm (Maksim Morozov) wrote…</i></summary><blockquote>

Initially i excluded a generators folder from running specs which cause to fail multiple other specs with errors looking like activesupport did not loaded (undefined method `year' , undefined method `to_json'), I am not quite sure how it related but loading "generator_spec" fix it so I moved it to spec_helper
</blockquote></details>

should this move back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914)*

**Comment by morozovm** [comment]
Review status: 4 of 227 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Rakefile, line 15 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-KrdwoD1BBwPLele5mQC:-KrrGXZYT6DUxvyczJ6c:b-hfpv0l) ([raw file](https://github.com/shakacode/react_on_rails/blob/f58345cfc87be91447e373a071f3c522a1353e04/Rakefile#L15)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

should we remove this then?
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914)*

**Comment by morozovm** [comment]
Review status: 4 of 227 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[spec/react_on_rails/spec_helper.rb, line 5 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-Krdvs-LvPfc8-d0Kxq3:-KrrHizetYrIjJjeHQ4-:bev72g1) ([raw file](https://github.com/shakacode/react_on_rails/blob/f58345cfc87be91447e373a071f3c522a1353e04/spec/react_on_rails/spec_helper.rb#L5)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

should this move back?
</blockquote></details>

spec helper is the place for it to be put in since a multiple specs depend on it to run properly not just generators specs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914)*

**Comment by morozovm** [comment]
coping /spec/dummy from the last v7 release and making slight adjustments seems to be working, i still have to solve the mystery of data-trace="false" attribute not being rendered in spec/dummy_no_webpacker/spec/helpers/react_on_rails_helper_spec.rb and eslint issues with dummy_no_webpacker but  all in all it looks promising

---

Review status: 4 of 227 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-KrrUMWWBlf4aKJ7FLtl:b-ioyzx4)*

**Comment by justin808** [comment]
We need to use sym links for the directories that are the same.  

---

Reviewed 52 of 223 files at r2.
Review status: 56 of 227 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/helpers/react_on_rails_helper.rb, line 186 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-KrtjAOezdb7egb7n6zD:-KrtjAOezdb7egb7n6zE:bcgjvre) ([raw file](https://github.com/shakacode/react_on_rails/blob/8db9227530f3c3dddad0be30454f13415bb0da9b/app/helpers/react_on_rails_helper.rb#L186)):*
> ```Ruby
> 
>   def sanitized_props_string(props)
>     ReactOnRails::JsonOutput.escape(props.is_a?(String) ? props : props.to_json)
> ```

Why this change?

---

*[spec/dummy_no_webpacker/Procfile.dev, line 1 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-Krtjkf5eNcwG0Je9soV:-Krtjkf5eNcwG0Je9soW:bjngpbp) ([raw file](https://github.com/shakacode/react_on_rails/blob/8db9227530f3c3dddad0be30454f13415bb0da9b/spec/dummy_no_webpacker/Procfile.dev#L1)):*
> ```
> Procfile
> ```

Does this work?
Missing new line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-KrtlM0Mve9NT_FmS30K:b-n4pxbk)*

**Comment by morozovm** [comment]
sym links pointing to /spec/dummy sub directories?

---

Review status: 56 of 227 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-KruYA6rZrTt-g3UkPN-:bjiat4d)*

**Comment by morozovm** [comment]
Review status: 56 of 227 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/helpers/react_on_rails_helper.rb, line 186 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-KrtjAOezdb7egb7n6zD:-Krua4KCR-eUVYinjtIW:b-4e1qtq) ([raw file](https://github.com/shakacode/react_on_rails/blob/8db9227530f3c3dddad0be30454f13415bb0da9b/app/helpers/react_on_rails_helper.rb#L186)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

makes sanitized_props_string specs pass
before the change 
```
Failures:

  1) ReactOnRailsHelper#sanitized_props_string(props) converts a hash to JSON and escapes </script>
     Failure/Error: expect(sanitized).to eq(json_string_sanitized)

       expected: "{\"hello\":\"world\",\"free\":\"of charge\",\"x\":\"\\u003c/script\\u003e\\u003cscript\\u003ealert('foo')\\u003c/script\\u003e\"}"
            got: "{\"hello\":\"world\",\"free\":\"of charge\",\"x\":\"</script><script>alert('foo')</script>\"}"

       (compared using ==)
     # ./spec/helpers/react_on_rails_helper_spec.rb:57:in `block (3 levels) in <top (required)>'

  2) ReactOnRailsHelper#sanitized_props_string(props) leaves a string alone that does not contain xss tags
     Failure/Error: expect(sanitized).to eq(json_string_sanitized)

       expected: "{\"hello\":\"world\",\"free\":\"of charge\",\"x\":\"\\u003c/script\\u003e\\u003cscript\\u003ealert('foo')\\u003c/script\\u003e\"}"
            got: "{hello:world,free:of charge,x:\\u003c/script\\u003e\\u003cscript\\u003ealert('foo')\\u003c/script\\u003e}"

       (compared using ==)
     # ./spec/helpers/react_on_rails_helper_spec.rb:62:in `block (3 levels) in <top (required)>'

  3) ReactOnRailsHelper#sanitized_props_string(props) fixes a string alone that contain xss tags
     Failure/Error: expect(sanitized).to eq(json_string_sanitized)

       expected: "{\"hello\":\"world\",\"free\":\"of charge\",\"x\":\"\\u003c/script\\u003e\\u003cscript\\u003ealert('foo')\\u003c/script\\u003e\"}"
            got: "{hello:world,free:of charge,x:\\u003C/script\\u003E\\u003Cscript\\u003Ealert('foo')\\u003C/script\\u003E}"

       (compared using ==)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914)*

**Comment by justin808** [comment]
> sym links pointing to /spec/dummy sub directories?
YES! Try to avoid duplicated files.

> makes sanitized_props_string specs pass
Are you saying that we are broken for Rails prior to X version, but were working for what version?
Please provide a little more detail.

**Comment by morozovm** [comment]
yes if we believe the specs, it passes without fix on 5.0.2 and fails on 3.2.22.5
and again if we believe whole design purpose of ReactOnRails::JsonOutput 
```
escape_without_erb_util(json) if Utils.rails_version_less_than_4_1_1
```
it broken right now on all prior to 4.1.1

(it passes on both 5.0.2 and 3.2.22.5 with the fix)

---

Review status: 56 of 227 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-Krw9d0so7Th51D11hE3:bvqrs6b)*

**Comment by morozovm** [comment]
Hi again @justin808 
I have linked rspec subdirectories and client/app to spec/dummy, made some adjustment to
server_render_check_spec.rb
react_on_rails_helper_spec.rb
and finally was able to get all green on the rspecs, but travis run is failing  with oddest thing
```
Building Webpack assets...
================================================================================
React on Rails FATAL ERROR!
Error in building webpack assets!
cmd: cd client && yarn run build:test
exitstatus: 1
stdout:
yarn run v0.27.5
$ yarn run build:client && yarn run build:server
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
stderr:
sh: 1: webpack: not found
error Command failed with exit code 127.
error Command failed with exit code 1.
================================================================================
```
I am honestly lost, maybe you can give a advice on what is missing.

---

Review status: 51 of 173 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-Ks9IZ6KPvtS9cnDbnnO:bqtduw1)*

**Comment by morozovm** [comment]
Review status: 51 of 173 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[spec/dummy_no_webpacker/Procfile.dev, line 1 at r2](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-Krtjkf5eNcwG0Je9soV:-Ks9LxBnbjrcUDQTTtHl:b-wl3tkg) ([raw file](https://github.com/shakacode/react_on_rails/blob/8db9227530f3c3dddad0be30454f13415bb0da9b/spec/dummy_no_webpacker/Procfile.dev#L1)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Does this work?
Missing new line?
</blockquote></details>

it is a symbolic link, and it is working

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914)*

**Comment by morozovm** [comment]
i was able to identify the origin of issue and currently in process of solving it

---

Review status: 51 of 173 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-KsB-BPoCJ9_ner2yuki:b-wnmn56)*

**Comment by justin808** [comment]
@morozovm This is fabulous. I'm hoping we get down to a smaller number of files...

Be aware that there can be some issues with symlinks and the node modules.

**Comment by morozovm** [comment]
@justin808 ok i have solved "webpack: not found" issue by adding "npm install" into the mix but now i completely stuck with all of integration specs falling without cue why so, it is all green locally.

---

Review status: 50 of 232 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-KsES1eEHmCT1i4sb2Cq:b-a6tbzd)*

**Comment by morozovm** [comment]
Well I succumb to excluding features specs from the build, trying to figure out what is wrong in travis build on public repository without "debug button" is the hellish nightmare.
On linking directories issue there is too much subtle differences to ifelse around, i honestly think copies is better solution even though it is look dumb.

---

Review status: 50 of 231 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-KsErCevmntZi_vK2Fhe:bjp7lmo)*

**Comment by justin808** [comment]
@morozovm Thanks. I realize there could be lots of issues with the sym linking. Any recommendations on the best way for me to review such a large set of files? In other words, if I knew which files differed, that would be helpful. I guess, ideally, there would be a commit with the exact copies, and another with the the changes, so I could just see the diff in the second commit.

**Comment by morozovm** [comment]
@justin808 
I squashed all dummy_no_webpacker related changes into three commits 
232c699: v7 coping into dummy_no_webpacker
b83db37: all changes made in  dummy_no_webpacker directory after
8866436: all other changes made outside of dummy_no_webpacker directory

hope that helps

---

Review status: 43 of 230 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-KsOZ8yEy6rqNyodcRy_:b-p39llp)*

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 147 of 223 files at r2, 45 of 48 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[spec/dummy/Gemfile, line 73 at r3](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-KsgskCaiu_C792db-IE:-KsgskCaiu_C792db-IF:b-lwp5e) ([raw file](https://github.com/shakacode/react_on_rails/blob/8866436ddf75b89925eb02e34696e5aabb9b6d8f/spec/dummy/Gemfile#L73)):*
> mbklein/equivalent-xml"
Odd that no 1.0 is yet pushed, @morozovm 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/914#-:-KsgtcbOa3_nISecSB3H:bnfp4nl)*

**Comment by justin808** [comment]
Great job @morozovm! Let's be in touch!

**Pull request merged**
