### PR TITLE
Update dependencies with doc on how to update

### PR DESCRIPTION
**Pull request by justin808**
All updated to absolute latest. 

Verified against: 
https://github.com/justin808/test-react-on-rails-3/commit/4042638012dd8df0858697d646ab94ab1dd3d304

[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/223)

### CODE REVIEW

**Comment by justin808** [comment]
@alexfedoseev @robwise Please take a quick peek.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/223#-:-K8rJakyW3_HjpWDh4tL:-1604540639)*

**Comment by alexfedoseev** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/additional_reading/updating-dependencies.md, line 20 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/223#-K8rLfF1EzQQKdK7Wmkg:-K8rLfF1EzQQKdK7Wmkh:1220473263) ([raw file](https://github.com/shakacode/react_on_rails/blob/ba9ed58fc1d0e93be89f03b14ab02dc6896dd069/docs/additional_reading/updating-dependencies.md#L20)):*
I do it only in case I have some weird conflicts from npm.

---

*[docs/additional_reading/updating-dependencies.md, line 21 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/223#-K8rM7ozTMcFC3v1lFsZ:-K8rM7ozTMcFC3v1lFs_:1440527123) ([raw file](https://github.com/shakacode/react_on_rails/blob/ba9ed58fc1d0e93be89f03b14ab02dc6896dd069/docs/additional_reading/updating-dependencies.md#L21)):*
I'd suggest to do `npm outdated` & read CHANGELOGs of major updated packages before actual update.

---

*[docs/additional_reading/updating-dependencies.md, line 23 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/223#-K8rMCY0gMtZKlPDfwkp:-K8rMCY0gMtZKlPDfwkq:533801080) ([raw file](https://github.com/shakacode/react_on_rails/blob/ba9ed58fc1d0e93be89f03b14ab02dc6896dd069/docs/additional_reading/updating-dependencies.md#L23)):*
`npm@3` do it automatically if shrinkwrap file exists.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/223)*

**Comment by mapreal19** [comment]
Reviewed 8 of 32 files at r2.
Review status: 8 of 36 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/223)*

**Comment by justin808** [comment]
@robwise check this out, even though merged.

**Pull request merged**
