### PR TITLE
Add missed react_component_hash functionality

### PR DESCRIPTION
**Pull request by Judahmeek**
When I created #951, I forgot to add the useful functionality from #950 that would ensure that `react_component_hash` worked correctly. When there is a prerendering error, `react_component_hash` should return the result combined with the console logs as a hash even though every prerendering error is returned from `Exec` as a String. Right now, if a prerendering error occurs, `react_component_hash` throws its ["Expected a Hash" error](https://github.com/shakacode/react_on_rails/blob/master/app/helpers/react_on_rails_helper.rb#L140-L142)

Expected Behavior: 
screen_shot_2017-10-19_at_2_55_00_am

Current Behavior:
screen_shot_2017-10-18_at_11_41_39_pm

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/960)

### CODE REVIEW

**Comment by justin808** [comment]
:lgtm:. Ready to merge? and release? Needs a CHANGELOG and doc entry.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[spec/dummy/package.json, line 10 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/960#-Kwr_0keWDWmHT3c5bF6:-Kwr_0keWDWmHT3c5bF7:b-39soph) ([raw file](https://github.com/shakacode/react_on_rails/blob/4af3f11ef7869bad2f39599ed65c6f883da42a8d/spec/dummy/package.json#L10)):*
> ```JSON
>     "lint": "cd client && yarn run lint",
>     "build:clean": "rm -rf public/webpack || true",
>     "build:production:client": "(cd client && yarn run build:production:client --silent)",
> ```

why did this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/960#-:-Kwr_JIKKLrpyNBxgXeS:byt4ih2)*

**Comment by Judahmeek** [comment]
I'd like to get the rest of my PRs reviewed, fixed, approved, and merged before release.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[spec/dummy/package.json, line 10 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/960#-Kwr_0keWDWmHT3c5bF6:-KwwU4J06GypW6KwjvwM:bh1vgq3) ([raw file](https://github.com/shakacode/react_on_rails/blob/4af3f11ef7869bad2f39599ed65c6f883da42a8d/spec/dummy/package.json#L10)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why did this change?
</blockquote></details>

Because with yarn v1, the old syntax sends the `--silent` option to webpack, which then throws an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/960#-:-KwwUPI_EENuOnKRRT3U:bkm7i37)*

**Comment by justin808** [comment]
Why no CHANGELOG.md and doc change, @judahmeek? 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/960#-:-Kwy1_19jJTeX6uHzskx:b-g0dgbj)*

**Comment by Judahmeek** [comment]
My bad, @justin808. For some reason, I was thinking that CHANGELOG updates were only required on release. I forgot about the unreleased section. That said, I don't think any doc changes are required since this PR simply ensured that `react_component_hash` actually returns a hash every time.

Btw, https://github.com/shakacode/react_on_rails/pull/957 is also ready for re-review.

---

Review status: 11 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/960#-:-Kx-l7aCAcZKeI-NsL_c:b-qgtrvg)*

**Comment by justin808** [comment]
:lgtm:

---

Review status: 11 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/960#-:-KxCgCZ_fuYLMmSVa3U8:bnfp4nl)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/960)*

**Pull request merged**
