### PR TITLE
build: trigger on main instead of master

### PR DESCRIPTION
**Pull request by ologbonowiwi**
### Summary

This PR changes the GH Actions triggers from `master` to `main`.

### Pull Request checklist
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._

- [ ] ~Add/update test to cover these changes~
- [ ] Update documentation
- [ ] Update CHANGELOG file

### Other Information

~If any more changes are required, let me know and I can implement it.~
This PR is a kick-off, likely we'll need to open another to make all the changes. 

- - -
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1589)

### CODE REVIEW

**Comment by justin808** [comment]
I'm pretty sure that merging this PR is not the only item, but I could be wrong.

**Comment by ologbonowiwi** [comment]
I agree with you, @justin808. Honestly, this is more of a first step than a concluded work. As I'm not familiar with the codebase, these were my findings, but I'd be happy to add more stuff to this PR

**Comment by Judahmeek** [comment]
@justin808 Github documents the changes you'll have to make in the repo settings here: https://github.com/github/renaming

**Review by G-Rath — CHANGES_REQUESTED** [review]
This looks good, but you also need to update the CircleCI config as that has some references to `master` as well.

**Comment by justin808** [comment]
Did we check the repo for master?

https://github.com/search?q=repo%3Ashakacode%2Freact_on_rails+master&type=code

**Pull request closed without merging**
