### PR TITLE
Replace URI parse with Addressable gem

### PR DESCRIPTION
**Pull request by lucke84**
PR related to issue https://github.com/shakacode/react_on_rails/issues/403

Also, adds the fragment of the requested URI as a attribute of the Rails context.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/405)

### CODE REVIEW

**Comment by justin808** [comment]
Couple comments.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Gemfile, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-KGNvFyR1JYDm7FsdvfW:-KGNvFySU0xN4WJs3P8y:-1051848398) ([raw file](https://github.com/shakacode/react_on_rails/blob/332081ec3c45c40cbd46f132172ed2965c962403/Gemfile#L10)):*
I believe we need to modify the gemspec for a peer dependency.

Did you try to make a new app and see if it works?

We certainly don't want apps that use ReactOnRails to have include this gem.

---

*[app/helpers/react_on_rails_helper.rb, line 342 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-KGNv437F80fi1Hvej4x:-KGNv437F80fi1Hvej4y:786823491) ([raw file](https://github.com/shakacode/react_on_rails/blob/332081ec3c45c40cbd46f132172ed2965c962403/app/helpers/react_on_rails_helper.rb#L342)):*
We need a clear comment in the code as to why we are not using the standard URI.

What problem does this solve. 

Otherwise, this will be confusing to somebody later on.

We can refer to the github issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-:-KGNvVoF_mGFDbCEVS1_:1120263039)*

**Comment by justin808** [comment]
@lucke84 Have you looked into why CI is failing? Maybe rebase on top of master and push to start CI again.

**Comment by lucke84** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/helpers/react_on_rails_helper.rb, line 342 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-KGNv437F80fi1Hvej4x:-KGc4-2ra-lWDBl9sNB4:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/332081ec3c45c40cbd46f132172ed2965c962403/app/helpers/react_on_rails_helper.rb#L342)):*
Done.

---

*[Gemfile, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-KGNvFyR1JYDm7FsdvfW:-KGc45KAk2adeGo4wAd0:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/332081ec3c45c40cbd46f132172ed2965c962403/Gemfile#L10)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/405)*

**Comment by jbhatab** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/405)*

**Comment by jbhatab** [comment]
@justin808 looks good to me if you want to merge it in.

**Comment by justin808** [comment]
Another comment on the addition of the "hash".

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[app/helpers/react_on_rails_helper.rb, line 355 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-KGcxBqNpNZgoC7w_nSe:-KGcxBqNpNZgoC7w_nSf:-275309772) ([raw file](https://github.com/shakacode/react_on_rails/blob/a6fdbccb6a42677e9d623a7b983eb6a10e313b35/app/helpers/react_on_rails_helper.rb#L355)):*
This is a nice addition, actually superb.

however, this needs to be:

1. Match Location api for browser: https://developer.mozilla.org/en-US/docs/Web/API/Location (use Location.hash)
2. Update docs.
3. Provide test of this addition (see related ones).
4. Update PR description
5. Update CHANGELOG with this one. I'll revise the release and date. I'm going to do this with all PR requests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-:-KGcxeWN_bp7XyOziTi6:-2041398981)*

**Comment by lucke84** [comment]
Thanks for the comments, I'd applied some changes (see specific comments).

---

Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/helpers/react_on_rails_helper.rb, line 355 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-KGcxBqNpNZgoC7w_nSe:-KGh7AVCJkPOvvdgw0Eg:-1803604324) ([raw file](https://github.com/shakacode/react_on_rails/blob/a6fdbccb6a42677e9d623a7b983eb6a10e313b35/app/helpers/react_on_rails_helper.rb#L355)):*
I've updated the docs (README and CHANGELOG) and added tests. The PR description already includes the fact that the fragment is included, we can maybe specify it better in the changelog (should I do it or will you?).

I'm not 100% sure what you meant with point 1, do you want the attribute to be called "hash" instead of "fragment"?

BTW, the way we populate the "href" attribute is misleading, as we use request.original_url which does not include the hash/fragment. I added it to the "location" attribute but I'm not sure it's good to leave "href" like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-:-KGh7tv8Tr7pIwYXS7P6:-1016674818)*

**Comment by lucke84** [comment]
I removed the fragment part at all: Addressable is able to recognize it but the fragment is never sent to the server so there's no point in try to read it.

**Comment by justin808** [comment]
:lgtm: 

---

Reviewed 1 of 3 files at r2, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 4 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/405#-:-KGk2rSpBoib3ocS8ocb:980077423)*

**Comment by justin808** [comment]
Thanks @lucke84. Nice job!

**Comment by lucke84** [comment]
Hey @justin808, I was wondering if there's a simple way for you guys to release a new version of the 5.x.y series to include this change. According to the changelog, this change has been added to the 6.x.y series but I don't think you should be forced to upgrade in order to get it (it doesn't seem to be related whatsoever to the breaking changes of version 6, looks to me more like a minor/patch release). What do you think?

**Comment by justin808** [comment]
@lucke84 Most of the changes concern the generator and a tiny bit with the running of tests, as well as some additional bits like yours.

The v6 change is because we have a couple additional config params for the test running.

I'll send you a PR of me updating the https://github.com/shakacode/react-webpack-rails-tutorial/ and if you still feel that this is too major let me know. Give me a few hours.

**Comment by lucke84** [comment]
Sure, take your time 👍  I was just pointing out that those bits and pieces which are not part of bumping a major should have probably been released as minor/patch, hopefully useful suggestion for the next time :)

**Comment by justin808** [comment]
@lucke84 We're following full semantic versioning being pushed in the JS community. In that, **ANY** deprecation or addition of something that needs to change requires a major version bump.

**Pull request merged**
