### PR TITLE
Fixed bug to allow filenames with spaces in assets_precompile.rb

### PR DESCRIPTION
**Pull request by dzirtusss**
#510 moved to a branch

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/513)

### CODE REVIEW

**Comment by justin808** [comment]
@dzirtusss There's no need for a separate PR. You can do a `push -f` to replace what the server has for your old branch. First change the old branch to some new name, then rename this branch to the old name. And then do a push force.

**Comment by justin808** [comment]
It was my mistake in that I asked Sergey to rename his fixes to a branch. The original review comments are in #510. I should have asked Sergey to rebase to origin/master on the remote, which means creating a named remote, such as "shakacode" (rather than origin, as that's Sergey's fork) and rebasing on top of that. My bad.

**Comment by justin808** [comment]
:lgtm: I'll update the CHANGELOG.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqU5498T7_R9JmK91-:-KOqU5498T7_R9JmK910:b38yxii) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/CHANGELOG.md#L10)):*
> ```Markdown
> - React on Rails server rendering now supports contexts outside of browser rendering, such as ActionMailer templates [#486](https://github.com/shakacode/react_on_rails/pull/486) by [eacaps](https://github.com/eacaps).
> - React on Rails now correctly parses single-digit version strings from package.json [#491](https://github.com/shakacode/react_on_rails/pull/491) by [samphilipd ](https://github.com/samphilipd ).
> - Fixed assets symlinking to correctly use filenames with spaces [#510](https://github.com/shakacode/react_on_rails/pull/510) 
> ```

Update this to 513. I'll do this. And we should have the author!

---

*[lib/react_on_rails/assets_precompile.rb, line 46 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqU2Yzp8wrCeWVCtuW:-KOqU2Yzp8wrCeWVCtuX:b-8fx2u7) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/lib/react_on_rails/assets_precompile.rb#L46)):*
> ```Ruby
>         FileUtils.chdir(dest_path) do
>           File.symlink(target_filename, symlink_filename)
>         end
> ```

:+1: 

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 29 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqUCgU8KVSR7FJFbs9:-KOqUCgU8KVSR7FJFbsA:b68ycsb) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/spec/react_on_rails/assets_precompile_spec.rb#L29)):*
> ```Ruby
>                         .symlink_file(filename, digest_filename)
> 
>         expect(File.readlink(assets_path.join(digest_filename)).to_s).to eq(filename)
> ```

It's worth noting that digest_filename and filename are all relative paths in the manifest.

I would have probably kept in the removed test that verified that confirms the value of readLink is not the absolute path of filename. Then again, it's clear from the code a few lines above that calls File.basename. :smile: 

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 40 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqUu1riJlOPLpGHNte:-KOqUu1riJlOPLpGHNtf:b-8ligz5) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/spec/react_on_rails/assets_precompile_spec.rb#L40)):*
> ```Ruby
>         expect(assets_path.join(digest_filename).lstat.symlink?).to be true
>         expect(File.identical?(assets_path.join(filename),
>                                assets_path.join(digest_filename))).to be true
> ```

Critical that we fixed this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOqUxZLLnWo_aY_RWCZ:b6l8qz1)*

**Comment by dzirtusss** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqU5498T7_R9JmK91-:-KOsGL0xeCQl9Vtz-kOM:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/CHANGELOG.md#L10)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Update this to 513. I'll do this. And we should have the author!
</details>
Done.

---

*[lib/react_on_rails/assets_precompile.rb, line 46 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqU2Yzp8wrCeWVCtuW:-KOsCkMGa4w1cEMLNdz7:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/lib/react_on_rails/assets_precompile.rb#L46)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> :+1: 
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 29 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqUCgU8KVSR7FJFbs9:-KOsRqSBLPOUxJ56Cbzm:b-bq53lu) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/spec/react_on_rails/assets_precompile_spec.rb#L29)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> It's worth noting that digest_filename and filename are all relative paths in the manifest.
> 
> I would have probably kept in the removed test that verified that confirms the value of readLink is not the absolute path of filename. Then again, it's clear from the code a few lines above that calls File.basename. :smile: 
</details>
In #510 you commented - *If we test for equality, that's a bit more of a sure thing. Only having an "expectation not" can result in a test that passes due to an error in writing the test.*

Actually I totally agree with that comment. To be double-proof we can have both expects:
```
expect.to eq(filename)          # positive expectation
expect.not_to eq(global_path)   # negative expectation
```

Than we check for both filename and path.

Should do like this?

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 40 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqUu1riJlOPLpGHNte:-KOsWvaNbioxfvbwOnjA:b-k9y7ni) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/spec/react_on_rails/assets_precompile_spec.rb#L40)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Critical that we fixed this.
</details>
I'm really-really sorry I don't understand here. What would U like to fix here?

We have exact same test (original) at L:12 for filename without spaces, and then this new one, which specially tests for fix condition - for filename with spaces `"temp file"`. Test is exact replica of original only with spaces in filenames.

If U want to test it on old source without fix, then first test will pass and this will fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513)*

**Comment by dzirtusss** [comment]
ok

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOsZm0MpjJCQ3GU0rhx:b32wtd)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CHANGELOG.md, line 10 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOs_uxdBDnxqXrlXmaL:-KOs_uxdBDnxqXrlXmaM:b-xwtj1j) ([raw file](https://github.com/shakacode/react_on_rails/blob/799b60a077bd488399ac73183d10c7ff52256251/CHANGELOG.md#L10)):*
> ```Markdown
> - React on Rails server rendering now supports contexts outside of browser rendering, such as ActionMailer templates [#486](https://github.com/shakacode/react_on_rails/pull/486) by [eacaps](https://github.com/eacaps).
> - React on Rails now correctly parses single-digit version strings from package.json [#491](https://github.com/shakacode/react_on_rails/pull/491) by [samphilipd ](https://github.com/samphilipd ).
> - Fixed assets symlinking to correctly use filenames with spaces. Begining in [#510](https://github.com/shakacode/react_on_rails/pull/510), end in [#513](https://github.com/shakacode/react_on_rails/pull/513) by Sergey Tarasov [https://github.com/dzirtusss]  
> ```

see other names in the changelog for the format

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513)*

**Comment by justin808** [comment]
couple comments

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 29 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqUCgU8KVSR7FJFbs9:-KOsa3V6U7hdsqbL7Asu:b-80tlqk) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/spec/react_on_rails/assets_precompile_spec.rb#L29)):*
<details><summary><i>Previously, dzirtusss (Sergey Tarasov) wrote…</i></summary>
> In #510 you commented - *If we test for equality, that's a bit more of a sure thing. Only having an "expectation not" can result in a test that passes due to an error in writing the test.*
> 
> Actually I totally agree with that comment. To be double-proof we can have both expects:
> ```
> expect.to eq(filename)          # positive expectation
> expect.not_to eq(global_path)   # negative expectation
> ```
> 
> Than we check for both filename and path.
> 
> Should do like this?
> 
</details>
Sure.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 40 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqUu1riJlOPLpGHNte:-KOsa600S8XpX_7d2-yc:begreux) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/spec/react_on_rails/assets_precompile_spec.rb#L40)):*
<details><summary><i>Previously, dzirtusss (Sergey Tarasov) wrote…</i></summary>
> I'm really-really sorry I don't understand here. What would U like to fix here?
> 
> We have exact same test (original) at L:12 for filename without spaces, and then this new one, which specially tests for fix condition - for filename with spaces `"temp file"`. Test is exact replica of original only with spaces in filenames.
> 
> If U want to test it on old source without fix, then first test will pass and this will fail.
</details>
I'm saying :+1:  on this fix. Great job. That's it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOsaB99iVZnimuxmfU8:b11p8z3)*

**Comment by dzirtusss** [comment]
Done

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGELOG.md, line 10 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOs_uxdBDnxqXrlXmaL:-KOscjVrX6q2pjxOXIM-:bb6un1j) ([raw file](https://github.com/shakacode/react_on_rails/blob/799b60a077bd488399ac73183d10c7ff52256251/CHANGELOG.md#L10)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> see other names in the changelog for the format
</details>
Done

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 29 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqUCgU8KVSR7FJFbs9:-KOscDTyPR0p9OzJ3-X8:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/spec/react_on_rails/assets_precompile_spec.rb#L29)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Sure.
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 40 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOqUu1riJlOPLpGHNte:-KOsbjnxYdLu9UqGHvLx:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/bfc8b7bc57945ff0833f16f2f7ea2b48e7504137/spec/react_on_rails/assets_precompile_spec.rb#L40)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> I'm saying :+1:  on this fix. Great job. That's it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOscpeYJYeWDS1CAYxR:bb6un1j)*

**Comment by justin808** [comment]
one more comment

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 10 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOsf_M9U55dQ-IYnAWw:-KOsf_M9U55dQ-IYnAWx:b-awtdfe) ([raw file](https://github.com/shakacode/react_on_rails/blob/e2ad3e9708e89409c3384edb38ce05e8ad0d4dfb/CHANGELOG.md#L10)):*
> ```Markdown
> - React on Rails server rendering now supports contexts outside of browser rendering, such as ActionMailer templates [#486](https://github.com/shakacode/react_on_rails/pull/486) by [eacaps](https://github.com/eacaps).
> - React on Rails now correctly parses single-digit version strings from package.json [#491](https://github.com/shakacode/react_on_rails/pull/491) by [samphilipd ](https://github.com/samphilipd ).
> - Fixed assets symlinking to correctly use filenames with spaces. Begining in [#510](https://github.com/shakacode/react_on_rails/pull/510), ending in [#513](https://github.com/shakacode/react_on_rails/pull/513) by [Sergey Tarasov](https://github.com/dzirtusss) 
> ```

almost...see other entries. We use the github id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOsfisZfgttUFl7b1Lk:bc9us5v)*

**Comment by justin808** [comment]
Be sure to run `rake lint` before pushing!

Offenses:
spec/react_on_rails/assets_precompile_spec.rb:31:13: C: Style/MultilineMethodCallIndentation: Use 2 (not 4) spaces for indenting an expression spanning multiple lines.
            .not_to eq(File.expand_path(assets_path.join(filename)).to_s)
            ^^^^^^^
91 files inspected, 1 offense detected
rake aborted!
Command failed with status (1): [cd /home/travis/build/shakacode/react_on_r...]
/home/travis/build/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `block in sh_in_dir'
/home/travis/build/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `each'
/home/travis/build/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `sh_in_dir'
/home/travis/build/shakacode/react_on_rails/rakelib/lint.rake:7:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => lint => lint:lint => lint:rubocop
(See full trace by running task with --trace)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOsixnFU-aJ8zer6hJ5:b84ikgi)*

**Comment by dzirtusss** [comment]
Done

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 10 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-KOsf_M9U55dQ-IYnAWw:-KOsoAjNGZUUPCWlWGSJ:b-5vq23e) ([raw file](https://github.com/shakacode/react_on_rails/blob/e2ad3e9708e89409c3384edb38ce05e8ad0d4dfb/CHANGELOG.md#L10)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> almost...see other entries. We use the github id.
</details>
:confused:  Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOsnUGs0pLmopGVgJZ2:bb6un1j)*

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOsq2R4pCNje4utSOni:bnfp4nl)*

**Comment by dzirtusss** [comment]
Done, squashed commits

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOv5DGn3jWiXmcHbiSv:bkto99x)*

**Comment by justin808** [comment]
:lgtm_strong: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/513#-:-KOv7tAqIWvm3sgLxr2M:b-uwkowd)*

**Pull request merged**
