### PR TITLE
Update start steps in README

### PR DESCRIPTION
**Pull request by alexeyr**
Partial fix for #1442

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1443)

### CODE REVIEW

**Comment by justin808** [comment]
@alexeyr 

## Upgrade to 6.2.1 of shakapacker. 

6.2.0 was broken.


## Details

See the failed test links.

I think the update of shakapacker broke the test.

```
Hello World

====> React On Rails: Checking files in /home/runner/work/react_on_rails/react_on_rails/gen-examples/examples/basic/public/packs-test for outdated/missing bundles based on source_path /home/runner/work/react_on_rails/react_on_rails/gen-examples/examples/basic/app/javascript

  the hello world example works (FAILED - 1)

Failures:

  1) Hello World the hello world example works
     Failure/Error: Webpacker.config.public_manifest_path.exist?

     NoMethodError:
       undefined method `public_manifest_path' for #<Webpacker::Configuration:0x000055a94fe403d8>
       Did you mean?  public_path
     # /home/runner/work/react_on_rails/react_on_rails/lib/react_on_rails/webpacker_utils.rb:54:in `manifest_exists?'
     # /home/runner/work/react_on_rails/react_on_rails/lib/react_on_rails/test_helper/webpack_assets_status_checker.rb:30:in `stale_generated_webpack_files'
     # /home/runner/work/react_on_rails/react_on_rails/lib/react_on_rails/test_helper/ensure_assets_compiled.rb:35:in `call'
     # /home/runner/work/react_on_rails/react_on_rails/lib/react_on_rails/test_helper.rb:97:in `ensure_assets_compiled'
     # /home/runner/work/react_on_rails/react_on_rails/lib/react_on_rails/test_helper.rb:39:in `block (2 levels) in configure_rspec_to_compile_assets'

Finished in 0.00235 seconds (files took 2.72 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/system/hello_world_spec.rb:6 # Hello World the hello world example works

rake aborted!
Command failed with status (1): [cd /home/runner/work/react_on_rails/react_...]
/home/runner/work/react_on_rails/react_on_rails/rakelib/task_helpers.rb:21:in `block in sh_in_dir'
/home/runner/work/react_on_rails/react_on_rails/rakelib/task_helpers.rb:21:in `each'
/home/runner/work/react_on_rails/react_on_rails/rakelib/task_helpers.rb:21:in `sh_in_dir'
/home/runner/work/react_on_rails/react_on_rails/rakelib/run_rspec.rake:111:in `run_tests_in'
/home/runner/work/react_on_rails/react_on_rails/rakelib/run_rspec.rake:41:in `block (3 levels) in <top (required)>'
/home/runner/work/react_on_rails/react_on_rails/rakelib/run_rspec.rake:47:in `block (3 levels) in <top (required)>'
/home/runner/work/react_on_rails/react_on_rails/rakelib/run_rspec.rake:47:in `each'
/home/runner/work/react_on_rails/react_on_rails/rakelib/run_rspec.rake:47:in `block (2 levels) in <top (required)>'
/home/runner/work/react_on_rails/react_on_rails/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `<main>'
Tasks: TOP => run_rspec:example_basic
(See full trace by running task with --trace)
```


See this commit: https://github.com/shakacode/shakapacker/commit/b4ecde115a9676ae23b0c70a2118db65bcdec3f2

**Comment by alexeyr** [comment]
@justin808 I updated, but still seem to have the same problem (and so does #1446, though it also uses 6.2.1 according to logs). Is 6.2.1 still broken?

**Comment by justin808** [comment]
@Judahmeek can you get this one ready for merge?

**Comment by alexeyr** [comment]
@justin808 Rebased, can you approve it now?

**Pull request merged**
