### PR TITLE
Add support for single digit version strings, closes #489

### LINKED ISSUE #489: Version checker cannot cope with single digit strings in package.json
Steps to reproduce:
1. In client/package.json specify version: `"react-on-rails": "^6"`
2. In root path run `bundle exec rails server`

Expected behaviour:
- Should run fine

Actual behaviour:
- Crashes with:

```
/Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.0.5/lib/react_on_rails/version_checker.rb:69:in `major': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.0.5/lib/react_on_rails/version_checker.rb:21:in `warn_if_gem_and_node_package_versions_differ'
    from /Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.0.5/lib/react_on_rails/engine.rb:5:in `block in <class:Engine>'
    from /Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:396:in `instance_exec'
    from /Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:396:in `block in make_lambda'
(... trace truncated ...)
```

The problem is on `version_checker.rb` line 69. The regex should probably be more like this: `raw.match(/(\d+)(\.|\z)/)[1]`

### PR DESCRIPTION
**Pull request by samphilipd**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/491)

### CODE REVIEW

**Comment by justin808** [comment]
👍 Thanks @samphilipd!

Looks 💯.

I'll merge and release once this passes CI.

**Comment by justin808** [comment]
@samphilipd One small request:

> Provide changelog entry in the unreleased section of the CHANGELOG.md.

Per https://github.com/shakacode/react_on_rails/blob/master/docs/contributor-info/contributing.md

Please squash and push commit on top of master and I'll merge and release. 

Thanks again @samphilipd!

**Comment by justin808** [comment]
@samphilipd can you please rebase your commit on top of master and take a look a the ci results:

**Comment by justin808** [comment]
@samphilipd Can you please rebase this on top of master and then I can merge this and cut a release.

**Comment by samphilipd** [comment]
Hi @justin808 I don't understand what you're asking, I have rebased on top of master?

**Comment by justin808** [comment]
@samnang A number of changes have gone in since you did that.

**Comment by samphilipd** [comment]
@justin808 I think I fixed it?

**Comment by justin808** [comment]
Thanks @samphilipd!

**Pull request merged**
