### PR TITLE
Update assets_precompile_spec.rb

### PR DESCRIPTION
**Pull request by dzirtusss**
Symlink tests with tempfs. Please don't kill - I'm new to ruby/rspec/git world. Waiting for any comments.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/490)

### CODE REVIEW

**Comment by justin808** [comment]
@dzirtusss **GREAT START!**

@mapreal19 can you please do a quick review.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdgGW-LYLXmB7Tiwmz:-KNdgGW-LYLXmB7Tiwn-:15718723) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L10)):*
> ```Ruby
>   RSpec.describe AssetsPrecompile do
> 
>     assets_path = Pathname.new(Dir.mktmpdir)
> ```

this should either be a let block or a before block (before block requires the use of @assets_path)

I'd suggest  a let block.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 18 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdfFe4maHvRvwrMHHq:-KNdfFe4maHvRvwrMHHr:-609998702) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L18)):*
> ```Ruby
>         AssetsPrecompile.new(assets_path: assets_path).
>               symlink_file(filename,digest_filename)
>         
> ```

be sure to run `rubocop -a` to autofix!

you will need to run 

```
rake lint
```

the red dots mean spaces. 

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 51 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdhEx56OGs8Kt1swku:-KNdhEx56OGs8Kt1swkv:202093650) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L51)):*
> ```Ruby
>         f.close
>       
>         File.new(assets_path.join(digest_filename),"w").close
> ```

How about http://apidock.com/ruby/FileUtils/touch/class

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 95 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdi0XisRFYqlBrLdm7:-KNdi0XisRFYqlBrLdm8:1828357297) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L95)):*
> ```Ruby
> 
> #### Problems here because in clobber dir = Rails.root.join(@generated_assets_dir)
> #### which is not tmpdir, meaning we need to update real fs?
> ```

this should be a temp dir

so not sure why this won't work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-:-KNdi9XeQzAp0ag5pI0s:1691177136)*

**Comment by mapreal19** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdgGW-LYLXmB7Tiwmz:-KNfGrZw7qMteUQOXp7B:-2036345700) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L10)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> this should either be a let block or a before block (before block requires the use of @assets_path)
> 
> I'd suggest  a let block.
</details>
let :+1: 

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 12 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNfHRh32ZilaJM2XKPp:-KNfHRh32ZilaJM2XKPq:968063257) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L12)):*
> ```Ruby
>     assets_path = Pathname.new(Dir.mktmpdir)
>     
>     describe "symlink_file" do
> ```

here `describe "#symlink_file"`

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 24 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNfH9AB2FZrx8jyZCCg:-KNfH9AB2FZrx8jyZCCh:1843505994) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L24)):*
> ```Ruby
>       end
>       
>       it "creates a proper symlink if nested" do
> ```

better to put this inside a context "when nested"

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 40 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNfHcuoRmTn4kGr9siu:-KNfHcuoRmTn4kGr9siv:1463434147) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L40)):*
> ```Ruby
>     describe "symlink_non_digested_assets" do
>       it "creates the necessary symlinks" do
>         manifest_filename = "manifest-alfa.json" 
> ```

create contexts for every case. It is preferable to have few expectations per each spec

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 86 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNfIP6jyZwKmdXtyOdx:-KNfIP6jyZwKmdXtyOdy:-462506547) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L86)):*
> ```Ruby
>         a.delete_broken_symlinks
>         
>         expect(assets_path.join(filename).exist?).to be false
> ```

maybe you could use this matcher here https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/exist-matcher

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490)*

**Comment by justin808** [comment]
@dzirtusss Let's get the suggestions implemented and get your change merged. Thanks again!

**Comment by dzirtusss** [comment]
I have added all the changes (+rubocop) except clobber test

Last test for clobber still have problems. In **assets_precompile.rb** in clobber we have ABSOLUTE FIXED path as follows: _dir = Rails.root.join(@generated_assets_dir)_ in all other places paths are RELATIVE and are set up in _initialize_ method. So we can substitute them with any tempfs dir we want. Inside clobber it is substituted to this: _Rails.root.join(tempdir)_ which is NOT our testing tempdir

Plus for some reason I didn't understand yet, while testing on my system _Rails.root is nil_ and thus generates no method error (which can be my setup mistake). But, if it is right to do smth like: _dir = @generated_assets_dir_  in clobber presuming it has full path, than everything is easy to update.

Please advise on the right logic.

**Comment by dzirtusss** [comment]
As for introducing context do U mean smth like this? Thanks

    describe "symlink_non_digested_assets" do
      context "creates the necessary symlinks" do
        let (:manifest_filename) { "manifest-alfa.json" }
        let (:digest_filename) { "alfa.12345.js" }
        let (:nondigest_filename) { "alfa.js" }
        let (:digest_bad_filename) { "alfa.12345.jsx" }
        let (:nondigest_bad_filename) { "alfa.jsx" }

        before (:each) do
          Dir.chdir(assets_path)
          f = File.new(assets_path.join(manifest_filename), "w")
          f.write("{\"assets\":{\"#{nondigest_filename}\": \"#{digest_filename}\"}}")
          f.close
        end

        it "creates right symlink" do
          FileUtils.touch assets_path.join(digest_filename)
          
          AssetsPrecompile.new(assets_path: assets_path,
                             symlink_non_digested_assets_regex: Regexp.new('.*\.js$'))
                        .symlink_non_digested_assets

          expect(assets_path.join(digest_filename).exist?).to be true
          expect(assets_path.join(nondigest_filename).lstat.symlink?).to be true
          expect(File.identical?(assets_path.join(nondigest_filename),
                               assets_path.join(digest_filename))).to be true
        end

        it "creates right symlink with .gz" do
          FileUtils.touch assets_path.join("#{digest_filename}.gz")

          AssetsPrecompile.new(assets_path: assets_path,
                             symlink_non_digested_assets_regex: Regexp.new('.*\.js$'))
                        .symlink_non_digested_assets

          expect(assets_path.join("#{digest_filename}.gz").exist?).to be true
          expect(assets_path.join("#{nondigest_filename}.gz").lstat.symlink?).to be true
          expect(File.identical?(assets_path.join("#{nondigest_filename}.gz"),
                               assets_path.join("#{digest_filename}.gz"))).to be true
        end

        it "doesn't create wrong symlink" do
          FileUtils.touch assets_path.join(digest_bad_filename)

          AssetsPrecompile.new(assets_path: assets_path,
                             symlink_non_digested_assets_regex: Regexp.new('.*\.js$'))
                        .symlink_non_digested_assets

          expect(assets_path.join(nondigest_bad_filename).exist?).to be false
        end
      end
    end

**Comment by mapreal19** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 58 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNlu3VGDucX-yCRikot:-KNlu3VH98wfnVfbLS6u:-1112490202) ([raw file](https://github.com/shakacode/react_on_rails/blob/e33611fb182c6f2ad6cb59de8c99d87b290b384d/spec/react_on_rails/assets_precompile_spec.rb#L58)):*
> ```Ruby
>                         .symlink_non_digested_assets
> 
>         # testing for alfa.js symlink
> ```

@dzirtusss what I meant is having a context per each blocks of code here. Instead of having comments we could have something like:

```
context "correct nondigest filename" do ... end

context "zipped nondigest filename" do ... end

context "wrong nondigest filename" do ... end
```

Also we try to follow the four-phase test (See: https://robots.thoughtbot.com/four-phase-test) instead of abusing the use of `let` & `before`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490)*

**Comment by dzirtusss** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 10 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdgGW-LYLXmB7Tiwmz:-KNm7YcU0YBcPIBlpF7N:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L10)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary>
> let :+1: 
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 12 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNfHRh32ZilaJM2XKPp:-KNm7eTlHeBOjPS-APPF:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L12)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary>
> here `describe "#symlink_file"`
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 18 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdfFe4maHvRvwrMHHq:-KNm7fgUjZrqSCb09ZZY:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L18)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> be sure to run `rubocop -a` to autofix!
> 
> you will need to run 
> 
> ```
> rake lint
> ```
> 
> the red dots mean spaces. 
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 24 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNfH9AB2FZrx8jyZCCg:-KNm7j3BNgYd97bnxpI5:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L24)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary>
> better to put this inside a context "when nested"
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 51 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdhEx56OGs8Kt1swku:-KNm7l19vyMD0HNuqCvs:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L51)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> How about http://apidock.com/ruby/FileUtils/touch/class
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 86 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNfIP6jyZwKmdXtyOdx:-KNm7tvQYxaNgudzn7Hj:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L86)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary>
> maybe you could use this matcher here https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/exist-matcher
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490)*

**Comment by dzirtusss** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 40 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNfHcuoRmTn4kGr9siu:-KNnBOUpc25_zcUEaFwc:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L40)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary>
> create contexts for every case. It is preferable to have few expectations per each spec
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 58 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNlu3VGDucX-yCRikot:-KNnBQ1LC0EW8PW3d9K4:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/e33611fb182c6f2ad6cb59de8c99d87b290b384d/spec/react_on_rails/assets_precompile_spec.rb#L58)):*
<details><summary><i>Previously, mapreal19 (Mario Pérez) wrote…</i></summary>
> @dzirtusss what I meant is having a context per each blocks of code here. Instead of having comments we could have something like:
> 
> ```
> context "correct nondigest filename" do ... end
> 
> context "zipped nondigest filename" do ... end
> 
> context "wrong nondigest filename" do ... end
> ```
> 
> Also we try to follow the four-phase test (See: https://robots.thoughtbot.com/four-phase-test) instead of abusing the use of `let` & `before`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490)*

**Comment by dzirtusss** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 95 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNdi0XisRFYqlBrLdm7:-KNpxr4GrE2Z6fj7AF6B:-1068918007) ([raw file](https://github.com/shakacode/react_on_rails/blob/56ed4988e4b6a9f0a3b0520f4a05616070f5eff4/spec/react_on_rails/assets_precompile_spec.rb#L95)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> this should be a temp dir
> 
> so not sure why this won't work
</details>
All time getting `Rails.root == nil` in tests, seem to miss some require or initialization. Need help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490)*

**Comment by mapreal19** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490)*

**Comment by justin808** [comment]
One small comment.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 102 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNtS44A9MYJgX_abLho:-KNtS44Bfq-_Se8IfdrD:-1990596672) ([raw file](https://github.com/shakacode/react_on_rails/blob/cb83b3b1c5dc4ad387a70635d1952e7efc5826e7/spec/react_on_rails/assets_precompile_spec.rb#L102)):*
> ```Ruby
>         expect(file).to exist
>         AssetsPrecompile.new(assets_path: assets_path,
>                              generated_assets_dir: assets_path).clobber
> ```

@dzirtusss 

the generated_assets_dir should not be inside of the assets_path.

See this for the generated assets dir: https://github.com/shakacode/react_on_rails/blob/1e7ab23daf95df4e7c8d8f39600cfb0f85e3bc8d/spec/dummy/config/initializers/react_on_rails.rb#L14


Since we're only using the generated_assets_dir here, then just don't pass the param for the assets_path.

```ruby
    def clobber
      dir = Rails.root.join(@generated_assets_dir)
      if dir.present? && File.directory?(dir)
        puts "Deleting files in directory #{dir}"
        FileUtils.rm_r(Dir.glob(Rails.root.join("#{@generated_assets_dir}/*")))
      else
        puts "Could not find generated_assets_dir #{dir} defined in react_on_rails initializer: "
      end
    end
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-:-KNtUUpJYDY9gTDArYB2:-1121150073)*

**Comment by justin808** [comment]
@dzirtusss Please see why the travis build failed per the link in "checks".

**Comment by dzirtusss** [comment]
Rails.root was nil. Didn't know how to stub )) now ok

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 102 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNtS44A9MYJgX_abLho:-KO1H694nO7UQyR_sB1T:-1575475740) ([raw file](https://github.com/shakacode/react_on_rails/blob/cb83b3b1c5dc4ad387a70635d1952e7efc5826e7/spec/react_on_rails/assets_precompile_spec.rb#L102)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> @dzirtusss 
> 
> the generated_assets_dir should not be inside of the assets_path.
> 
> See this for the generated assets dir: https://github.com/shakacode/react_on_rails/blob/1e7ab23daf95df4e7c8d8f39600cfb0f85e3bc8d/spec/dummy/config/initializers/react_on_rails.rb#L14
> 
> 
> Since we're only using the generated_assets_dir here, then just don't pass the param for the assets_path.
> 
> ```ruby
>     def clobber
>       dir = Rails.root.join(@generated_assets_dir)
>       if dir.present? && File.directory?(dir)
>         puts "Deleting files in directory #{dir}"
>         FileUtils.rm_r(Dir.glob(Rails.root.join("#{@generated_assets_dir}/*")))
>       else
>         puts "Could not find generated_assets_dir #{dir} defined in react_on_rails initializer: "
>       end
>     end
> ```
</details>
Done. Rails.root was nil. Didn't know how to stub )) now ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-:-KO1GtIMtkXqQVn9xsXM:478791288)*

**Comment by dzirtusss** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 102 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-KNtS44A9MYJgX_abLho:-KO1IXF-4zI24i3oOEBs:529875157) ([raw file](https://github.com/shakacode/react_on_rails/blob/cb83b3b1c5dc4ad387a70635d1952e7efc5826e7/spec/react_on_rails/assets_precompile_spec.rb#L102)):*
<details><summary><i>Previously, dzirtusss (Sergey) wrote…</i></summary>
> Done. Rails.root was nil. Didn't know how to stub )) now ok
</details>
Don't passing `assets_path` generates nil error, because `assets_path.presence || default_asset_path` where it is called same `Rails` which is nil or stub

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490)*

**Comment by justin808** [comment]
:lgtm:

Thanks @dzirtusss!

Great job! 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/490#-:-KO2U1otrwxnszq7Tw2c:137380449)*

**Pull request merged**
