### PR TITLE
fix too early unmount

### PR DESCRIPTION
**Pull request by szyablitsky**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/425)

### CODE REVIEW

**Comment by justin808** [comment]
@szyablitsky This is super awesome! Would you like to create a failing without, passing with test in the `spec/dummy` app? If not, I can try. I will merge your commit into a branch on my machine and then I'll push up a new PR. If you can write a test, that would be AMAZING! Thanks so much!

**Comment by szyablitsky** [comment]
@justin808 testing this can be very tricky because of Capybara's waiting behavior. https://github.com/jnicklas/capybara#asynchronous-javascript-ajax-and-friends
Also rerendering actually happens every time. But depending on cache state time between `turbolinks:before-cache` and `turbolinks:before-render` can be zero (in which case rerendering is not visible) or it can be big enough to see the empty space in place of unmounted component.

**Comment by justin808** [comment]
@szyablitsky At the least, we can put in an example that confirms this manually, in `spec/dummy`

I'm also going to push an RC with this fix and test it in my branch for the https://github.com/shakacode/react-webpack-rails-tutorial/.

**Comment by justin808** [comment]
I merged this change here: 

https://github.com/shakacode/react_on_rails/commit/40553fc58976370ea23d08ce69511b869c4268d9

We should still have an example of this in `spec/dummy`.

**Pull request closed without merging**
