### PR TITLE
Fix file exists check for server bundle, which returns true for a dir.

### PR DESCRIPTION
**Pull request by timscott**
NOTE: Similar bugs may exist elsewhere in the code.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/386)

### CODE REVIEW

**Comment by justin808** [comment]
http://www.gethourglass.com/blog/ruby-check-if-file-exists.html

Interesting one.

@samnang @mapreal19 Do you two like this change?

**Comment by timscott** [comment]
@justin808  Ha, that's the same blog post I found. I did not know about this behavior of ```File.exist?``` I would call surprising.

**Comment by mapreal19** [comment]
Looks good. Didn't know about this either. Is it possible to add a spec that confirm this bug?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/386#-:-KFNucqCwbf9ZlNoDnqT:-536050799)*

**Comment by samnang** [comment]
Good catch. On Unix, everything is a file https://en.wikipedia.org/wiki/Everything_is_a_file

**Comment by justin808** [comment]
Thanks @timscott!

**Pull request merged**
