### PR TITLE
Fixed bug to allow filenames with spaces in assets_precompile.rb

### LINKED ISSUE #505: Asset precompilation stage cannot cope with filenames with spaces in them
Just updated `react_on_rails` to 6.0.5 and now I see this error precompiling assets:

```
React On Rails: Symlinking /Users/sam/code/projects/foo/public/assets/face on grey-93536981da08346bc1270aea2bcb27786769c3eb7b8f9966725a3b4bd3405202.png to /Users/sam/code/projects/foo/public/assets/face on grey.png
ln: grey.png: No such file or directory
```

Seems like React on Rails chokes on filenames with spaces in them.

### PR DESCRIPTION
**Pull request by dzirtusss**
Fixed bug to allow filenames with spaces in assets_precompile.rb its test spec, closes #505

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/510)

### CODE REVIEW

**Comment by justin808** [comment]
@dzirtusss Tip: Feel free to review your own PR first putting in questions and comments. These are useful to the reviewer and it's a place to put discussions/comments that don't deserve to be in code comments.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/react_on_rails/assets_precompile.rb, line 44 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONPx7GNxkah5etK5CV:-KONPx7GNxkah5etK5CW:958045339) ([raw file](https://github.com/shakacode/react_on_rails/blob/6291e54fdb9037c51f1f1736f4e5c51470af74e1/lib/react_on_rails/assets_precompile.rb#L44)):*
> ```Ruby
>         puts "React On Rails: Symlinking \"#{target}\" to \"#{symlink}\""
>         dest_path = File.join(@assets_path, target_sub_path)
>         FileUtils.chdir(dest_path)
> ```

we should probably use the block syntax so that the chdir only applies to the code inside of the block.

---

*[lib/react_on_rails/assets_precompile.rb, line 45 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONQ2VUGoMWTaXbatRf:-KONQ2VVVvoWSPxBb2BT:-2040019019) ([raw file](https://github.com/shakacode/react_on_rails/blob/6291e54fdb9037c51f1f1736f4e5c51470af74e1/lib/react_on_rails/assets_precompile.rb#L45)):*
> ```Ruby
>         dest_path = File.join(@assets_path, target_sub_path)
>         FileUtils.chdir(dest_path)
>         File.symlink(File.expand_path(target_filename), File.expand_path(symlink_filename))
> ```

be careful with the file expand

we need a test to ensure that we're never using absolute paths

I suspect that you don't need the expand_path.

please be sure to verify this in the tests

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 28 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONQIru0apQNgewUFfG:-KONQIru0apQNgewUFfH:-1483738419) ([raw file](https://github.com/shakacode/react_on_rails/blob/6291e54fdb9037c51f1f1736f4e5c51470af74e1/spec/react_on_rails/assets_precompile_spec.rb#L28)):*
> ```Ruby
>                                                                assets_path.join("test images")))
>         digest_filename = "#{filename} digest"
>         AssetsPrecompile.new(assets_path: assets_path)
> ```

if you ever check a symlink into github, then you can see the difference between the symlink that is the minimum relative path versus a full path.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 33 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONQTLYobQXhLFu-8Sl:-KONQTLYobQXhLFu-8Sm:-1173858832) ([raw file](https://github.com/shakacode/react_on_rails/blob/6291e54fdb9037c51f1f1736f4e5c51470af74e1/spec/react_on_rails/assets_precompile_spec.rb#L33)):*
> ```Ruby
>         expect(assets_path.join(digest_filename).lstat.symlink?).to be true
>         expect(File.identical?(assets_path.join(filename),
>                                assets_path.join(digest_filename))).to be true
> ```

Ideally, I'd like to see new tests with a file name that does not have spaces, so we can run the tests without the fix and see just these tests fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-:-KONQbFVsMb8vGvddRfo:1673672238)*

**Comment by justin808** [comment]
:lgtm:

Thanks @dzirtusss 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/assets_precompile.rb, line 45 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONQ2VUGoMWTaXbatRf:-KOdWioE6nG5tZGdgqaY:bbcztd0) ([raw file](https://github.com/shakacode/react_on_rails/blob/5695c820ad000c2f544070d82bfe91faa5ff072a/lib/react_on_rails/assets_precompile.rb#L45)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> be careful with the file expand
> 
> we need a test to ensure that we're never using absolute paths
> 
> I suspect that you don't need the expand_path.
> 
> please be sure to verify this in the tests
</details>
@dzirtusss Please mark addressed issues as "done" in reviewable.io. Thanks.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 31 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KOdWycpb31GbzI8prpW:-KOdWycpb31GbzI8prpX:bqzjfi1) ([raw file](https://github.com/shakacode/react_on_rails/blob/d03cb710faa9076268ff1624fdacc682cf492bdf/spec/react_on_rails/assets_precompile_spec.rb#L31)):*
> ```Ruby
>         expect(File.readlink(assets_path.join(digest_filename)).to_s)
>           .not_to eq(File.expand_path(assets_path.join(filename)).to_s)
>       end
> ```

CC: @alleycat-at-git Check this out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-:-KOdX1bk2SRQP1UkovEf:bm10kuf)*

**Comment by justin808** [comment]
@dzirtusss Please see https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md.


We need to update the CHANGELOG.md.

Please add that entry and rebase on top of master.

**Comment by dzirtusss** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/assets_precompile.rb, line 44 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONPx7GNxkah5etK5CV:-KOQnxXBnAzG5G_ZloUm:b-fidxxn) ([raw file](https://github.com/shakacode/react_on_rails/blob/5695c820ad000c2f544070d82bfe91faa5ff072a/lib/react_on_rails/assets_precompile.rb#L44)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> we should probably use the block syntax so that the chdir only applies to the code inside of the block.
</details>
Agree 200%. chdir in block really interesting and easy construct, saves efforts and get clean code

---

*[lib/react_on_rails/assets_precompile.rb, line 45 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONQ2VUGoMWTaXbatRf:-KOQy7XAKbVITPPvGi8h:bvfklnn) ([raw file](https://github.com/shakacode/react_on_rails/blob/5695c820ad000c2f544070d82bfe91faa5ff072a/lib/react_on_rails/assets_precompile.rb#L45)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> be careful with the file expand
> 
> we need a test to ensure that we're never using absolute paths
> 
> I suspect that you don't need the expand_path.
> 
> please be sure to verify this in the tests
</details>
Agree.  I don't need expand_path - added it to get global symlink. Now updated to local. Check for local/global path also added to test.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 28 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONQIru0apQNgewUFfG:-KOR-Xyee27q1yk5wt__:bc3x9id) ([raw file](https://github.com/shakacode/react_on_rails/blob/5695c820ad000c2f544070d82bfe91faa5ff072a/spec/react_on_rails/assets_precompile_spec.rb#L28)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> if you ever check a symlink into github, then you can see the difference between the symlink that is the minimum relative path versus a full path.
</details>
Agree only relative paths for future

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 33 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONQTLYobQXhLFu-8Sl:-KOR7FyF1Cd-C1WYIIRf:b-el5zlk) ([raw file](https://github.com/shakacode/react_on_rails/blob/5695c820ad000c2f544070d82bfe91faa5ff072a/spec/react_on_rails/assets_precompile_spec.rb#L33)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Ideally, I'd like to see new tests with a file name that does not have spaces, so we can run the tests without the fix and see just these tests fail.
</details>
I've splitted tests for 1) space 2) global links as a separate its. Than tested each against its revision. This is what you mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510)*

**Comment by dzirtusss** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/assets_precompile.rb, line 45 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KONQ2VUGoMWTaXbatRf:-KOdpiGhVvrEV88w8biJ:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/5695c820ad000c2f544070d82bfe91faa5ff072a/lib/react_on_rails/assets_precompile.rb#L45)):*
<details><summary><i>Previously, dzirtusss (Sergey Tarasov) wrote…</i></summary>
> Agree.  I don't need expand_path - added it to get global symlink. Now updated to local. Check for local/global path also added to test.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510)*

**Comment by dzirtusss** [comment]
Done

---

Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-:-KOeClvmNZyoOWxciV9j:bb6un1j)*

**Comment by dzirtusss** [comment]
Merge commits

---

Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-:-KOeFlCrn_2TO-Cwtofw:b-n5iv2p)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 23 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KOkkrQcIa8LWcWMYKzf:-KOkkrQcIa8LWcWMYKzg:bflun9t) ([raw file](https://github.com/shakacode/react_on_rails/blob/1a4eb4a83e46c8f4f62afcbab9d6cbcef06f4ef5/spec/react_on_rails/assets_precompile_spec.rb#L23)):*
> ```Ruby
>       end
> 
>       it "doesn't create global symlink" do
> ```

"creates a relative symlink, rather than an absolute path symlink"

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 30 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KOkl7XpW1bt4sZmraGY:-KOkl7XpW1bt4sZmraGZ:b-fmcy0j) ([raw file](https://github.com/shakacode/react_on_rails/blob/1a4eb4a83e46c8f4f62afcbab9d6cbcef06f4ef5/spec/react_on_rails/assets_precompile_spec.rb#L30)):*
> ```Ruby
> 
>         expect(File.readlink(assets_path.join(digest_filename)).to_s)
>           .not_to eq(File.expand_path(assets_path.join(filename)).to_s)
> ```

Expect the readlink to equal the digest_filename?

If we test for equality, that's a bit more of a sure thing.

Only having an "expectation not" can result in a test that passes due to an error in writing the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 30 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KOkl7XpW1bt4sZmraGY:-KOkmaOxFTwX-XSsdsRH:b718usu) ([raw file](https://github.com/shakacode/react_on_rails/blob/1a4eb4a83e46c8f4f62afcbab9d6cbcef06f4ef5/spec/react_on_rails/assets_precompile_spec.rb#L30)):*
> Expect the readlink to equal the digest_filename?

Expect the readlink to equal the filename?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510)*

**Comment by dzirtusss** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 23 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KOkkrQcIa8LWcWMYKzf:-KOoF4dR6Z8fNz5eyI58:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/1a4eb4a83e46c8f4f62afcbab9d6cbcef06f4ef5/spec/react_on_rails/assets_precompile_spec.rb#L23)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> "creates a relative symlink, rather than an absolute path symlink"
</details>
Done.

---

*[spec/react_on_rails/assets_precompile_spec.rb, line 30 \[r3\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/510#-KOkl7XpW1bt4sZmraGY:-KOoF7v1HwbJTcGgSQgj:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/1a4eb4a83e46c8f4f62afcbab9d6cbcef06f4ef5/spec/react_on_rails/assets_precompile_spec.rb#L30)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> > Expect the readlink to equal the digest_filename?
> 
> Expect the readlink to equal the filename?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/510)*

**Comment by justin808** [comment]
@dzirtusss Please try to reopen this one.

**Pull request closed without merging**
