### PR TITLE
bugfix: execJS timeout

### PR DESCRIPTION
**Pull request by alleycat-at-git**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/390)

### CODE REVIEW

**Comment by justin808** [comment]
:lgtm: Thanks @alleycat-at-git 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/390#-:-KFm4alf5yQhEiLlvWiE:-1289694988)*

**Comment by justin808** [comment]
@alleycat-at-git  Please merge latest changes from master into this branch.

**Comment by alleycat-at-git** [comment]
@justin808 Done

**Comment by justin808** [comment]
Thanks @alleycat-at-git !

**Pull request merged**
