### PR TITLE
Upgrade GitHub Actions versions

### PR DESCRIPTION
**Pull request by adriangohjw**
### Summary

Node.js 16 actions are deprecated and we want to update them to use the latest actions

Reference:
`
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3, actions/cache@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
`

#### Changes

- Updated `actions/setup-node@v3` to `actions/setup-node@v4`
- Updated `actions/cache@v3` to `actions/cache@v4`
  - and also `actions/cache/save@v3` to `actions/cache/save@v4`
- Updated `actions/upload-artifact@v3` to `actions/upload-artifact@v4`
  - `Uploads are significantly faster, upwards of 90% improvement in worst case scenarios` according to the [documentation](https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new)
  - added unique artifact name due to breaking change from v3 and v4 by following [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact)

### Pull Request checklist
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._

- ~[ ] Add/update test to cover these changes~
- ~[ ] Update documentation~
- [x] Update CHANGELOG file  
  _Add the CHANGELOG entry at the top of the file._

### Other Information

_Remove this paragraph and mention any other important and relevant information such as benchmarks._

- - -
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1623)

## Summary by CodeRabbit

- **Chores**
  - Upgraded GitHub Actions to use newer versions (`setup-node@v4`, `cache@v4`, `upload-artifact@v4`) for improved performance and security.
  - Updated artifact naming conventions in workflows for better organization and tracking.

### CODE REVIEW

**Comment by justin808** [comment]
@adriangohjw can you investigate the CI failures?

**Comment by adriangohjw** [comment]
@justin808 alright will do, will look at it sometime this week 🫡

**Comment by justin808** [comment]
@adriangohjw any update?

**Comment by adriangohjw** [comment]
@justin808 sorry for the delay, fixed!

**Comment by justin808** [comment]
Thanks @adriangohjw

**Pull request merged**
