### PR TITLE
Remove unnecessary dependencies from released NPM package

### PR DESCRIPTION
**Pull request by tricknotes**
These dependencies are injected by generator spec.
However they are unnecessary for released react-on-rails package.

Even if the `dependencies` section is removed, it will back after `$ rspec spec/react_on_rails/generators/install_generator_spec.rb` is run.

I think it is unexpected behavior.
So I removed these dependencies and fix specs.

@Judahmeek @justin808
Can you review this PR? It this a correct way?

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/968)

### CODE REVIEW

**Comment by justin808** [comment]
@tricknotes Can you please rebase on top of master. Then let's see the CI results.

**Comment by tricknotes** [comment]
rebased

**Comment by tricknotes** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

https://travis-ci.org/shakacode/react_on_rails/jobs/294304640

hmm..., some tests are timeouted :<

**Comment by tricknotes** [comment]
@justin808 
Now all tests are passed on Travis CI.
Could you review this PR?

**Comment by justin808** [comment]
This looks solid to me. @Judahmeek?

**Comment by Judahmeek** [comment]
Nice work. However, I think that `react-redux` should at least be a peer dependency since it is referenced in ReactOnRails source code.

**Comment by tricknotes** [comment]
Thanks for your review, @Judahmeek !
Yes, `react-redux` is referenced by ReactOnRails.
However it seems from specs, generators and docs, not from production code.
Additionally, the ReactOnRails users who use react without redux don't need `react-redux`.

I think it may be a optional dependencies. Or I've misunderstand?

**Comment by Judahmeek** [comment]
You're correct that it is an optional dependency.

**Pull request merged**
