### PR TITLE
Change Turbolinks unmount event from before-visit to before-render

### LINKED ISSUE #706: Using turbolinks:before-visit causes too early unmount and components "flickering"
Changing unmount event to `turbolinks:before-render` causes warning. See https://github.com/shakacode/react_on_rails/issues/610

```
unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.
```

If `ReactDOM.unmountComponentAtNode` can leave rendered markup after component unmounting, then we can use `turbolinks:before-visit` and get rid of "flickering" components causing bad UX.

I filled a pull request to React adding `shouldLeaveMarkup` flag for `unmountComponentAtNode`
https://github.com/facebook/react/pull/8928

Tested these changes on my local copies of libraries and they resolve this issue.

### PR DESCRIPTION
**Pull request by szyablitsky**
fixes #706

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/709)

### CODE REVIEW

**Comment by justin808** [comment]
@volkanunsal @szyablitsky Do we have consensus on merging this one?

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/709#-:-KcWfdWERuaZ0n9lVUpk:bnfp4nl)*

**Comment by volkanunsal** [comment]
Looks good to me. 👍

**Comment by justin808** [comment]
Imagine I have to explain this to a beginner or in an insturctional video. What do I say? That needs to go in the docs.

**Comment by szyablitsky** [comment]
@justin808 it is explained here https://github.com/shakacode/react_on_rails/pull/709/files#diff-66873aa717656c99137530d5cf817527R101

**Comment by justin808** [comment]
A few comments...

My main concern is that this may not need to be configurable. I'm not convinced on why the default should be one way or another and why you'd change it.

We should provide a thorough explanation here:
https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/turbolinks.md

---

Reviewed 4 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CHANGELOG.md, line 9 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/709#-KcaFUN97ZEJp3ZxDdUH:-KcaFUN97ZEJp3ZxDdUI:bndcv5b) ([raw file](https://github.com/shakacode/react_on_rails/blob/284c0963cb4e3d0b2f2051bf53a16e63d47b60ed/CHANGELOG.md#L9)):*
> ```Markdown
> *Please add entries here for your pull requests.*
> ### Added
> - Added an option to change Turbolinks unmount event from `before-visit` to `before-render`. To allow fixing "flickering" components when they are unmounted too early [#709](https://github.com/shakacode/react_on_rails/pull/709) by [szyablitsky](https://github.com/szyablitsky)
> ```

Please reference the github "issue" as well.

---

*[docs/additional-reading/turbolinks.md, line 102 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/709#-KcaESCHaLl6Hv43ENtD:-KcaESCIBtvAfVJwt3aV:b-h8dogz) ([raw file](https://github.com/shakacode/react_on_rails/blob/284c0963cb4e3d0b2f2051bf53a16e63d47b60ed/docs/additional-reading/turbolinks.md#L102)):*
> ```Markdown
> 
> ## Unmount event
> By default Turbolinks 5 will handle `turbolinks:before-visit` event for unmounting rendered components before visiting next page. If you use the same component on different pages this can cause the temporary disappearance of component during page load and even moving the parts of the page. To fix this issue switch unmount event to `turbolinks:before-render`.
> ```

@volkanunsal @szyablitsky What is the disadvantage to always using before-render? Why did we change this to before-visit?

---

*[docs/additional-reading/turbolinks.md, line 102 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/709#-KcaEyLBDzATzE6BbHTX:-KcaEyLBDzATzE6BbHTY:b-bloi85) ([raw file](https://github.com/shakacode/react_on_rails/blob/284c0963cb4e3d0b2f2051bf53a16e63d47b60ed/docs/additional-reading/turbolinks.md#L102)):*
> To fix this issue switch unmount event to `turbolinks:before-render`.
To fix this issue set the client side option `turbolinksUnmountOnBeforeRender` to true.

---

*[docs/api/javascript-api.md, line 37 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/709#-KcaEk4pUgnMTMoygFRI:-KcaEk4pUgnMTMoygFRJ:b6dqzy0) ([raw file](https://github.com/shakacode/react_on_rails/blob/284c0963cb4e3d0b2f2051bf53a16e63d47b60ed/docs/api/javascript-api.md#L37)):*
> ```Markdown
>    * Available Options:
>    * `traceTurbolinks: true|false Gives you debugging messages on Turbolinks events
>    * `turbolinksUnmountOnBeforeRender: true|false Binds unmount to before-render event
> ```

true binds unmounting to the `before-render` event, false keeps the default behavior of `before-visit`

---

*[node_package/src/ReactOnRails.js, line 62 at r4](https://reviewable.io:443/reviews/shakacode/react_on_rails/709#-KcaFERTX6MHb6gn0GZo:-KcaFERTX6MHb6gn0GZp:b6dqzy0) ([raw file](https://github.com/shakacode/react_on_rails/blob/284c0963cb4e3d0b2f2051bf53a16e63d47b60ed/node_package/src/ReactOnRails.js#L62)):*
> ```JavaScript
>    * Available Options:
>    * `traceTurbolinks: true|false Gives you debugging messages on Turbolinks events
>    * `turbolinksUnmountOnBeforeRender: true|false Binds unmount to before-render event
> ```

true binds unmounting to the `before-render` event, false keeps the default behavior of `before-visit`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/709#-:-KcaFYgCHdFccHCPyS9X:b8npvzm)*

**Comment by szyablitsky** [comment]
Removed option and set unmount event back to `turbolinks:before-render`.

**Comment by justin808** [comment]
@volkanunsal Are you good with this change? I'd prefer not to have an extra option if it's not necessary.

**Comment by volkanunsal** [comment]
The reason I settled on before-visit initially is because it solved the
error message introduced by before-render at the time I tested it for #610.
We still don't fully understand why the double render error was being
thrown by React.

-- 
*Volkan Unsal*
*Product Engineer*
volkanunsal.com

**Comment by volkanunsal** [comment]
I'm ok with removing the configuration option.

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/709#-:-KcfvSCA3rClXVTOvu1o:bnfp4nl)*

**Comment by justin808** [comment]
Fixed in 6.5.1.

**Pull request merged**
