### PR TITLE
Add missing `else` clause, ensuring hashed filename is used for Webpacker.

### PR DESCRIPTION
**Pull request by MrJoy**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/913)

### CODE REVIEW

**Comment by justin808** [comment]
Outstanding! A couple comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/utils.rb, line 78 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-KrAC23EO3eBnR1fk9jZ:-KrAC23EO3eBnR1fk9j_:b-nuhlsr) ([raw file](https://github.com/shakacode/react_on_rails/blob/b6ef458f63e2573639967d9179c30fd40e5e01ad/lib/react_on_rails/utils.rb#L78)):*
> ```Ruby
>         hashed_name = Webpacker::Manifest.lookup(bundle_name, throw_if_missing: false)
>         hashed_name = bundle_name if hashed_name.blank?
>         Rails.root.join(File.join(Webpacker::Configuration.output_path, hashed_name)).to_s
> ```

Why do we need to add the `to_s` here? It seems that Rails.root returns a pathname, so we'd have a pathname when we want a string. 

---

*[spec/react_on_rails/utils_spec.rb, line 35 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-KrACdhOyDAk6aCODSxv:-KrACdhOyDAk6aCODSxw:b-q19pzt) ([raw file](https://github.com/shakacode/react_on_rails/blob/b6ef458f63e2573639967d9179c30fd40e5e01ad/spec/react_on_rails/utils_spec.rb#L35)):*
> ```Ruby
>         before { allow(Utils).to receive(:using_webpacker?).and_return(false) }
> 
>         it { expect(subject).to eq("public/webpack/development/webpack-bundle") }
> ```

The output file should have a `.js`. I think this just needs to get added to here and above a few places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-:-KrACv0yq7XY2j0eoU_2:b-2o1o3)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[spec/react_on_rails/utils_spec.rb, line 15 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-KrADvlTlumv5TTbwJxH:-KrADvlTlumv5TTbwJxI:by7cj30) ([raw file](https://github.com/shakacode/react_on_rails/blob/b6ef458f63e2573639967d9179c30fd40e5e01ad/spec/react_on_rails/utils_spec.rb#L15)):*
> ```Ruby
> 
>       subject do
>         Utils.bundle_js_file_path('webpack-bundle')
> ```

I think it's fine here to use `'webpack-bundle.js'`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/913)*

**Comment by justin808** [comment]
@MrJoy,  Try:

`rubocop -a`

```
Inspecting 115 files
..........C........................................................................................................
Offenses:
spec/react_on_rails/utils_spec.rb:11:32: C: Layout/MultilineMethodCallIndentation: Use 2 (not 23) spaces for indenting an expression spanning multiple lines.
                               .and_return("public/webpack/development")
                               ^^^^^^^^^^^
spec/react_on_rails/utils_spec.rb:15:35: C: Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
        Utils.bundle_js_file_path('webpack-bundle')
                                  ^^^^^^^^^^^^^^^^
spec/react_on_rails/utils_spec.rb:22:46: C: Layout/MultilineMethodCallIndentation: Use 2 (not 35) spaces for indenting an expression spanning multiple lines.
                                             .and_return("public/webpack/development")
                                             ^^^^^^^^^^^
spec/react_on_rails/utils_spec.rb:24:41: C: Layout/MultilineMethodCallIndentation: Use 2 (not 30) spaces for indenting an expression spanning multiple lines.
                                        .with("webpack-bundle", throw_if_missing: false)
                                        ^^^^^
spec/react_on_rails/utils_spec.rb:25:41: C: Layout/MultilineMethodCallIndentation: Use 2 (not 30) spaces for indenting an expression spanning multiple lines.
                                        .and_return("webpack-bundle-0123456789abcdef")
                                        ^^^^^^^^^^^
115 files inspected, 5 offenses detected
```

**Comment by MrJoy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/utils.rb, line 78 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-KrAC23EO3eBnR1fk9jZ:-KrCDc_5_pFwK3CeDuZK:bxmh8zt) ([raw file](https://github.com/shakacode/react_on_rails/blob/b6ef458f63e2573639967d9179c30fd40e5e01ad/lib/react_on_rails/utils.rb#L78)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Why do we need to add the `to_s` here? It seems that Rails.root returns a pathname, so we'd have a pathname when we want a string. 
</blockquote></details>

As the other side of the conditional returns a `String`, I was concerned about exactly introducing a sharp corner to the interface:  People might come to expect that they always get a `String` or a `Pathname` -- depending on what configuration they start with -- and build up their own dependency on that semantic.  This could leave them surprised by changing the configuration.

I'd also be amenable to wrapping the `String` in a `Pathname` for the `else` clause, of course.

---

*[spec/react_on_rails/utils_spec.rb, line 15 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-KrADvlTlumv5TTbwJxH:-KrCEBibNinNKfZLpI7B:b-q9zpd0) ([raw file](https://github.com/shakacode/react_on_rails/blob/b6ef458f63e2573639967d9179c30fd40e5e01ad/spec/react_on_rails/utils_spec.rb#L15)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I think it's fine here to use `'webpack-bundle.js'`.
</blockquote></details>

Will update.

---

*[spec/react_on_rails/utils_spec.rb, line 35 at r1](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-KrACdhOyDAk6aCODSxv:-KrCEDK2T6vvVaRd8_v_:b-q9zpd0) ([raw file](https://github.com/shakacode/react_on_rails/blob/b6ef458f63e2573639967d9179c30fd40e5e01ad/spec/react_on_rails/utils_spec.rb#L35)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

The output file should have a `.js`. I think this just needs to get added to here and above a few places.
</blockquote></details>

Will update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/913)*

**Comment by MrJoy** [comment]
Updated to address style issues.

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-:-KrCG5KrPSbq3U83ZbLV:b-yxlski)*

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/913#-:-KrDVizL-tOKg4nPq8-h:bnfp4nl)*

**Pull request merged**
