### PR TITLE
react_component outside of view

### PR DESCRIPTION
**Pull request by jtibbertsma**
Here's a failing test case that demonstrates #634

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/636)

### CODE REVIEW

**Comment by justin808** [comment]
@jtibbertsma can you include the fix with the test? CI needs to pass before we can merge.

**Comment by jtibbertsma** [comment]
I'm not sure why CI failed. It seems to have failed during an npm install.

**Comment by jtibbertsma** [comment]
screen shot 2016-12-05 at 7 51 20 pm

**Comment by justin808** [comment]
@jtibbertsma Please create a changelog entry. Once tests pass, I'll create a release.

**Pull request merged**
