### PR TITLE
Feature/cleanup react components

### PR DESCRIPTION
**Pull request by lifeiscontent**
@justin808 I updated all the react components in the dummy app to use the new [Stateless Functional Components](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components) signature

as well as upgrade the new react-router signature

[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/282)

### CODE REVIEW

**Comment by justin808** [comment]
**EXCELLENT**. One main concern is that we have at least one registered component does the extend React.Component, as we need to make sure the internals of ReactOnRails can handle that.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[spec/dummy/client/app/components/HelloWorldContainer.jsx, line 27 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnHvn5IAK19vcs8KYY:-KAnHvn5IAK19vcs8KYZ:2108266277) ([raw file](https://github.com/shakacode/react_on_rails/blob/49ca68718fd84ccd60de4f8bfc3cccfbcb53fcd5/spec/dummy/client/app/components/HelloWorldContainer.jsx#L27)):*
@alexfedoseev I guess this is the new react-redux API. Way more readable!

CC: @robwise 

---

*[spec/dummy/client/app/components/HelloWorldContainer.jsx, line 31 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnHWGkKymsrdPDf54J:-KAnHWGlTXt54M-bIeKn:2142988675) ([raw file](https://github.com/shakacode/react_on_rails/blob/0b8d8894ef6d3c29d23b6c883c3ce539c24104d2/spec/dummy/client/app/components/HelloWorldContainer.jsx#L31)):*
We need to be sure that we have examples of:

* React.createClass
* extends React.Component
* pure render function

So yes, this could be written as a pure render function, but we're losing test fidelity.

BTW, this code looks great!

---

*[spec/dummy/client/app/components/RouterSecondPage.jsx, line 12 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnIarFK9crTZNbWNSi:-KAnIarFK9crTZNbWNSj:-1337502329) ([raw file](https://github.com/shakacode/react_on_rails/blob/49ca68718fd84ccd60de4f8bfc3cccfbcb53fcd5/spec/dummy/client/app/components/RouterSecondPage.jsx#L12)):*
We could just have the export default above and inline the variable.

@robwise @alexfedoseev ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-:-KAnIzk9EMGKKhgIGG5_:-1252132256)*

**Comment by lifeiscontent** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[spec/dummy/client/app/components/RouterSecondPage.jsx, line 12 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnIarFK9crTZNbWNSi:-KAnJc_kh_Z_bsG2y-ye:1679438184) ([raw file](https://github.com/shakacode/react_on_rails/blob/49ca68718fd84ccd60de4f8bfc3cccfbcb53fcd5/spec/dummy/client/app/components/RouterSecondPage.jsx#L12)):*
@justin808 I generally like to name things because it allows for less friction when you need to add something like PropTypes to a component.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/282)*

**Comment by lifeiscontent** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[spec/dummy/client/app/components/HelloWorldContainer.jsx, line 31 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnHWGkKymsrdPDf54J:-KAnKdM9_H35SBHheMEa:1236355783) ([raw file](https://github.com/shakacode/react_on_rails/blob/0b8d8894ef6d3c29d23b6c883c3ce539c24104d2/spec/dummy/client/app/components/HelloWorldContainer.jsx#L31)):*
@justin808 sounds good, just let me know what I should change and I'll do that! :smile: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/282)*

**Comment by alexfedoseev** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[spec/dummy/client/app/components/HelloWorldContainer.jsx, line 27 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnHvn5IAK19vcs8KYY:-KAnoTgpRucNEw3CaXuL:-2072684294) ([raw file](https://github.com/shakacode/react_on_rails/blob/49ca68718fd84ccd60de4f8bfc3cccfbcb53fcd5/spec/dummy/client/app/components/HelloWorldContainer.jsx#L27)):*
Looks all the same for me, but w/o decorators (look in fng properties container), what actually changed? 

BTW decorators waaaay more readable when you need to apply more than one HOC.

---

*[spec/dummy/client/app/components/RouterSecondPage.jsx, line 12 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnIarFK9crTZNbWNSi:-KAnpZM_OJDn0pD1oQgd:-15485413) ([raw file](https://github.com/shakacode/react_on_rails/blob/49ca68718fd84ccd60de4f8bfc3cccfbcb53fcd5/spec/dummy/client/app/components/RouterSecondPage.jsx#L12)):*
Currently we use `class` way to define React components, and add `propTypes` via `static`s, b/c pure functions have limited functionality, so usually we export default the named class.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/282)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[spec/dummy/client/app/components/HelloWorldContainer.jsx, line 27 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnHvn5IAK19vcs8KYY:-KAo7UFykBrzAD51dwLO:-1940953820) ([raw file](https://github.com/shakacode/react_on_rails/blob/49ca68718fd84ccd60de4f8bfc3cccfbcb53fcd5/spec/dummy/client/app/components/HelloWorldContainer.jsx#L27)):*
@alexfedoseev HOC? 

@aaronvb Is this from the latest docs?

---

*[spec/dummy/client/app/components/HelloWorldContainer.jsx, line 31 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnHWGkKymsrdPDf54J:-KAo7GT2RXy3AuBko4t7:-1943964394) ([raw file](https://github.com/shakacode/react_on_rails/blob/0b8d8894ef6d3c29d23b6c883c3ce539c24104d2/spec/dummy/client/app/components/HelloWorldContainer.jsx#L31)):*
You probably should just make this one extend the 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/282)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/dummy/client/app/components/HelloWorldWithLogAndThrow.jsx, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAo9_RqdNoN2KISx6j3:-KAo9_RrzyisnevbPfAN:-1047540890) ([raw file](https://github.com/shakacode/react_on_rails/blob/49ca68718fd84ccd60de4f8bfc3cccfbcb53fcd5/spec/dummy/client/app/components/HelloWorldWithLogAndThrow.jsx#L5)):*
We've got one component that meets the "have one component" so we're all set.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/282)*

**Comment by justin808** [comment]
Thanks @lifeiscontent. Nice Job!

:clap:

**Comment by alexfedoseev** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/dummy/client/app/components/HelloWorldContainer.jsx, line 27 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-KAnHvn5IAK19vcs8KYY:-KAoFj0joHtbV8CYsxCF:-960422855) ([raw file](https://github.com/shakacode/react_on_rails/blob/49ca68718fd84ccd60de4f8bfc3cccfbcb53fcd5/spec/dummy/client/app/components/HelloWorldContainer.jsx#L27)):*
Higher-order Components. Here is an example w/ just 2 HOCs:

```js
// w/ decorators
@doOneThing(withParams)
@doAnotherThing(withAnotherParams)
class Foo { ... }

// w/o decorators
doOneThing(withParams)(doAnotherThing(withAnotherParams)(Foo))
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/282)*

**Comment by lifeiscontent** [comment]
@alexfedoseev aren't decorators deprecated? That's what I think I've read.

**Comment by alexfedoseev** [comment]
@lifeiscontent They aren't deprecated, decorator's draft is being reworked and this is why they temporarily removed from Babel. So they're not going anywhere, at least I hope.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/282#-:-KB2vute-GS9Htbobw_X:-1666479618)*

**Pull request merged**
