### PR TITLE
Fix unmounting in React 18

### PR DESCRIPTION
**Pull request by alexeyr-ci1**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1466)

### CODE REVIEW

**Comment by alexeyr-ci1** [comment]
Depends on #1460.

**Comment by justin808** [comment]
@tomdracz, @summera Any chance that you can take a look here?

LGTM.

@alexeyr-ci1 what's left for React 18?

**Comment by alexeyr-ci1** [comment]
> @alexeyr-ci1 what's left for React 18?

#1463 and the third task in #1464 (but that's just a doc change). Unless we come up with some nice idea about avoiding multiple roots, but that's probably in the future.

**Comment by summera** [comment]
Looks good!

**Comment by justin808** [comment]
If CI passes with react 18 in spec/dummy, I'm merging.

**Review by justin808 — APPROVED** [review]

**Pull request merged**
