### PR TITLE
Improve EnsureAssetsCompiled logic to wait for webpack process to finish

### PR DESCRIPTION
**Pull request by robwise**
Because there may be situations where a user is running a webpack
process in watch mode in the background that will recompile the
assets, it is possible that if the build time is extremely long,
the user could start their test suite before the build completes. In this case,
`EnsureAssetsCompiled` would start compiling the assets again even
though there is already a webpack process doing that.

This commit adds behavior to `EnsureAssetsCompiled` to check whether
or not the webpack process is running in the background, and, if so, will
defer the responsibility of compilation to that process, re-checking
the compiled assets every second until they are up to date.

[Review on Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/253)

### CODE REVIEW

**Comment by justin808** [comment]
Looking great!

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 56 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dG6wo_TtrjXDk-BLK:-K9dG6wo_TtrjXDk-BLL:1232486338) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/ensure_assets_compiled.rb#L56)):*
Please display a message how to do this more efficient, by running blah, blah, blah, etc. or a doc link.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 63 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGH55pIGIxVmdQooB:-K9dGH55pIGIxVmdQooC:-1628873360) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/ensure_assets_compiled.rb#L63)):*
It will be confusing if one or the other is not running. I'd recommend we error out  in the case of we detect one but not the other. FAIL FAST!

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 72 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGSWpAX8L9795Bn2G:-K9dGSWpAX8L9795Bn2H:-830941552) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/ensure_assets_compiled.rb#L72)):*
Did you test this?
It's `(-w|--watch)`

-watch is not correct

---

*[lib/react_on_rails/utils.rb, line 14 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGkEHx4sFvb2LComG:-K9dGkEHx4sFvb2LComH:-1640451822) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/utils.rb#L14)):*
This is a global.

IDEALLY, we should run both client and server concurrently, rather than sequentially, but you can defer on that one.


Where are you capturing the results? and aborting if not success?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-:-K9dHPrhNcK2UiWynAth:-781840010)*

**Comment by robwise** [comment]
Reviewed 2 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 56 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dG6wo_TtrjXDk-BLK:-K9dJdSuXh8pll_V8KlI:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/ensure_assets_compiled.rb#L56)):*
Done.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 63 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGH55pIGIxVmdQooB:-K9dKtpgKxMY0FUg3QTS:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/ensure_assets_compiled.rb#L63)):*
Done.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 72 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGSWpAX8L9795Bn2G:-K9dKuQAiHnkfe0-6cL4:1574155594) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/ensure_assets_compiled.rb#L72)):*
Tested in one of those regex websites as well as the spec dummy (which uses just the `-w` so I forgot about the double dash when passing the long form). 

Done.

---

*[lib/react_on_rails/utils.rb, line 14 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGkEHx4sFvb2LComG:-K9dMTzzfNuqBTPyavrz:1373617595) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/utils.rb#L14)):*
`WebpackAssetsCompiler#compile`: https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/ensure_assets_compiled.rb#L36

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by robwise** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by justin808** [comment]
More great code. Couple minor comments.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 57 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9eWoXjiQhP6YnxdhwZ:-K9eWoXjiQhP6Ynxdhw_:-1124661348) ([raw file](https://github.com/shakacode/react_on_rails/blob/c94e859c126eacdbc99da62843f84de4b8ff21b9/lib/react_on_rails/ensure_assets_compiled.rb#L57)):*
Too vague. Show what you are matching. Plus a doc link!

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 79 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9eX-V4t7KSDD1DJrM-:-K9eX-V4t7KSDD1DJrM0:262468467) ([raw file](https://github.com/shakacode/react_on_rails/blob/c94e859c126eacdbc99da62843f84de4b8ff21b9/lib/react_on_rails/ensure_assets_compiled.rb#L79)):*
:thumbsup: 

---

*[lib/react_on_rails/utils.rb, line 14 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGkEHx4sFvb2LComG:-K9eXKLCi-0dHEz9CAXo:-1866424024) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/utils.rb#L14)):*
Are we sure that we can rely on the content having error. Sometimes we have files with the word error in the file name. I prefer the exit code if that is reliable for knowing we failed. Or if we are **SURE**, then this is OK.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-:-K9eXdkqOBQWrrIK-bfg:540364167)*

**Comment by robwise** [comment]
Reviewed 2 of 3 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 57 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9eWoXjiQhP6YnxdhwZ:-K9jm6xv6IH8tvAJz67V:1669703794) ([raw file](https://github.com/shakacode/react_on_rails/blob/c94e859c126eacdbc99da62843f84de4b8ff21b9/lib/react_on_rails/ensure_assets_compiled.rb#L57)):*
Okay the link to the docs was a little long, so check how I did it. I can change if you want the full-length link in there. It's this, unless I can shorten it somehow but I can't remember?: `https://github.com/shakacode/react_on_rails/blob/master/docs/additional_reading/rspec_configuration.md`

I'm not sure what you meant by matching here though, I'm not matching anything. This is just the output that happens after we compile the bundle.

---

*[lib/react_on_rails/utils.rb, line 14 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGkEHx4sFvb2LComG:-K9jk9ECDqC-2peU3PGr:1439293079) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/utils.rb#L14)):*
@justin808 wait I'm confused, you originally wrote it so it was grepping for the word "error," but my commit changes that to use the exit status. That link is to the current implementation of `WebpackAssetsCompiler#compile` on master, the new implementation uses this helper I wrote here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 57 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9eWoXjiQhP6YnxdhwZ:-K9k16h9XnxUzayj5XkM:-1668290841) ([raw file](https://github.com/shakacode/react_on_rails/blob/c94e859c126eacdbc99da62843f84de4b8ff21b9/lib/react_on_rails/ensure_assets_compiled.rb#L57)):*
You need the full URL. Yes, it's long. It's worth it.

---

*[lib/react_on_rails/utils.rb, line 14 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGkEHx4sFvb2LComG:-K9k1H9Aty-2vpSmFC4J:270331541) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/utils.rb#L14)):*
OK -- so long as you can display the error when you exit due to this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by robwise** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 57 \[r2\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9eWoXjiQhP6YnxdhwZ:-K9mNyHZdMphgkSEJs2h:-499146009) ([raw file](https://github.com/shakacode/react_on_rails/blob/c94e859c126eacdbc99da62843f84de4b8ff21b9/lib/react_on_rails/ensure_assets_compiled.rb#L57)):*
Done.

---

*[lib/react_on_rails/utils.rb, line 14 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9dGkEHx4sFvb2LComG:-K9mO1-kK0aXEdXfpoVy:-296349261) ([raw file](https://github.com/shakacode/react_on_rails/blob/8c395c963d77ebde737ea33b0e42f71d698afe53/lib/react_on_rails/utils.rb#L14)):*
@justin808 Yep, this method is the best of both worlds in this sense. Here is the link to the same place but how I have it in this PR: https://github.com/shakacode/react_on_rails/blob/rob/improve-ensure-assets-compiled/lib/react_on_rails/ensure_assets_compiled.rb#L54

Notice I'm still capturing the output of the process, then I check the exit code, and if the exit code is a failure, then I log an error message that includes the captured output so they know what the error was.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by robwise** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by justin808** [comment]
:lgtm_strong: 

Amazing job @robwise! 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-:-K9n42S4eFKzP_KriUUv:-823989951)*

**Comment by justin808** [comment]
Please merge, ensure changelog updated, docs ready etc. and let me know if I should release later today.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-:-K9n46Nh1pw2f-JnbjbC:32968328)*

**Comment by robwise** [comment]
Latest code makes it so we only run once per suite run (assuming the suite has a feature test in it) instead of running every feature test.

Also, the config now allows for specifying where webpack is outputting generated files. By default, this is `app/assets/javascripts/generated` and `app/assets/stylesheets/generated` so that we don't break any current builds that are following the convention of the generators.

Lastly, we were using unix file separators in the configuration which I changed to be platform-dependent.

@justin808 I think I should just update the docs in PR 252 to include this information, right?

---

Reviewed 3 of 4 files at r5, 1 of 1 files at r6.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 5 \[r5\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9nxQdugWpSyY6YT_Z7:-K9nxQdvWnf3AvzwpK4_:-1161018597) ([raw file](https://github.com/shakacode/react_on_rails/blob/2c4e00ea4e5c6998d0d540e407479edab982ea4a/lib/react_on_rails/ensure_assets_compiled.rb#L5)):*
I had to do it this way because linter doesn't like it when I use `@@`. Supposedly that's a bad practice because subclasses have access to the variable. Whatevs

---

*[lib/react_on_rails/webpack_assets_status_checker.rb, line 14 \[r5\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9nyyiVz1mqhQp532kG:-K9nyyiVz1mqhQp532kH:1889247980) ([raw file](https://github.com/shakacode/react_on_rails/blob/2c4e00ea4e5c6998d0d540e407479edab982ea4a/lib/react_on_rails/webpack_assets_status_checker.rb#L14)):*
This was only temporarily necessary, pls ignore

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-:-K9nvvvErgdUCv8lru5h:-1894541371)*

**Comment by justin808** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 5 \[r5\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9nxQdugWpSyY6YT_Z7:-K9pp5vuH7I8HOCcXnTy:1798441257) ([raw file](https://github.com/shakacode/react_on_rails/blob/2c4e00ea4e5c6998d0d540e407479edab982ea4a/lib/react_on_rails/ensure_assets_compiled.rb#L5)):*
Correct.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 44 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9ppCvPXj7C8RG5LPur:-K9ppCvPXj7C8RG5LPus:-1012702347) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L44)):*
I personally think we should have one class per file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by justin808** [comment]
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 16 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pprYGwF9BZunNSVth:-K9pprYGwF9BZunNSVti:-393368691) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L16)):*
Is there a return value that is useful from this call? I don't see anything useful other than to call `call` from this created object.

Just use a static calls


You can make this one API:

`ReactOnRails::EnsureAssetsCompiled.call(client_assets_checker:, server_assets_checker:, process_checker:)`

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 21 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9ppY0a2UdcBNkXsNHa:-K9ppY0bJq1vjuwX0cF9:524033889) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L21)):*
This API is really awkward. 

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 21 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pqnLLFkSu6zYOwSri:-K9pqnLLFkSu6zYOwSrj:1367483142) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L21)):*
we don't need this method  -- just use static calls

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 27 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pqchcw3SHyuoGJ8Ac:-K9pqchcw3SHyuoGJ8Ad:1134383512) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L27)):*
Make this method static


    return if @has_been_run

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by justin808** [comment]
A couple comments.

---

Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-:-K9prPVymjgFCFFhqJZQ:-283569122)*

**Comment by robwise** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 16 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pprYGwF9BZunNSVth:-K9tMw-EEDh-v1ZbVh5k:274098923) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L16)):*
@samnang what's your thoughts here? I was trying to follow the style you taught me when pairing, but maybe this is a different case?

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 21 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9ppY0a2UdcBNkXsNHa:-K9tMfTIkWTO_weixmGL:-38575684) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L21)):*
@justin808 suggestions?

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 21 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pqnLLFkSu6zYOwSri:-K9tMkZzu8fJSAwa_huo:1421020849) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L21)):*
@justin808 I need DI for tests tho

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 44 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9ppCvPXj7C8RG5LPur:-K9tN3mPru88BkAPRnGj:-519571546) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L44)):*
@samnang what is the convention in Ruby if I'm creating a utility class that is only ever used by this other class

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 27 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pqchcw3SHyuoGJ8Ac:-K9tNZuacJ_YVjhkk5aq:488851823) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L27)):*
I have instance-level dependencies in this method in the form of `webpack_process_checker` and `webpack_assets_checker`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 21 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pqnLLFkSu6zYOwSri:-K9tStyIO2HHn5So6s6c:-944429927) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L21)):*
Please don't ever sacrifice the end code API for tests.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 27 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pqchcw3SHyuoGJ8Ac:-K9tT3fa7jn30IDat4Se:433663397) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L27)):*
You can pass those, in just have defaults.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 44 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9ppCvPXj7C8RG5LPur:-K9tTcxNrRdhInIQC8ik:1960295026) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L44)):*
You can/should test the other classes. I don't see why you'd have multiple classes in one file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/react_on_rails/ensure_assets_compiled.rb, line 44 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9ppCvPXj7C8RG5LPur:-K9toyFDsLLXQevGMUYF:1919060130) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L44)):*
I can move the classes to separate files, I was just following what I was shown. I have extracted these other classes specifically because they are simple wrappers on third-party libraries/applications. This isolates dependencies on webpack and running webpack processes as well as using the `pgrep`. To test these would just be testing the unix `pgrep` utility or webpack themselves.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by samnang** [comment]
*[lib/react_on_rails/ensure_assets_compiled.rb, line 44 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9ppCvPXj7C8RG5LPur:-K9wfppHafF1IkzEA4Qh:606552155) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L44)):*
If it's very simple class and ever used as their internal functionality, it's okay to leave it there, but if it's not simple, better to have it in another file, but it still in the namespace under it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by samnang** [comment]
*[lib/react_on_rails/ensure_assets_compiled.rb, line 16 \[r6\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/253#-K9pprYGwF9BZunNSVth:-K9wgjBHZoyLPelQDeY9:-1965324622) ([raw file](https://github.com/shakacode/react_on_rails/blob/fef644e65ff15cc7d36c94be694585557f92249c/lib/react_on_rails/ensure_assets_compiled.rb#L16)):*
In this case, you could inline here. The benefit to use dependency injection in constructor, so you could have more than one public methods, and extract some functionality in private methods. For static methods, if you want to extract methods, you have to always pass parameters, and then we don't get any benefit from encapsulation.   

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by justin808** [comment]
Let's merge if this passes CI.

**Comment by robwise** [comment]
Reviewed 20 of 20 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react_on_rails/253)*

**Comment by justin808** [comment]
**BOOM** :tada:

**Pull request merged**
